// neo4j_service.proto - Neo4j Graph Database gRPC Service
// Powerful graph database for connected data and relationship queries

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: neo4j_service.proto

package neo4j

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Neo4JService_RunCypher_FullMethodName             = "/isa.neo4j.Neo4jService/RunCypher"
	Neo4JService_RunCypherRead_FullMethodName         = "/isa.neo4j.Neo4jService/RunCypherRead"
	Neo4JService_RunCypherWrite_FullMethodName        = "/isa.neo4j.Neo4jService/RunCypherWrite"
	Neo4JService_RunCypherBatch_FullMethodName        = "/isa.neo4j.Neo4jService/RunCypherBatch"
	Neo4JService_CreateNode_FullMethodName            = "/isa.neo4j.Neo4jService/CreateNode"
	Neo4JService_GetNode_FullMethodName               = "/isa.neo4j.Neo4jService/GetNode"
	Neo4JService_UpdateNode_FullMethodName            = "/isa.neo4j.Neo4jService/UpdateNode"
	Neo4JService_DeleteNode_FullMethodName            = "/isa.neo4j.Neo4jService/DeleteNode"
	Neo4JService_MergeNode_FullMethodName             = "/isa.neo4j.Neo4jService/MergeNode"
	Neo4JService_FindNodes_FullMethodName             = "/isa.neo4j.Neo4jService/FindNodes"
	Neo4JService_CreateRelationship_FullMethodName    = "/isa.neo4j.Neo4jService/CreateRelationship"
	Neo4JService_GetRelationship_FullMethodName       = "/isa.neo4j.Neo4jService/GetRelationship"
	Neo4JService_UpdateRelationship_FullMethodName    = "/isa.neo4j.Neo4jService/UpdateRelationship"
	Neo4JService_DeleteRelationship_FullMethodName    = "/isa.neo4j.Neo4jService/DeleteRelationship"
	Neo4JService_FindRelationships_FullMethodName     = "/isa.neo4j.Neo4jService/FindRelationships"
	Neo4JService_GetNeighbors_FullMethodName          = "/isa.neo4j.Neo4jService/GetNeighbors"
	Neo4JService_GetPath_FullMethodName               = "/isa.neo4j.Neo4jService/GetPath"
	Neo4JService_GetShortestPath_FullMethodName       = "/isa.neo4j.Neo4jService/GetShortestPath"
	Neo4JService_GetAllPaths_FullMethodName           = "/isa.neo4j.Neo4jService/GetAllPaths"
	Neo4JService_PageRank_FullMethodName              = "/isa.neo4j.Neo4jService/PageRank"
	Neo4JService_BetweennessCentrality_FullMethodName = "/isa.neo4j.Neo4jService/BetweennessCentrality"
	Neo4JService_CommunityDetection_FullMethodName    = "/isa.neo4j.Neo4jService/CommunityDetection"
	Neo4JService_CreateIndex_FullMethodName           = "/isa.neo4j.Neo4jService/CreateIndex"
	Neo4JService_DropIndex_FullMethodName             = "/isa.neo4j.Neo4jService/DropIndex"
	Neo4JService_ListIndexes_FullMethodName           = "/isa.neo4j.Neo4jService/ListIndexes"
	Neo4JService_CreateConstraint_FullMethodName      = "/isa.neo4j.Neo4jService/CreateConstraint"
	Neo4JService_DropConstraint_FullMethodName        = "/isa.neo4j.Neo4jService/DropConstraint"
	Neo4JService_ListConstraints_FullMethodName       = "/isa.neo4j.Neo4jService/ListConstraints"
	Neo4JService_BeginTransaction_FullMethodName      = "/isa.neo4j.Neo4jService/BeginTransaction"
	Neo4JService_CommitTransaction_FullMethodName     = "/isa.neo4j.Neo4jService/CommitTransaction"
	Neo4JService_RollbackTransaction_FullMethodName   = "/isa.neo4j.Neo4jService/RollbackTransaction"
	Neo4JService_GetDatabaseInfo_FullMethodName       = "/isa.neo4j.Neo4jService/GetDatabaseInfo"
	Neo4JService_ListDatabases_FullMethodName         = "/isa.neo4j.Neo4jService/ListDatabases"
	Neo4JService_GetStatistics_FullMethodName         = "/isa.neo4j.Neo4jService/GetStatistics"
	Neo4JService_HealthCheck_FullMethodName           = "/isa.neo4j.Neo4jService/HealthCheck"
)

// Neo4JServiceClient is the client API for Neo4JService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type Neo4JServiceClient interface {
	// RunCypher - Execute Cypher query
	RunCypher(ctx context.Context, in *RunCypherRequest, opts ...grpc.CallOption) (*RunCypherResponse, error)
	// RunCypherRead - Execute read-only Cypher query
	RunCypherRead(ctx context.Context, in *RunCypherReadRequest, opts ...grpc.CallOption) (*RunCypherReadResponse, error)
	// RunCypherWrite - Execute write Cypher query
	RunCypherWrite(ctx context.Context, in *RunCypherWriteRequest, opts ...grpc.CallOption) (*RunCypherWriteResponse, error)
	// RunCypherBatch - Execute multiple Cypher queries in batch
	RunCypherBatch(ctx context.Context, in *RunCypherBatchRequest, opts ...grpc.CallOption) (*RunCypherBatchResponse, error)
	// CreateNode - Create a new node
	CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error)
	// GetNode - Retrieve node by ID
	GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error)
	// UpdateNode - Update node properties
	UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error)
	// DeleteNode - Delete node
	DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error)
	// MergeNode - Create or update node (MERGE)
	MergeNode(ctx context.Context, in *MergeNodeRequest, opts ...grpc.CallOption) (*MergeNodeResponse, error)
	// FindNodes - Find nodes by label and properties
	FindNodes(ctx context.Context, in *FindNodesRequest, opts ...grpc.CallOption) (*FindNodesResponse, error)
	// CreateRelationship - Create relationship between nodes
	CreateRelationship(ctx context.Context, in *CreateRelationshipRequest, opts ...grpc.CallOption) (*CreateRelationshipResponse, error)
	// GetRelationship - Retrieve relationship by ID
	GetRelationship(ctx context.Context, in *GetRelationshipRequest, opts ...grpc.CallOption) (*GetRelationshipResponse, error)
	// UpdateRelationship - Update relationship properties
	UpdateRelationship(ctx context.Context, in *UpdateRelationshipRequest, opts ...grpc.CallOption) (*UpdateRelationshipResponse, error)
	// DeleteRelationship - Delete relationship
	DeleteRelationship(ctx context.Context, in *DeleteRelationshipRequest, opts ...grpc.CallOption) (*DeleteRelationshipResponse, error)
	// FindRelationships - Find relationships by type and properties
	FindRelationships(ctx context.Context, in *FindRelationshipsRequest, opts ...grpc.CallOption) (*FindRelationshipsResponse, error)
	// GetNeighbors - Get neighboring nodes
	GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error)
	// GetPath - Find path between two nodes
	GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error)
	// GetShortestPath - Find shortest path between nodes
	GetShortestPath(ctx context.Context, in *GetShortestPathRequest, opts ...grpc.CallOption) (*GetShortestPathResponse, error)
	// GetAllPaths - Find all paths between nodes
	GetAllPaths(ctx context.Context, in *GetAllPathsRequest, opts ...grpc.CallOption) (*GetAllPathsResponse, error)
	// PageRank - Run PageRank algorithm
	PageRank(ctx context.Context, in *PageRankRequest, opts ...grpc.CallOption) (*PageRankResponse, error)
	// BetweennessCentrality - Calculate betweenness centrality
	BetweennessCentrality(ctx context.Context, in *BetweennessCentralityRequest, opts ...grpc.CallOption) (*BetweennessCentralityResponse, error)
	// CommunityDetection - Detect communities in graph
	CommunityDetection(ctx context.Context, in *CommunityDetectionRequest, opts ...grpc.CallOption) (*CommunityDetectionResponse, error)
	// CreateIndex - Create index on label/property
	CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error)
	// DropIndex - Drop an index
	DropIndex(ctx context.Context, in *DropIndexRequest, opts ...grpc.CallOption) (*DropIndexResponse, error)
	// ListIndexes - List all indexes
	ListIndexes(ctx context.Context, in *ListIndexesRequest, opts ...grpc.CallOption) (*ListIndexesResponse, error)
	// CreateConstraint - Create uniqueness or existence constraint
	CreateConstraint(ctx context.Context, in *CreateConstraintRequest, opts ...grpc.CallOption) (*CreateConstraintResponse, error)
	// DropConstraint - Drop a constraint
	DropConstraint(ctx context.Context, in *DropConstraintRequest, opts ...grpc.CallOption) (*DropConstraintResponse, error)
	// ListConstraints - List all constraints
	ListConstraints(ctx context.Context, in *ListConstraintsRequest, opts ...grpc.CallOption) (*ListConstraintsResponse, error)
	// BeginTransaction - Start a new transaction
	BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error)
	// CommitTransaction - Commit transaction
	CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*CommitTransactionResponse, error)
	// RollbackTransaction - Rollback transaction
	RollbackTransaction(ctx context.Context, in *RollbackTransactionRequest, opts ...grpc.CallOption) (*RollbackTransactionResponse, error)
	// GetDatabaseInfo - Get database information
	GetDatabaseInfo(ctx context.Context, in *GetDatabaseInfoRequest, opts ...grpc.CallOption) (*GetDatabaseInfoResponse, error)
	// ListDatabases - List all databases
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error)
	// GetStatistics - Get database statistics
	GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error)
	// HealthCheck - Service health check
	HealthCheck(ctx context.Context, in *Neo4JHealthCheckRequest, opts ...grpc.CallOption) (*Neo4JHealthCheckResponse, error)
}

type neo4JServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewNeo4JServiceClient(cc grpc.ClientConnInterface) Neo4JServiceClient {
	return &neo4JServiceClient{cc}
}

func (c *neo4JServiceClient) RunCypher(ctx context.Context, in *RunCypherRequest, opts ...grpc.CallOption) (*RunCypherResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCypherResponse)
	err := c.cc.Invoke(ctx, Neo4JService_RunCypher_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) RunCypherRead(ctx context.Context, in *RunCypherReadRequest, opts ...grpc.CallOption) (*RunCypherReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCypherReadResponse)
	err := c.cc.Invoke(ctx, Neo4JService_RunCypherRead_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) RunCypherWrite(ctx context.Context, in *RunCypherWriteRequest, opts ...grpc.CallOption) (*RunCypherWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCypherWriteResponse)
	err := c.cc.Invoke(ctx, Neo4JService_RunCypherWrite_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) RunCypherBatch(ctx context.Context, in *RunCypherBatchRequest, opts ...grpc.CallOption) (*RunCypherBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RunCypherBatchResponse)
	err := c.cc.Invoke(ctx, Neo4JService_RunCypherBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) CreateNode(ctx context.Context, in *CreateNodeRequest, opts ...grpc.CallOption) (*CreateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateNodeResponse)
	err := c.cc.Invoke(ctx, Neo4JService_CreateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) GetNode(ctx context.Context, in *GetNodeRequest, opts ...grpc.CallOption) (*GetNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNodeResponse)
	err := c.cc.Invoke(ctx, Neo4JService_GetNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) UpdateNode(ctx context.Context, in *UpdateNodeRequest, opts ...grpc.CallOption) (*UpdateNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateNodeResponse)
	err := c.cc.Invoke(ctx, Neo4JService_UpdateNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) DeleteNode(ctx context.Context, in *DeleteNodeRequest, opts ...grpc.CallOption) (*DeleteNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteNodeResponse)
	err := c.cc.Invoke(ctx, Neo4JService_DeleteNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) MergeNode(ctx context.Context, in *MergeNodeRequest, opts ...grpc.CallOption) (*MergeNodeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MergeNodeResponse)
	err := c.cc.Invoke(ctx, Neo4JService_MergeNode_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) FindNodes(ctx context.Context, in *FindNodesRequest, opts ...grpc.CallOption) (*FindNodesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindNodesResponse)
	err := c.cc.Invoke(ctx, Neo4JService_FindNodes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) CreateRelationship(ctx context.Context, in *CreateRelationshipRequest, opts ...grpc.CallOption) (*CreateRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateRelationshipResponse)
	err := c.cc.Invoke(ctx, Neo4JService_CreateRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) GetRelationship(ctx context.Context, in *GetRelationshipRequest, opts ...grpc.CallOption) (*GetRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRelationshipResponse)
	err := c.cc.Invoke(ctx, Neo4JService_GetRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) UpdateRelationship(ctx context.Context, in *UpdateRelationshipRequest, opts ...grpc.CallOption) (*UpdateRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRelationshipResponse)
	err := c.cc.Invoke(ctx, Neo4JService_UpdateRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) DeleteRelationship(ctx context.Context, in *DeleteRelationshipRequest, opts ...grpc.CallOption) (*DeleteRelationshipResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRelationshipResponse)
	err := c.cc.Invoke(ctx, Neo4JService_DeleteRelationship_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) FindRelationships(ctx context.Context, in *FindRelationshipsRequest, opts ...grpc.CallOption) (*FindRelationshipsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FindRelationshipsResponse)
	err := c.cc.Invoke(ctx, Neo4JService_FindRelationships_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) GetNeighbors(ctx context.Context, in *GetNeighborsRequest, opts ...grpc.CallOption) (*GetNeighborsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNeighborsResponse)
	err := c.cc.Invoke(ctx, Neo4JService_GetNeighbors_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) GetPath(ctx context.Context, in *GetPathRequest, opts ...grpc.CallOption) (*GetPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPathResponse)
	err := c.cc.Invoke(ctx, Neo4JService_GetPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) GetShortestPath(ctx context.Context, in *GetShortestPathRequest, opts ...grpc.CallOption) (*GetShortestPathResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetShortestPathResponse)
	err := c.cc.Invoke(ctx, Neo4JService_GetShortestPath_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) GetAllPaths(ctx context.Context, in *GetAllPathsRequest, opts ...grpc.CallOption) (*GetAllPathsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAllPathsResponse)
	err := c.cc.Invoke(ctx, Neo4JService_GetAllPaths_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) PageRank(ctx context.Context, in *PageRankRequest, opts ...grpc.CallOption) (*PageRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PageRankResponse)
	err := c.cc.Invoke(ctx, Neo4JService_PageRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) BetweennessCentrality(ctx context.Context, in *BetweennessCentralityRequest, opts ...grpc.CallOption) (*BetweennessCentralityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BetweennessCentralityResponse)
	err := c.cc.Invoke(ctx, Neo4JService_BetweennessCentrality_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) CommunityDetection(ctx context.Context, in *CommunityDetectionRequest, opts ...grpc.CallOption) (*CommunityDetectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommunityDetectionResponse)
	err := c.cc.Invoke(ctx, Neo4JService_CommunityDetection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) CreateIndex(ctx context.Context, in *CreateIndexRequest, opts ...grpc.CallOption) (*CreateIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateIndexResponse)
	err := c.cc.Invoke(ctx, Neo4JService_CreateIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) DropIndex(ctx context.Context, in *DropIndexRequest, opts ...grpc.CallOption) (*DropIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropIndexResponse)
	err := c.cc.Invoke(ctx, Neo4JService_DropIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) ListIndexes(ctx context.Context, in *ListIndexesRequest, opts ...grpc.CallOption) (*ListIndexesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListIndexesResponse)
	err := c.cc.Invoke(ctx, Neo4JService_ListIndexes_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) CreateConstraint(ctx context.Context, in *CreateConstraintRequest, opts ...grpc.CallOption) (*CreateConstraintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateConstraintResponse)
	err := c.cc.Invoke(ctx, Neo4JService_CreateConstraint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) DropConstraint(ctx context.Context, in *DropConstraintRequest, opts ...grpc.CallOption) (*DropConstraintResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropConstraintResponse)
	err := c.cc.Invoke(ctx, Neo4JService_DropConstraint_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) ListConstraints(ctx context.Context, in *ListConstraintsRequest, opts ...grpc.CallOption) (*ListConstraintsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListConstraintsResponse)
	err := c.cc.Invoke(ctx, Neo4JService_ListConstraints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) BeginTransaction(ctx context.Context, in *BeginTransactionRequest, opts ...grpc.CallOption) (*BeginTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BeginTransactionResponse)
	err := c.cc.Invoke(ctx, Neo4JService_BeginTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) CommitTransaction(ctx context.Context, in *CommitTransactionRequest, opts ...grpc.CallOption) (*CommitTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CommitTransactionResponse)
	err := c.cc.Invoke(ctx, Neo4JService_CommitTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) RollbackTransaction(ctx context.Context, in *RollbackTransactionRequest, opts ...grpc.CallOption) (*RollbackTransactionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RollbackTransactionResponse)
	err := c.cc.Invoke(ctx, Neo4JService_RollbackTransaction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) GetDatabaseInfo(ctx context.Context, in *GetDatabaseInfoRequest, opts ...grpc.CallOption) (*GetDatabaseInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatabaseInfoResponse)
	err := c.cc.Invoke(ctx, Neo4JService_GetDatabaseInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabasesResponse)
	err := c.cc.Invoke(ctx, Neo4JService_ListDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsResponse)
	err := c.cc.Invoke(ctx, Neo4JService_GetStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *neo4JServiceClient) HealthCheck(ctx context.Context, in *Neo4JHealthCheckRequest, opts ...grpc.CallOption) (*Neo4JHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Neo4JHealthCheckResponse)
	err := c.cc.Invoke(ctx, Neo4JService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Neo4JServiceServer is the server API for Neo4JService service.
// All implementations must embed UnimplementedNeo4JServiceServer
// for forward compatibility.
type Neo4JServiceServer interface {
	// RunCypher - Execute Cypher query
	RunCypher(context.Context, *RunCypherRequest) (*RunCypherResponse, error)
	// RunCypherRead - Execute read-only Cypher query
	RunCypherRead(context.Context, *RunCypherReadRequest) (*RunCypherReadResponse, error)
	// RunCypherWrite - Execute write Cypher query
	RunCypherWrite(context.Context, *RunCypherWriteRequest) (*RunCypherWriteResponse, error)
	// RunCypherBatch - Execute multiple Cypher queries in batch
	RunCypherBatch(context.Context, *RunCypherBatchRequest) (*RunCypherBatchResponse, error)
	// CreateNode - Create a new node
	CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error)
	// GetNode - Retrieve node by ID
	GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error)
	// UpdateNode - Update node properties
	UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error)
	// DeleteNode - Delete node
	DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error)
	// MergeNode - Create or update node (MERGE)
	MergeNode(context.Context, *MergeNodeRequest) (*MergeNodeResponse, error)
	// FindNodes - Find nodes by label and properties
	FindNodes(context.Context, *FindNodesRequest) (*FindNodesResponse, error)
	// CreateRelationship - Create relationship between nodes
	CreateRelationship(context.Context, *CreateRelationshipRequest) (*CreateRelationshipResponse, error)
	// GetRelationship - Retrieve relationship by ID
	GetRelationship(context.Context, *GetRelationshipRequest) (*GetRelationshipResponse, error)
	// UpdateRelationship - Update relationship properties
	UpdateRelationship(context.Context, *UpdateRelationshipRequest) (*UpdateRelationshipResponse, error)
	// DeleteRelationship - Delete relationship
	DeleteRelationship(context.Context, *DeleteRelationshipRequest) (*DeleteRelationshipResponse, error)
	// FindRelationships - Find relationships by type and properties
	FindRelationships(context.Context, *FindRelationshipsRequest) (*FindRelationshipsResponse, error)
	// GetNeighbors - Get neighboring nodes
	GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error)
	// GetPath - Find path between two nodes
	GetPath(context.Context, *GetPathRequest) (*GetPathResponse, error)
	// GetShortestPath - Find shortest path between nodes
	GetShortestPath(context.Context, *GetShortestPathRequest) (*GetShortestPathResponse, error)
	// GetAllPaths - Find all paths between nodes
	GetAllPaths(context.Context, *GetAllPathsRequest) (*GetAllPathsResponse, error)
	// PageRank - Run PageRank algorithm
	PageRank(context.Context, *PageRankRequest) (*PageRankResponse, error)
	// BetweennessCentrality - Calculate betweenness centrality
	BetweennessCentrality(context.Context, *BetweennessCentralityRequest) (*BetweennessCentralityResponse, error)
	// CommunityDetection - Detect communities in graph
	CommunityDetection(context.Context, *CommunityDetectionRequest) (*CommunityDetectionResponse, error)
	// CreateIndex - Create index on label/property
	CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error)
	// DropIndex - Drop an index
	DropIndex(context.Context, *DropIndexRequest) (*DropIndexResponse, error)
	// ListIndexes - List all indexes
	ListIndexes(context.Context, *ListIndexesRequest) (*ListIndexesResponse, error)
	// CreateConstraint - Create uniqueness or existence constraint
	CreateConstraint(context.Context, *CreateConstraintRequest) (*CreateConstraintResponse, error)
	// DropConstraint - Drop a constraint
	DropConstraint(context.Context, *DropConstraintRequest) (*DropConstraintResponse, error)
	// ListConstraints - List all constraints
	ListConstraints(context.Context, *ListConstraintsRequest) (*ListConstraintsResponse, error)
	// BeginTransaction - Start a new transaction
	BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error)
	// CommitTransaction - Commit transaction
	CommitTransaction(context.Context, *CommitTransactionRequest) (*CommitTransactionResponse, error)
	// RollbackTransaction - Rollback transaction
	RollbackTransaction(context.Context, *RollbackTransactionRequest) (*RollbackTransactionResponse, error)
	// GetDatabaseInfo - Get database information
	GetDatabaseInfo(context.Context, *GetDatabaseInfoRequest) (*GetDatabaseInfoResponse, error)
	// ListDatabases - List all databases
	ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)
	// GetStatistics - Get database statistics
	GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error)
	// HealthCheck - Service health check
	HealthCheck(context.Context, *Neo4JHealthCheckRequest) (*Neo4JHealthCheckResponse, error)
	mustEmbedUnimplementedNeo4JServiceServer()
}

// UnimplementedNeo4JServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNeo4JServiceServer struct{}

func (UnimplementedNeo4JServiceServer) RunCypher(context.Context, *RunCypherRequest) (*RunCypherResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCypher not implemented")
}
func (UnimplementedNeo4JServiceServer) RunCypherRead(context.Context, *RunCypherReadRequest) (*RunCypherReadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCypherRead not implemented")
}
func (UnimplementedNeo4JServiceServer) RunCypherWrite(context.Context, *RunCypherWriteRequest) (*RunCypherWriteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCypherWrite not implemented")
}
func (UnimplementedNeo4JServiceServer) RunCypherBatch(context.Context, *RunCypherBatchRequest) (*RunCypherBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RunCypherBatch not implemented")
}
func (UnimplementedNeo4JServiceServer) CreateNode(context.Context, *CreateNodeRequest) (*CreateNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateNode not implemented")
}
func (UnimplementedNeo4JServiceServer) GetNode(context.Context, *GetNodeRequest) (*GetNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNode not implemented")
}
func (UnimplementedNeo4JServiceServer) UpdateNode(context.Context, *UpdateNodeRequest) (*UpdateNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateNode not implemented")
}
func (UnimplementedNeo4JServiceServer) DeleteNode(context.Context, *DeleteNodeRequest) (*DeleteNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteNode not implemented")
}
func (UnimplementedNeo4JServiceServer) MergeNode(context.Context, *MergeNodeRequest) (*MergeNodeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MergeNode not implemented")
}
func (UnimplementedNeo4JServiceServer) FindNodes(context.Context, *FindNodesRequest) (*FindNodesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindNodes not implemented")
}
func (UnimplementedNeo4JServiceServer) CreateRelationship(context.Context, *CreateRelationshipRequest) (*CreateRelationshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateRelationship not implemented")
}
func (UnimplementedNeo4JServiceServer) GetRelationship(context.Context, *GetRelationshipRequest) (*GetRelationshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetRelationship not implemented")
}
func (UnimplementedNeo4JServiceServer) UpdateRelationship(context.Context, *UpdateRelationshipRequest) (*UpdateRelationshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateRelationship not implemented")
}
func (UnimplementedNeo4JServiceServer) DeleteRelationship(context.Context, *DeleteRelationshipRequest) (*DeleteRelationshipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteRelationship not implemented")
}
func (UnimplementedNeo4JServiceServer) FindRelationships(context.Context, *FindRelationshipsRequest) (*FindRelationshipsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindRelationships not implemented")
}
func (UnimplementedNeo4JServiceServer) GetNeighbors(context.Context, *GetNeighborsRequest) (*GetNeighborsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetNeighbors not implemented")
}
func (UnimplementedNeo4JServiceServer) GetPath(context.Context, *GetPathRequest) (*GetPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPath not implemented")
}
func (UnimplementedNeo4JServiceServer) GetShortestPath(context.Context, *GetShortestPathRequest) (*GetShortestPathResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetShortestPath not implemented")
}
func (UnimplementedNeo4JServiceServer) GetAllPaths(context.Context, *GetAllPathsRequest) (*GetAllPathsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAllPaths not implemented")
}
func (UnimplementedNeo4JServiceServer) PageRank(context.Context, *PageRankRequest) (*PageRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PageRank not implemented")
}
func (UnimplementedNeo4JServiceServer) BetweennessCentrality(context.Context, *BetweennessCentralityRequest) (*BetweennessCentralityResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BetweennessCentrality not implemented")
}
func (UnimplementedNeo4JServiceServer) CommunityDetection(context.Context, *CommunityDetectionRequest) (*CommunityDetectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommunityDetection not implemented")
}
func (UnimplementedNeo4JServiceServer) CreateIndex(context.Context, *CreateIndexRequest) (*CreateIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateIndex not implemented")
}
func (UnimplementedNeo4JServiceServer) DropIndex(context.Context, *DropIndexRequest) (*DropIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropIndex not implemented")
}
func (UnimplementedNeo4JServiceServer) ListIndexes(context.Context, *ListIndexesRequest) (*ListIndexesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListIndexes not implemented")
}
func (UnimplementedNeo4JServiceServer) CreateConstraint(context.Context, *CreateConstraintRequest) (*CreateConstraintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateConstraint not implemented")
}
func (UnimplementedNeo4JServiceServer) DropConstraint(context.Context, *DropConstraintRequest) (*DropConstraintResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropConstraint not implemented")
}
func (UnimplementedNeo4JServiceServer) ListConstraints(context.Context, *ListConstraintsRequest) (*ListConstraintsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListConstraints not implemented")
}
func (UnimplementedNeo4JServiceServer) BeginTransaction(context.Context, *BeginTransactionRequest) (*BeginTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BeginTransaction not implemented")
}
func (UnimplementedNeo4JServiceServer) CommitTransaction(context.Context, *CommitTransactionRequest) (*CommitTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CommitTransaction not implemented")
}
func (UnimplementedNeo4JServiceServer) RollbackTransaction(context.Context, *RollbackTransactionRequest) (*RollbackTransactionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RollbackTransaction not implemented")
}
func (UnimplementedNeo4JServiceServer) GetDatabaseInfo(context.Context, *GetDatabaseInfoRequest) (*GetDatabaseInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabaseInfo not implemented")
}
func (UnimplementedNeo4JServiceServer) ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDatabases not implemented")
}
func (UnimplementedNeo4JServiceServer) GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistics not implemented")
}
func (UnimplementedNeo4JServiceServer) HealthCheck(context.Context, *Neo4JHealthCheckRequest) (*Neo4JHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedNeo4JServiceServer) mustEmbedUnimplementedNeo4JServiceServer() {}
func (UnimplementedNeo4JServiceServer) testEmbeddedByValue()                      {}

// UnsafeNeo4JServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to Neo4JServiceServer will
// result in compilation errors.
type UnsafeNeo4JServiceServer interface {
	mustEmbedUnimplementedNeo4JServiceServer()
}

func RegisterNeo4JServiceServer(s grpc.ServiceRegistrar, srv Neo4JServiceServer) {
	// If the following call pancis, it indicates UnimplementedNeo4JServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Neo4JService_ServiceDesc, srv)
}

func _Neo4JService_RunCypher_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCypherRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).RunCypher(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_RunCypher_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).RunCypher(ctx, req.(*RunCypherRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_RunCypherRead_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCypherReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).RunCypherRead(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_RunCypherRead_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).RunCypherRead(ctx, req.(*RunCypherReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_RunCypherWrite_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCypherWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).RunCypherWrite(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_RunCypherWrite_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).RunCypherWrite(ctx, req.(*RunCypherWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_RunCypherBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RunCypherBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).RunCypherBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_RunCypherBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).RunCypherBatch(ctx, req.(*RunCypherBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_CreateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).CreateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_CreateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).CreateNode(ctx, req.(*CreateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_GetNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).GetNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_GetNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).GetNode(ctx, req.(*GetNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_UpdateNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).UpdateNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_UpdateNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).UpdateNode(ctx, req.(*UpdateNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_DeleteNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).DeleteNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_DeleteNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).DeleteNode(ctx, req.(*DeleteNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_MergeNode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MergeNodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).MergeNode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_MergeNode_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).MergeNode(ctx, req.(*MergeNodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_FindNodes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindNodesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).FindNodes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_FindNodes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).FindNodes(ctx, req.(*FindNodesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_CreateRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).CreateRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_CreateRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).CreateRelationship(ctx, req.(*CreateRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_GetRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).GetRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_GetRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).GetRelationship(ctx, req.(*GetRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_UpdateRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).UpdateRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_UpdateRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).UpdateRelationship(ctx, req.(*UpdateRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_DeleteRelationship_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRelationshipRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).DeleteRelationship(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_DeleteRelationship_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).DeleteRelationship(ctx, req.(*DeleteRelationshipRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_FindRelationships_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindRelationshipsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).FindRelationships(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_FindRelationships_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).FindRelationships(ctx, req.(*FindRelationshipsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_GetNeighbors_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNeighborsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).GetNeighbors(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_GetNeighbors_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).GetNeighbors(ctx, req.(*GetNeighborsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_GetPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).GetPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_GetPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).GetPath(ctx, req.(*GetPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_GetShortestPath_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetShortestPathRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).GetShortestPath(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_GetShortestPath_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).GetShortestPath(ctx, req.(*GetShortestPathRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_GetAllPaths_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAllPathsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).GetAllPaths(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_GetAllPaths_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).GetAllPaths(ctx, req.(*GetAllPathsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_PageRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PageRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).PageRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_PageRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).PageRank(ctx, req.(*PageRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_BetweennessCentrality_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BetweennessCentralityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).BetweennessCentrality(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_BetweennessCentrality_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).BetweennessCentrality(ctx, req.(*BetweennessCentralityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_CommunityDetection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommunityDetectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).CommunityDetection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_CommunityDetection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).CommunityDetection(ctx, req.(*CommunityDetectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_CreateIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).CreateIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_CreateIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).CreateIndex(ctx, req.(*CreateIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_DropIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).DropIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_DropIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).DropIndex(ctx, req.(*DropIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_ListIndexes_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListIndexesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).ListIndexes(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_ListIndexes_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).ListIndexes(ctx, req.(*ListIndexesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_CreateConstraint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateConstraintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).CreateConstraint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_CreateConstraint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).CreateConstraint(ctx, req.(*CreateConstraintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_DropConstraint_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropConstraintRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).DropConstraint(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_DropConstraint_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).DropConstraint(ctx, req.(*DropConstraintRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_ListConstraints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListConstraintsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).ListConstraints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_ListConstraints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).ListConstraints(ctx, req.(*ListConstraintsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_BeginTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BeginTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).BeginTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_BeginTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).BeginTransaction(ctx, req.(*BeginTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_CommitTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CommitTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).CommitTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_CommitTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).CommitTransaction(ctx, req.(*CommitTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_RollbackTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RollbackTransactionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).RollbackTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_RollbackTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).RollbackTransaction(ctx, req.(*RollbackTransactionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_GetDatabaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).GetDatabaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_GetDatabaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).GetDatabaseInfo(ctx, req.(*GetDatabaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_ListDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).ListDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_ListDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).ListDatabases(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_GetStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).GetStatistics(ctx, req.(*GetStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Neo4JService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Neo4JHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(Neo4JServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Neo4JService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(Neo4JServiceServer).HealthCheck(ctx, req.(*Neo4JHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Neo4JService_ServiceDesc is the grpc.ServiceDesc for Neo4JService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Neo4JService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "isa.neo4j.Neo4jService",
	HandlerType: (*Neo4JServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RunCypher",
			Handler:    _Neo4JService_RunCypher_Handler,
		},
		{
			MethodName: "RunCypherRead",
			Handler:    _Neo4JService_RunCypherRead_Handler,
		},
		{
			MethodName: "RunCypherWrite",
			Handler:    _Neo4JService_RunCypherWrite_Handler,
		},
		{
			MethodName: "RunCypherBatch",
			Handler:    _Neo4JService_RunCypherBatch_Handler,
		},
		{
			MethodName: "CreateNode",
			Handler:    _Neo4JService_CreateNode_Handler,
		},
		{
			MethodName: "GetNode",
			Handler:    _Neo4JService_GetNode_Handler,
		},
		{
			MethodName: "UpdateNode",
			Handler:    _Neo4JService_UpdateNode_Handler,
		},
		{
			MethodName: "DeleteNode",
			Handler:    _Neo4JService_DeleteNode_Handler,
		},
		{
			MethodName: "MergeNode",
			Handler:    _Neo4JService_MergeNode_Handler,
		},
		{
			MethodName: "FindNodes",
			Handler:    _Neo4JService_FindNodes_Handler,
		},
		{
			MethodName: "CreateRelationship",
			Handler:    _Neo4JService_CreateRelationship_Handler,
		},
		{
			MethodName: "GetRelationship",
			Handler:    _Neo4JService_GetRelationship_Handler,
		},
		{
			MethodName: "UpdateRelationship",
			Handler:    _Neo4JService_UpdateRelationship_Handler,
		},
		{
			MethodName: "DeleteRelationship",
			Handler:    _Neo4JService_DeleteRelationship_Handler,
		},
		{
			MethodName: "FindRelationships",
			Handler:    _Neo4JService_FindRelationships_Handler,
		},
		{
			MethodName: "GetNeighbors",
			Handler:    _Neo4JService_GetNeighbors_Handler,
		},
		{
			MethodName: "GetPath",
			Handler:    _Neo4JService_GetPath_Handler,
		},
		{
			MethodName: "GetShortestPath",
			Handler:    _Neo4JService_GetShortestPath_Handler,
		},
		{
			MethodName: "GetAllPaths",
			Handler:    _Neo4JService_GetAllPaths_Handler,
		},
		{
			MethodName: "PageRank",
			Handler:    _Neo4JService_PageRank_Handler,
		},
		{
			MethodName: "BetweennessCentrality",
			Handler:    _Neo4JService_BetweennessCentrality_Handler,
		},
		{
			MethodName: "CommunityDetection",
			Handler:    _Neo4JService_CommunityDetection_Handler,
		},
		{
			MethodName: "CreateIndex",
			Handler:    _Neo4JService_CreateIndex_Handler,
		},
		{
			MethodName: "DropIndex",
			Handler:    _Neo4JService_DropIndex_Handler,
		},
		{
			MethodName: "ListIndexes",
			Handler:    _Neo4JService_ListIndexes_Handler,
		},
		{
			MethodName: "CreateConstraint",
			Handler:    _Neo4JService_CreateConstraint_Handler,
		},
		{
			MethodName: "DropConstraint",
			Handler:    _Neo4JService_DropConstraint_Handler,
		},
		{
			MethodName: "ListConstraints",
			Handler:    _Neo4JService_ListConstraints_Handler,
		},
		{
			MethodName: "BeginTransaction",
			Handler:    _Neo4JService_BeginTransaction_Handler,
		},
		{
			MethodName: "CommitTransaction",
			Handler:    _Neo4JService_CommitTransaction_Handler,
		},
		{
			MethodName: "RollbackTransaction",
			Handler:    _Neo4JService_RollbackTransaction_Handler,
		},
		{
			MethodName: "GetDatabaseInfo",
			Handler:    _Neo4JService_GetDatabaseInfo_Handler,
		},
		{
			MethodName: "ListDatabases",
			Handler:    _Neo4JService_ListDatabases_Handler,
		},
		{
			MethodName: "GetStatistics",
			Handler:    _Neo4JService_GetStatistics_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _Neo4JService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "neo4j_service.proto",
}
