{{- if and .Values.auth.enabled (not .Values.auth.existingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "redis.name" . }}-auth
  labels:
    {{- include "redis.labels" . | nindent 4 }}
type: Opaque
stringData:
  {{ .Values.auth.existingSecretPasswordKey }}: {{ required "redis: auth.enabled but auth.password is empty and no existingSecret set" .Values.auth.password | quote }}
{{- end }}
