# Docker Compose configuration for isA_Cloud Edge Layer + Gateway (Staging)
# This includes OpenResty edge layer and Go application gateway
#
# Prerequisites: Run infrastructure.staging.yml first to create the network and base services
# Usage: docker-compose -f gateway.staging.yml up -d

version: '3.8'

networks:
  staging-network:
    name: staging_staging-network
    external: true

services:
  # ==============================================
  # EDGE LAYER - OpenResty (Nginx + Lua)
  # ==============================================
  openresty:
    build:
      context: ../../..
      dockerfile: deployments/dockerfiles/Staging/Dockerfile.openresty.staging
    image: isa-cloud/openresty:staging
    container_name: isa-cloud-openresty-staging
    restart: unless-stopped
    ports:
      - "80:80"      # HTTP
      - "443:443"    # HTTPS
    environment:
      - REDIS_HOST=staging-redis
      - REDIS_PORT=6379
      - UPSTREAM_HOST=gateway
      - UPSTREAM_PORT=8000
      - TZ=UTC
    volumes:
      # Configuration files (for live updates without rebuild)
      - ../../../deployments/nginx/conf/nginx.conf:/usr/local/openresty/nginx/conf/nginx.conf:ro
      - ../../../deployments/nginx/conf/upstream.conf:/etc/nginx/conf.d/upstream.conf:ro
      - ../../../deployments/nginx/conf/cache.conf:/etc/nginx/conf.d/cache.conf:ro
      - ../../../deployments/nginx/conf/security.conf:/etc/nginx/conf.d/security.conf:ro
      - ../../../deployments/nginx/sites-available:/etc/nginx/sites-available:ro
      - ../../../deployments/nginx/lua:/etc/nginx/lua:ro

      # SSL certificates (mount from host or use Let's Encrypt)
      - ./ssl:/etc/nginx/ssl:ro

      # Static files (if any)
      - ./static:/var/www/static:ro

      # Logs
      - ./logs/openresty:/var/log/nginx

      # Cache directory
      - openresty-cache:/var/cache/nginx
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 10s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # ==============================================
  # APPLICATION LAYER - Go Gateway
  # ==============================================
  gateway:
    build:
      context: ../../..
      dockerfile: deployments/dockerfiles/Dockerfile.gateway
    image: isa-cloud/gateway:staging
    container_name: isa-cloud-gateway-staging
    restart: unless-stopped
    expose:
      - "8000"  # HTTP (internal only - accessed via OpenResty)
      - "8001"  # gRPC (internal only)
    environment:
      # Environment selection (loads configs/staging/gateway.yaml)
      - ENVIRONMENT=staging

      # Application settings
      - APP_ENV=staging
      - APP_NAME=isA_Cloud Gateway Staging
      - APP_VERSION=1.0.0
      - DEBUG=true

      # Server configuration
      - SERVER_HOST=0.0.0.0
      - SERVER_HTTP_PORT=8000
      - SERVER_GRPC_PORT=8001

      # Database (Supabase)
      - DATABASE_HOST=db.ugloxikfljpuvakwiadf.supabase.co
      - DATABASE_PORT=5432
      - DATABASE_NAME=postgres
      - DATABASE_USER=postgres
      - DATABASE_PASSWORD=0npfjCaFaXXnm289
      - DATABASE_SSL_MODE=require

      # Redis
      - REDIS_HOST=staging-redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
      - REDIS_DATABASE=0

      # Consul
      - CONSUL_ENABLED=true
      - CONSUL_HOST=staging-consul
      - CONSUL_PORT=8500

      # Security
      - JWT_SECRET=staging-secret-key-change-in-production
      - JWT_EXPIRATION=24h
      - JWT_ISSUER=isa-cloud-gateway-staging

      # CORS
      - CORS_ENABLED=true
      - CORS_ALLOW_ORIGINS=*
      - CORS_ALLOW_CREDENTIALS=true

      # Rate Limiting (application level)
      - RATE_LIMIT_ENABLED=true
      - RATE_LIMIT_TYPE=per_user
      - RATE_LIMIT_RPS=10
      - RATE_LIMIT_BURST=20

      # MQTT
      - MQTT_ENABLED=true
      - MQTT_BROKER_URL=tcp://staging-mosquitto:1883
      - MQTT_CLIENT_ID=isa_cloud_gateway_staging

      # Timezone
      - TZ=UTC

    volumes:
      # Configuration
      - ../../../deployments/configs/staging/gateway.yaml:/app/config/gateway.yaml:ro

      # Logs
      - ./logs/gateway:/app/logs

    networks:
      - staging-network

    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8000/health"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 20s

    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  openresty-cache:
    driver: local
