# ============================================
# isA Platform - Infrastructure Services (Staging)
# ============================================
# Core infrastructure services for staging environment
# Uses staging-isa-*:amd64 Docker images

services:
  # ============== Service Discovery ==============
  consul:
    image: staging-isa-consul:amd64
    container_name: staging-consul
    ports:
      - "8500:8500"
    volumes:
      - consul-data:/consul/data
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8500/v1/status/leader"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Consul Agent - Shared agent for all application services
  # Implements HashiCorp best practices for agent-based service registration
  consul-agent-shared:
    image: hashicorp/consul:latest
    container_name: consul-agent-shared
    hostname: consul-agent-shared
    command: >
      agent
      -retry-join=staging-consul
      -bind=0.0.0.0
      -client=0.0.0.0
      -datacenter=staging
      -data-dir=/consul/data
      -config-file=/consul/config/agent-config.json
      -config-dir=/consul/config/services
      -enable-local-script-checks=true
    volumes:
      - ../../configs/staging/consul/agent:/consul/config
      - consul-agent-shared-data:/consul/data
    networks:
      - staging-network
    depends_on:
      - consul
    healthcheck:
      test: ["CMD", "consul", "members"]
      interval: 10s
      timeout: 3s
      retries: 3
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    restart: unless-stopped

  # ============== Cache ==============
  redis:
    image: staging-isa-redis:amd64
    container_name: staging-redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_PASSWORD=staging_redis_2024
    volumes:
      - redis-data:/data/redis
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ============== Object Storage ==============
  minio:
    image: staging-isa-minio:amd64
    container_name: staging-minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    command: ["minio", "server", "/data", "--console-address", ":9001"]
    volumes:
      - minio-data:/data
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  # ============== Message Streaming ==============
  nats:
    image: staging-isa-nats:amd64
    container_name: staging-nats
    ports:
      - "4222:4222"
      - "4223:4223"
      - "6222:6222"
    environment:
      - NATS_PORT=4222
      - NATS_HTTP_PORT=4223
      - CONSUL_ENABLED=false
      - CONSUL_HOST=consul
      - SERVICE_NAME=nats-service
    volumes:
      - nats-data:/data
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4223/healthz"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ============== MQTT Broker ==============
  mosquitto:
    image: staging-isa-mosquitto:amd64
    container_name: staging-mosquitto
    ports:
      - "1883:1883"
      - "9003:9001"
    environment:
      - MQTT_PORT=1883
      - MQTT_WS_PORT=9001
      - CONSUL_ENABLED=false
      - CONSUL_HOST=consul
      - SERVICE_NAME=mqtt-service
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # ============== Database (PostgreSQL) ==============
  postgres:
    image: staging-isa-postgres:amd64
    container_name: staging-postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=staging_postgres_2024
      - POSTGRES_DB=isa_platform
      - POSTGRES_PORT=5432
      - CONSUL_ENABLED=false
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SERVICE_NAME=postgres-db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - staging-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      - consul

  # ============== Vector Database (Qdrant) ==============
  qdrant:
    image: staging-isa-qdrant:amd64
    container_name: staging-qdrant
    ports:
      - "6333:6333"  # HTTP API
      - "6334:6334"  # gRPC API
    environment:
      - QDRANT_HTTP_PORT=6333
      - QDRANT_GRPC_PORT=6334
      - CONSUL_ENABLED=false
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SERVICE_NAME=qdrant-db
    volumes:
      - qdrant-data:/qdrant/storage
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:6333/"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      - consul

  # ============== Graph Database (Neo4j) ==============
  neo4j:
    image: staging-isa-neo4j:amd64
    container_name: staging-neo4j
    ports:
      - "7474:7474"  # HTTP
      - "7687:7687"  # Bolt
    environment:
      - NEO4J_AUTH=neo4j/staging_neo4j_2024
      - NEO4J_server_http_listen__address=0.0.0.0:7474
      - NEO4J_server_bolt_listen__address=0.0.0.0:7687
      - NEO4J_server_config_strict__validation_enabled=false
      - HTTP_PORT=7474
      - BOLT_PORT=7687
      - CONSUL_ENABLED=false
      - CONSUL_HOST=consul
      - CONSUL_PORT=8500
      - SERVICE_NAME=neo4j-db
    volumes:
      - neo4j-data:/data
      - neo4j-logs:/logs
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7474/"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    depends_on:
      - consul

  # ============== Log Aggregation ==============
  loki:
    image: staging-isa-loki:amd64
    container_name: staging-loki
    ports:
      - "3100:3100"
    volumes:
      - loki-data:/loki
    networks:
      - staging-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3100/ready"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # ============== Monitoring Dashboard ==============
  grafana:
    image: staging-isa-grafana:amd64
    container_name: staging-grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=staging_admin_2024
      - GF_USERS_ALLOW_SIGN_UP=false
      - GF_INSTALL_PLUGINS=grafana-piechart-panel,grafana-worldmap-panel
      - GF_PATHS_DATA=/var/lib/grafana
      - GF_PATHS_LOGS=/var/log/grafana
      - GF_PATHS_PLUGINS=/var/lib/grafana/plugins
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    volumes:
      - grafana-data:/var/lib/grafana
      - grafana-logs:/var/log/grafana
    networks:
      - staging-network
    depends_on:
      - loki
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

networks:
  staging-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

volumes:
  consul-data:
    driver: local
  consul-agent-shared-data:
    driver: local
  redis-data:
    driver: local
  minio-data:
    driver: local
  nats-data:
    driver: local
  mosquitto-data:
    driver: local
  mosquitto-logs:
    driver: local
  postgres-data:
    driver: local
  qdrant-data:
    driver: local
  neo4j-data:
    driver: local
  neo4j-logs:
    driver: local
  loki-data:
    driver: local
  grafana-data:
    driver: local
  grafana-logs:
    driver: local