FROM grafana/grafana:10.2.3

# Copy Grafana provisioning configurations for staging
COPY configs/staging/grafana/provisioning /etc/grafana/provisioning
COPY configs/staging/grafana/dashboards /var/lib/grafana/dashboards

# Expose Grafana port
EXPOSE 3000

# Grafana runs as user grafana
USER grafana
