apiVersion: v1
data:
  CONSUL_ENABLED: 'true'
  CONSUL_HOST: consul-server.sn-cloud-production.svc.cluster.local
  CONSUL_PORT: '8500'
  DB_POOL_BASE: '2'
  DB_POOL_GROWTH: '1'
  DEBUG: 'false'
  ENV: production
  LOG_LEVEL: INFO
  LOKI_ENABLED: 'false'
  MINIO_HOST: minio.sn-cloud-production.svc.cluster.local
  MINIO_PORT: '9000'
  MINIO_SECURE: 'false'
  NATS_HOST: nats.sn-cloud-production.svc.cluster.local
  NATS_PORT: '4222'
  NATS_URL: nats://nats.sn-cloud-production.svc.cluster.local:4222
  NEO4J_AVAILABLE: 'false'
  POD_REPLICA_COUNT: '1'
  POSTGRES_DB: isa_platform
  POSTGRES_HOST: pgbouncer.sn-cloud-production.svc.cluster.local
  POSTGRES_PORT: '6432'
  POSTGRES_USER: postgres
  PYTHONPATH: /app
  PYTHONUNBUFFERED: '1'
  QDRANT_HOST: qdrant.sn-cloud-production.svc.cluster.local
  QDRANT_PORT: '6333'
  REDIS_DB: '0'
  REDIS_HOST: redis-cluster.sn-cloud-production.svc.cluster.local
  REDIS_PORT: '6379'
kind: ConfigMap
metadata:
  name: isa-user-env
  namespace: sn-cloud-production

