// minio_service.proto - MinIO 对象存储服务 gRPC 接口
// 提供统一的对象存储访问接口，支持多租户和用户隔离

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: minio_service.proto

package minio

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	MinIOService_CreateBucket_FullMethodName            = "/isa.minio.MinIOService/CreateBucket"
	MinIOService_ListBuckets_FullMethodName             = "/isa.minio.MinIOService/ListBuckets"
	MinIOService_DeleteBucket_FullMethodName            = "/isa.minio.MinIOService/DeleteBucket"
	MinIOService_GetBucketInfo_FullMethodName           = "/isa.minio.MinIOService/GetBucketInfo"
	MinIOService_SetBucketPolicy_FullMethodName         = "/isa.minio.MinIOService/SetBucketPolicy"
	MinIOService_GetBucketPolicy_FullMethodName         = "/isa.minio.MinIOService/GetBucketPolicy"
	MinIOService_SetBucketTags_FullMethodName           = "/isa.minio.MinIOService/SetBucketTags"
	MinIOService_GetBucketTags_FullMethodName           = "/isa.minio.MinIOService/GetBucketTags"
	MinIOService_DeleteBucketTags_FullMethodName        = "/isa.minio.MinIOService/DeleteBucketTags"
	MinIOService_SetBucketVersioning_FullMethodName     = "/isa.minio.MinIOService/SetBucketVersioning"
	MinIOService_GetBucketVersioning_FullMethodName     = "/isa.minio.MinIOService/GetBucketVersioning"
	MinIOService_SetBucketLifecycle_FullMethodName      = "/isa.minio.MinIOService/SetBucketLifecycle"
	MinIOService_GetBucketLifecycle_FullMethodName      = "/isa.minio.MinIOService/GetBucketLifecycle"
	MinIOService_DeleteBucketLifecycle_FullMethodName   = "/isa.minio.MinIOService/DeleteBucketLifecycle"
	MinIOService_PutObject_FullMethodName               = "/isa.minio.MinIOService/PutObject"
	MinIOService_GetObject_FullMethodName               = "/isa.minio.MinIOService/GetObject"
	MinIOService_DeleteObject_FullMethodName            = "/isa.minio.MinIOService/DeleteObject"
	MinIOService_DeleteObjects_FullMethodName           = "/isa.minio.MinIOService/DeleteObjects"
	MinIOService_ListObjects_FullMethodName             = "/isa.minio.MinIOService/ListObjects"
	MinIOService_CopyObject_FullMethodName              = "/isa.minio.MinIOService/CopyObject"
	MinIOService_StatObject_FullMethodName              = "/isa.minio.MinIOService/StatObject"
	MinIOService_SetObjectTags_FullMethodName           = "/isa.minio.MinIOService/SetObjectTags"
	MinIOService_GetObjectTags_FullMethodName           = "/isa.minio.MinIOService/GetObjectTags"
	MinIOService_DeleteObjectTags_FullMethodName        = "/isa.minio.MinIOService/DeleteObjectTags"
	MinIOService_GetPresignedURL_FullMethodName         = "/isa.minio.MinIOService/GetPresignedURL"
	MinIOService_GetPresignedPutURL_FullMethodName      = "/isa.minio.MinIOService/GetPresignedPutURL"
	MinIOService_InitiateMultipartUpload_FullMethodName = "/isa.minio.MinIOService/InitiateMultipartUpload"
	MinIOService_UploadPart_FullMethodName              = "/isa.minio.MinIOService/UploadPart"
	MinIOService_CompleteMultipartUpload_FullMethodName = "/isa.minio.MinIOService/CompleteMultipartUpload"
	MinIOService_AbortMultipartUpload_FullMethodName    = "/isa.minio.MinIOService/AbortMultipartUpload"
	MinIOService_HealthCheck_FullMethodName             = "/isa.minio.MinIOService/HealthCheck"
)

// MinIOServiceClient is the client API for MinIOService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type MinIOServiceClient interface {
	// ========== 桶管理 ==========
	CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error)
	ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error)
	DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error)
	GetBucketInfo(ctx context.Context, in *GetBucketInfoRequest, opts ...grpc.CallOption) (*GetBucketInfoResponse, error)
	SetBucketPolicy(ctx context.Context, in *SetBucketPolicyRequest, opts ...grpc.CallOption) (*SetBucketPolicyResponse, error)
	GetBucketPolicy(ctx context.Context, in *GetBucketPolicyRequest, opts ...grpc.CallOption) (*GetBucketPolicyResponse, error)
	SetBucketTags(ctx context.Context, in *SetBucketTagsRequest, opts ...grpc.CallOption) (*SetBucketTagsResponse, error)
	GetBucketTags(ctx context.Context, in *GetBucketTagsRequest, opts ...grpc.CallOption) (*GetBucketTagsResponse, error)
	DeleteBucketTags(ctx context.Context, in *DeleteBucketTagsRequest, opts ...grpc.CallOption) (*DeleteBucketTagsResponse, error)
	SetBucketVersioning(ctx context.Context, in *SetBucketVersioningRequest, opts ...grpc.CallOption) (*SetBucketVersioningResponse, error)
	GetBucketVersioning(ctx context.Context, in *GetBucketVersioningRequest, opts ...grpc.CallOption) (*GetBucketVersioningResponse, error)
	SetBucketLifecycle(ctx context.Context, in *SetBucketLifecycleRequest, opts ...grpc.CallOption) (*SetBucketLifecycleResponse, error)
	GetBucketLifecycle(ctx context.Context, in *GetBucketLifecycleRequest, opts ...grpc.CallOption) (*GetBucketLifecycleResponse, error)
	DeleteBucketLifecycle(ctx context.Context, in *DeleteBucketLifecycleRequest, opts ...grpc.CallOption) (*DeleteBucketLifecycleResponse, error)
	// ========== 对象操作 ==========
	// 流式上传（支持大文件分块上传）
	PutObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutObjectRequest, PutObjectResponse], error)
	// 流式下载（支持大文件分块下载）
	GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error)
	// 删除对象
	DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error)
	// 批量删除对象
	DeleteObjects(ctx context.Context, in *DeleteObjectsRequest, opts ...grpc.CallOption) (*DeleteObjectsResponse, error)
	// 列出对象
	ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error)
	// 复制对象
	CopyObject(ctx context.Context, in *CopyObjectRequest, opts ...grpc.CallOption) (*CopyObjectResponse, error)
	// 获取对象信息（不下载内容）
	StatObject(ctx context.Context, in *StatObjectRequest, opts ...grpc.CallOption) (*StatObjectResponse, error)
	// 对象标签管理
	SetObjectTags(ctx context.Context, in *SetObjectTagsRequest, opts ...grpc.CallOption) (*SetObjectTagsResponse, error)
	GetObjectTags(ctx context.Context, in *GetObjectTagsRequest, opts ...grpc.CallOption) (*GetObjectTagsResponse, error)
	DeleteObjectTags(ctx context.Context, in *DeleteObjectTagsRequest, opts ...grpc.CallOption) (*DeleteObjectTagsResponse, error)
	// ========== 预签名 URL ==========
	GetPresignedURL(ctx context.Context, in *GetPresignedURLRequest, opts ...grpc.CallOption) (*GetPresignedURLResponse, error)
	GetPresignedPutURL(ctx context.Context, in *GetPresignedPutURLRequest, opts ...grpc.CallOption) (*GetPresignedPutURLResponse, error)
	// ========== 多部分上传 ==========
	InitiateMultipartUpload(ctx context.Context, in *InitiateMultipartUploadRequest, opts ...grpc.CallOption) (*InitiateMultipartUploadResponse, error)
	UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPartRequest, UploadPartResponse], error)
	CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadRequest, opts ...grpc.CallOption) (*CompleteMultipartUploadResponse, error)
	AbortMultipartUpload(ctx context.Context, in *AbortMultipartUploadRequest, opts ...grpc.CallOption) (*AbortMultipartUploadResponse, error)
	// ========== 健康检查 ==========
	HealthCheck(ctx context.Context, in *MinIOHealthCheckRequest, opts ...grpc.CallOption) (*MinIOHealthCheckResponse, error)
}

type minIOServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewMinIOServiceClient(cc grpc.ClientConnInterface) MinIOServiceClient {
	return &minIOServiceClient{cc}
}

func (c *minIOServiceClient) CreateBucket(ctx context.Context, in *CreateBucketRequest, opts ...grpc.CallOption) (*CreateBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateBucketResponse)
	err := c.cc.Invoke(ctx, MinIOService_CreateBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) ListBuckets(ctx context.Context, in *ListBucketsRequest, opts ...grpc.CallOption) (*ListBucketsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListBucketsResponse)
	err := c.cc.Invoke(ctx, MinIOService_ListBuckets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) DeleteBucket(ctx context.Context, in *DeleteBucketRequest, opts ...grpc.CallOption) (*DeleteBucketResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBucketResponse)
	err := c.cc.Invoke(ctx, MinIOService_DeleteBucket_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) GetBucketInfo(ctx context.Context, in *GetBucketInfoRequest, opts ...grpc.CallOption) (*GetBucketInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketInfoResponse)
	err := c.cc.Invoke(ctx, MinIOService_GetBucketInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) SetBucketPolicy(ctx context.Context, in *SetBucketPolicyRequest, opts ...grpc.CallOption) (*SetBucketPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBucketPolicyResponse)
	err := c.cc.Invoke(ctx, MinIOService_SetBucketPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) GetBucketPolicy(ctx context.Context, in *GetBucketPolicyRequest, opts ...grpc.CallOption) (*GetBucketPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketPolicyResponse)
	err := c.cc.Invoke(ctx, MinIOService_GetBucketPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) SetBucketTags(ctx context.Context, in *SetBucketTagsRequest, opts ...grpc.CallOption) (*SetBucketTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBucketTagsResponse)
	err := c.cc.Invoke(ctx, MinIOService_SetBucketTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) GetBucketTags(ctx context.Context, in *GetBucketTagsRequest, opts ...grpc.CallOption) (*GetBucketTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketTagsResponse)
	err := c.cc.Invoke(ctx, MinIOService_GetBucketTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) DeleteBucketTags(ctx context.Context, in *DeleteBucketTagsRequest, opts ...grpc.CallOption) (*DeleteBucketTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBucketTagsResponse)
	err := c.cc.Invoke(ctx, MinIOService_DeleteBucketTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) SetBucketVersioning(ctx context.Context, in *SetBucketVersioningRequest, opts ...grpc.CallOption) (*SetBucketVersioningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBucketVersioningResponse)
	err := c.cc.Invoke(ctx, MinIOService_SetBucketVersioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) GetBucketVersioning(ctx context.Context, in *GetBucketVersioningRequest, opts ...grpc.CallOption) (*GetBucketVersioningResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketVersioningResponse)
	err := c.cc.Invoke(ctx, MinIOService_GetBucketVersioning_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) SetBucketLifecycle(ctx context.Context, in *SetBucketLifecycleRequest, opts ...grpc.CallOption) (*SetBucketLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetBucketLifecycleResponse)
	err := c.cc.Invoke(ctx, MinIOService_SetBucketLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) GetBucketLifecycle(ctx context.Context, in *GetBucketLifecycleRequest, opts ...grpc.CallOption) (*GetBucketLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBucketLifecycleResponse)
	err := c.cc.Invoke(ctx, MinIOService_GetBucketLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) DeleteBucketLifecycle(ctx context.Context, in *DeleteBucketLifecycleRequest, opts ...grpc.CallOption) (*DeleteBucketLifecycleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteBucketLifecycleResponse)
	err := c.cc.Invoke(ctx, MinIOService_DeleteBucketLifecycle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) PutObject(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutObjectRequest, PutObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinIOService_ServiceDesc.Streams[0], MinIOService_PutObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutObjectRequest, PutObjectResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinIOService_PutObjectClient = grpc.ClientStreamingClient[PutObjectRequest, PutObjectResponse]

func (c *minIOServiceClient) GetObject(ctx context.Context, in *GetObjectRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetObjectResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinIOService_ServiceDesc.Streams[1], MinIOService_GetObject_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetObjectRequest, GetObjectResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinIOService_GetObjectClient = grpc.ServerStreamingClient[GetObjectResponse]

func (c *minIOServiceClient) DeleteObject(ctx context.Context, in *DeleteObjectRequest, opts ...grpc.CallOption) (*DeleteObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectResponse)
	err := c.cc.Invoke(ctx, MinIOService_DeleteObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) DeleteObjects(ctx context.Context, in *DeleteObjectsRequest, opts ...grpc.CallOption) (*DeleteObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectsResponse)
	err := c.cc.Invoke(ctx, MinIOService_DeleteObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) ListObjects(ctx context.Context, in *ListObjectsRequest, opts ...grpc.CallOption) (*ListObjectsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListObjectsResponse)
	err := c.cc.Invoke(ctx, MinIOService_ListObjects_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) CopyObject(ctx context.Context, in *CopyObjectRequest, opts ...grpc.CallOption) (*CopyObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CopyObjectResponse)
	err := c.cc.Invoke(ctx, MinIOService_CopyObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) StatObject(ctx context.Context, in *StatObjectRequest, opts ...grpc.CallOption) (*StatObjectResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatObjectResponse)
	err := c.cc.Invoke(ctx, MinIOService_StatObject_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) SetObjectTags(ctx context.Context, in *SetObjectTagsRequest, opts ...grpc.CallOption) (*SetObjectTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetObjectTagsResponse)
	err := c.cc.Invoke(ctx, MinIOService_SetObjectTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) GetObjectTags(ctx context.Context, in *GetObjectTagsRequest, opts ...grpc.CallOption) (*GetObjectTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetObjectTagsResponse)
	err := c.cc.Invoke(ctx, MinIOService_GetObjectTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) DeleteObjectTags(ctx context.Context, in *DeleteObjectTagsRequest, opts ...grpc.CallOption) (*DeleteObjectTagsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteObjectTagsResponse)
	err := c.cc.Invoke(ctx, MinIOService_DeleteObjectTags_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) GetPresignedURL(ctx context.Context, in *GetPresignedURLRequest, opts ...grpc.CallOption) (*GetPresignedURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresignedURLResponse)
	err := c.cc.Invoke(ctx, MinIOService_GetPresignedURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) GetPresignedPutURL(ctx context.Context, in *GetPresignedPutURLRequest, opts ...grpc.CallOption) (*GetPresignedPutURLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPresignedPutURLResponse)
	err := c.cc.Invoke(ctx, MinIOService_GetPresignedPutURL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) InitiateMultipartUpload(ctx context.Context, in *InitiateMultipartUploadRequest, opts ...grpc.CallOption) (*InitiateMultipartUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InitiateMultipartUploadResponse)
	err := c.cc.Invoke(ctx, MinIOService_InitiateMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) UploadPart(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[UploadPartRequest, UploadPartResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &MinIOService_ServiceDesc.Streams[2], MinIOService_UploadPart_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UploadPartRequest, UploadPartResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinIOService_UploadPartClient = grpc.ClientStreamingClient[UploadPartRequest, UploadPartResponse]

func (c *minIOServiceClient) CompleteMultipartUpload(ctx context.Context, in *CompleteMultipartUploadRequest, opts ...grpc.CallOption) (*CompleteMultipartUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteMultipartUploadResponse)
	err := c.cc.Invoke(ctx, MinIOService_CompleteMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) AbortMultipartUpload(ctx context.Context, in *AbortMultipartUploadRequest, opts ...grpc.CallOption) (*AbortMultipartUploadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AbortMultipartUploadResponse)
	err := c.cc.Invoke(ctx, MinIOService_AbortMultipartUpload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *minIOServiceClient) HealthCheck(ctx context.Context, in *MinIOHealthCheckRequest, opts ...grpc.CallOption) (*MinIOHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MinIOHealthCheckResponse)
	err := c.cc.Invoke(ctx, MinIOService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MinIOServiceServer is the server API for MinIOService service.
// All implementations must embed UnimplementedMinIOServiceServer
// for forward compatibility.
type MinIOServiceServer interface {
	// ========== 桶管理 ==========
	CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error)
	ListBuckets(context.Context, *ListBucketsRequest) (*ListBucketsResponse, error)
	DeleteBucket(context.Context, *DeleteBucketRequest) (*DeleteBucketResponse, error)
	GetBucketInfo(context.Context, *GetBucketInfoRequest) (*GetBucketInfoResponse, error)
	SetBucketPolicy(context.Context, *SetBucketPolicyRequest) (*SetBucketPolicyResponse, error)
	GetBucketPolicy(context.Context, *GetBucketPolicyRequest) (*GetBucketPolicyResponse, error)
	SetBucketTags(context.Context, *SetBucketTagsRequest) (*SetBucketTagsResponse, error)
	GetBucketTags(context.Context, *GetBucketTagsRequest) (*GetBucketTagsResponse, error)
	DeleteBucketTags(context.Context, *DeleteBucketTagsRequest) (*DeleteBucketTagsResponse, error)
	SetBucketVersioning(context.Context, *SetBucketVersioningRequest) (*SetBucketVersioningResponse, error)
	GetBucketVersioning(context.Context, *GetBucketVersioningRequest) (*GetBucketVersioningResponse, error)
	SetBucketLifecycle(context.Context, *SetBucketLifecycleRequest) (*SetBucketLifecycleResponse, error)
	GetBucketLifecycle(context.Context, *GetBucketLifecycleRequest) (*GetBucketLifecycleResponse, error)
	DeleteBucketLifecycle(context.Context, *DeleteBucketLifecycleRequest) (*DeleteBucketLifecycleResponse, error)
	// ========== 对象操作 ==========
	// 流式上传（支持大文件分块上传）
	PutObject(grpc.ClientStreamingServer[PutObjectRequest, PutObjectResponse]) error
	// 流式下载（支持大文件分块下载）
	GetObject(*GetObjectRequest, grpc.ServerStreamingServer[GetObjectResponse]) error
	// 删除对象
	DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error)
	// 批量删除对象
	DeleteObjects(context.Context, *DeleteObjectsRequest) (*DeleteObjectsResponse, error)
	// 列出对象
	ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error)
	// 复制对象
	CopyObject(context.Context, *CopyObjectRequest) (*CopyObjectResponse, error)
	// 获取对象信息（不下载内容）
	StatObject(context.Context, *StatObjectRequest) (*StatObjectResponse, error)
	// 对象标签管理
	SetObjectTags(context.Context, *SetObjectTagsRequest) (*SetObjectTagsResponse, error)
	GetObjectTags(context.Context, *GetObjectTagsRequest) (*GetObjectTagsResponse, error)
	DeleteObjectTags(context.Context, *DeleteObjectTagsRequest) (*DeleteObjectTagsResponse, error)
	// ========== 预签名 URL ==========
	GetPresignedURL(context.Context, *GetPresignedURLRequest) (*GetPresignedURLResponse, error)
	GetPresignedPutURL(context.Context, *GetPresignedPutURLRequest) (*GetPresignedPutURLResponse, error)
	// ========== 多部分上传 ==========
	InitiateMultipartUpload(context.Context, *InitiateMultipartUploadRequest) (*InitiateMultipartUploadResponse, error)
	UploadPart(grpc.ClientStreamingServer[UploadPartRequest, UploadPartResponse]) error
	CompleteMultipartUpload(context.Context, *CompleteMultipartUploadRequest) (*CompleteMultipartUploadResponse, error)
	AbortMultipartUpload(context.Context, *AbortMultipartUploadRequest) (*AbortMultipartUploadResponse, error)
	// ========== 健康检查 ==========
	HealthCheck(context.Context, *MinIOHealthCheckRequest) (*MinIOHealthCheckResponse, error)
	mustEmbedUnimplementedMinIOServiceServer()
}

// UnimplementedMinIOServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedMinIOServiceServer struct{}

func (UnimplementedMinIOServiceServer) CreateBucket(context.Context, *CreateBucketRequest) (*CreateBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateBucket not implemented")
}
func (UnimplementedMinIOServiceServer) ListBuckets(context.Context, *ListBucketsRequest) (*ListBucketsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBuckets not implemented")
}
func (UnimplementedMinIOServiceServer) DeleteBucket(context.Context, *DeleteBucketRequest) (*DeleteBucketResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBucket not implemented")
}
func (UnimplementedMinIOServiceServer) GetBucketInfo(context.Context, *GetBucketInfoRequest) (*GetBucketInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBucketInfo not implemented")
}
func (UnimplementedMinIOServiceServer) SetBucketPolicy(context.Context, *SetBucketPolicyRequest) (*SetBucketPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBucketPolicy not implemented")
}
func (UnimplementedMinIOServiceServer) GetBucketPolicy(context.Context, *GetBucketPolicyRequest) (*GetBucketPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBucketPolicy not implemented")
}
func (UnimplementedMinIOServiceServer) SetBucketTags(context.Context, *SetBucketTagsRequest) (*SetBucketTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBucketTags not implemented")
}
func (UnimplementedMinIOServiceServer) GetBucketTags(context.Context, *GetBucketTagsRequest) (*GetBucketTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBucketTags not implemented")
}
func (UnimplementedMinIOServiceServer) DeleteBucketTags(context.Context, *DeleteBucketTagsRequest) (*DeleteBucketTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBucketTags not implemented")
}
func (UnimplementedMinIOServiceServer) SetBucketVersioning(context.Context, *SetBucketVersioningRequest) (*SetBucketVersioningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBucketVersioning not implemented")
}
func (UnimplementedMinIOServiceServer) GetBucketVersioning(context.Context, *GetBucketVersioningRequest) (*GetBucketVersioningResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBucketVersioning not implemented")
}
func (UnimplementedMinIOServiceServer) SetBucketLifecycle(context.Context, *SetBucketLifecycleRequest) (*SetBucketLifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetBucketLifecycle not implemented")
}
func (UnimplementedMinIOServiceServer) GetBucketLifecycle(context.Context, *GetBucketLifecycleRequest) (*GetBucketLifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBucketLifecycle not implemented")
}
func (UnimplementedMinIOServiceServer) DeleteBucketLifecycle(context.Context, *DeleteBucketLifecycleRequest) (*DeleteBucketLifecycleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteBucketLifecycle not implemented")
}
func (UnimplementedMinIOServiceServer) PutObject(grpc.ClientStreamingServer[PutObjectRequest, PutObjectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method PutObject not implemented")
}
func (UnimplementedMinIOServiceServer) GetObject(*GetObjectRequest, grpc.ServerStreamingServer[GetObjectResponse]) error {
	return status.Errorf(codes.Unimplemented, "method GetObject not implemented")
}
func (UnimplementedMinIOServiceServer) DeleteObject(context.Context, *DeleteObjectRequest) (*DeleteObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObject not implemented")
}
func (UnimplementedMinIOServiceServer) DeleteObjects(context.Context, *DeleteObjectsRequest) (*DeleteObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObjects not implemented")
}
func (UnimplementedMinIOServiceServer) ListObjects(context.Context, *ListObjectsRequest) (*ListObjectsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListObjects not implemented")
}
func (UnimplementedMinIOServiceServer) CopyObject(context.Context, *CopyObjectRequest) (*CopyObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CopyObject not implemented")
}
func (UnimplementedMinIOServiceServer) StatObject(context.Context, *StatObjectRequest) (*StatObjectResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatObject not implemented")
}
func (UnimplementedMinIOServiceServer) SetObjectTags(context.Context, *SetObjectTagsRequest) (*SetObjectTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetObjectTags not implemented")
}
func (UnimplementedMinIOServiceServer) GetObjectTags(context.Context, *GetObjectTagsRequest) (*GetObjectTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetObjectTags not implemented")
}
func (UnimplementedMinIOServiceServer) DeleteObjectTags(context.Context, *DeleteObjectTagsRequest) (*DeleteObjectTagsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteObjectTags not implemented")
}
func (UnimplementedMinIOServiceServer) GetPresignedURL(context.Context, *GetPresignedURLRequest) (*GetPresignedURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresignedURL not implemented")
}
func (UnimplementedMinIOServiceServer) GetPresignedPutURL(context.Context, *GetPresignedPutURLRequest) (*GetPresignedPutURLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPresignedPutURL not implemented")
}
func (UnimplementedMinIOServiceServer) InitiateMultipartUpload(context.Context, *InitiateMultipartUploadRequest) (*InitiateMultipartUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InitiateMultipartUpload not implemented")
}
func (UnimplementedMinIOServiceServer) UploadPart(grpc.ClientStreamingServer[UploadPartRequest, UploadPartResponse]) error {
	return status.Errorf(codes.Unimplemented, "method UploadPart not implemented")
}
func (UnimplementedMinIOServiceServer) CompleteMultipartUpload(context.Context, *CompleteMultipartUploadRequest) (*CompleteMultipartUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CompleteMultipartUpload not implemented")
}
func (UnimplementedMinIOServiceServer) AbortMultipartUpload(context.Context, *AbortMultipartUploadRequest) (*AbortMultipartUploadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AbortMultipartUpload not implemented")
}
func (UnimplementedMinIOServiceServer) HealthCheck(context.Context, *MinIOHealthCheckRequest) (*MinIOHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedMinIOServiceServer) mustEmbedUnimplementedMinIOServiceServer() {}
func (UnimplementedMinIOServiceServer) testEmbeddedByValue()                      {}

// UnsafeMinIOServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to MinIOServiceServer will
// result in compilation errors.
type UnsafeMinIOServiceServer interface {
	mustEmbedUnimplementedMinIOServiceServer()
}

func RegisterMinIOServiceServer(s grpc.ServiceRegistrar, srv MinIOServiceServer) {
	// If the following call pancis, it indicates UnimplementedMinIOServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&MinIOService_ServiceDesc, srv)
}

func _MinIOService_CreateBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).CreateBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_CreateBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).CreateBucket(ctx, req.(*CreateBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_ListBuckets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBucketsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).ListBuckets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_ListBuckets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).ListBuckets(ctx, req.(*ListBucketsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_DeleteBucket_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).DeleteBucket(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_DeleteBucket_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).DeleteBucket(ctx, req.(*DeleteBucketRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_GetBucketInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).GetBucketInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_GetBucketInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).GetBucketInfo(ctx, req.(*GetBucketInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_SetBucketPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBucketPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).SetBucketPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_SetBucketPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).SetBucketPolicy(ctx, req.(*SetBucketPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_GetBucketPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).GetBucketPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_GetBucketPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).GetBucketPolicy(ctx, req.(*GetBucketPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_SetBucketTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBucketTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).SetBucketTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_SetBucketTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).SetBucketTags(ctx, req.(*SetBucketTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_GetBucketTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).GetBucketTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_GetBucketTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).GetBucketTags(ctx, req.(*GetBucketTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_DeleteBucketTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).DeleteBucketTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_DeleteBucketTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).DeleteBucketTags(ctx, req.(*DeleteBucketTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_SetBucketVersioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBucketVersioningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).SetBucketVersioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_SetBucketVersioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).SetBucketVersioning(ctx, req.(*SetBucketVersioningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_GetBucketVersioning_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketVersioningRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).GetBucketVersioning(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_GetBucketVersioning_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).GetBucketVersioning(ctx, req.(*GetBucketVersioningRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_SetBucketLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetBucketLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).SetBucketLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_SetBucketLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).SetBucketLifecycle(ctx, req.(*SetBucketLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_GetBucketLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBucketLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).GetBucketLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_GetBucketLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).GetBucketLifecycle(ctx, req.(*GetBucketLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_DeleteBucketLifecycle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteBucketLifecycleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).DeleteBucketLifecycle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_DeleteBucketLifecycle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).DeleteBucketLifecycle(ctx, req.(*DeleteBucketLifecycleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_PutObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MinIOServiceServer).PutObject(&grpc.GenericServerStream[PutObjectRequest, PutObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinIOService_PutObjectServer = grpc.ClientStreamingServer[PutObjectRequest, PutObjectResponse]

func _MinIOService_GetObject_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetObjectRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(MinIOServiceServer).GetObject(m, &grpc.GenericServerStream[GetObjectRequest, GetObjectResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinIOService_GetObjectServer = grpc.ServerStreamingServer[GetObjectResponse]

func _MinIOService_DeleteObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).DeleteObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_DeleteObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).DeleteObject(ctx, req.(*DeleteObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_DeleteObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).DeleteObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_DeleteObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).DeleteObjects(ctx, req.(*DeleteObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_ListObjects_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListObjectsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).ListObjects(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_ListObjects_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).ListObjects(ctx, req.(*ListObjectsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_CopyObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CopyObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).CopyObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_CopyObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).CopyObject(ctx, req.(*CopyObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_StatObject_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatObjectRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).StatObject(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_StatObject_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).StatObject(ctx, req.(*StatObjectRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_SetObjectTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetObjectTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).SetObjectTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_SetObjectTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).SetObjectTags(ctx, req.(*SetObjectTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_GetObjectTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetObjectTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).GetObjectTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_GetObjectTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).GetObjectTags(ctx, req.(*GetObjectTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_DeleteObjectTags_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteObjectTagsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).DeleteObjectTags(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_DeleteObjectTags_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).DeleteObjectTags(ctx, req.(*DeleteObjectTagsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_GetPresignedURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).GetPresignedURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_GetPresignedURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).GetPresignedURL(ctx, req.(*GetPresignedURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_GetPresignedPutURL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPresignedPutURLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).GetPresignedPutURL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_GetPresignedPutURL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).GetPresignedPutURL(ctx, req.(*GetPresignedPutURLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_InitiateMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InitiateMultipartUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).InitiateMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_InitiateMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).InitiateMultipartUpload(ctx, req.(*InitiateMultipartUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_UploadPart_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MinIOServiceServer).UploadPart(&grpc.GenericServerStream[UploadPartRequest, UploadPartResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type MinIOService_UploadPartServer = grpc.ClientStreamingServer[UploadPartRequest, UploadPartResponse]

func _MinIOService_CompleteMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteMultipartUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).CompleteMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_CompleteMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).CompleteMultipartUpload(ctx, req.(*CompleteMultipartUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_AbortMultipartUpload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AbortMultipartUploadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).AbortMultipartUpload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_AbortMultipartUpload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).AbortMultipartUpload(ctx, req.(*AbortMultipartUploadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MinIOService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MinIOHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MinIOServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: MinIOService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MinIOServiceServer).HealthCheck(ctx, req.(*MinIOHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// MinIOService_ServiceDesc is the grpc.ServiceDesc for MinIOService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var MinIOService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "isa.minio.MinIOService",
	HandlerType: (*MinIOServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateBucket",
			Handler:    _MinIOService_CreateBucket_Handler,
		},
		{
			MethodName: "ListBuckets",
			Handler:    _MinIOService_ListBuckets_Handler,
		},
		{
			MethodName: "DeleteBucket",
			Handler:    _MinIOService_DeleteBucket_Handler,
		},
		{
			MethodName: "GetBucketInfo",
			Handler:    _MinIOService_GetBucketInfo_Handler,
		},
		{
			MethodName: "SetBucketPolicy",
			Handler:    _MinIOService_SetBucketPolicy_Handler,
		},
		{
			MethodName: "GetBucketPolicy",
			Handler:    _MinIOService_GetBucketPolicy_Handler,
		},
		{
			MethodName: "SetBucketTags",
			Handler:    _MinIOService_SetBucketTags_Handler,
		},
		{
			MethodName: "GetBucketTags",
			Handler:    _MinIOService_GetBucketTags_Handler,
		},
		{
			MethodName: "DeleteBucketTags",
			Handler:    _MinIOService_DeleteBucketTags_Handler,
		},
		{
			MethodName: "SetBucketVersioning",
			Handler:    _MinIOService_SetBucketVersioning_Handler,
		},
		{
			MethodName: "GetBucketVersioning",
			Handler:    _MinIOService_GetBucketVersioning_Handler,
		},
		{
			MethodName: "SetBucketLifecycle",
			Handler:    _MinIOService_SetBucketLifecycle_Handler,
		},
		{
			MethodName: "GetBucketLifecycle",
			Handler:    _MinIOService_GetBucketLifecycle_Handler,
		},
		{
			MethodName: "DeleteBucketLifecycle",
			Handler:    _MinIOService_DeleteBucketLifecycle_Handler,
		},
		{
			MethodName: "DeleteObject",
			Handler:    _MinIOService_DeleteObject_Handler,
		},
		{
			MethodName: "DeleteObjects",
			Handler:    _MinIOService_DeleteObjects_Handler,
		},
		{
			MethodName: "ListObjects",
			Handler:    _MinIOService_ListObjects_Handler,
		},
		{
			MethodName: "CopyObject",
			Handler:    _MinIOService_CopyObject_Handler,
		},
		{
			MethodName: "StatObject",
			Handler:    _MinIOService_StatObject_Handler,
		},
		{
			MethodName: "SetObjectTags",
			Handler:    _MinIOService_SetObjectTags_Handler,
		},
		{
			MethodName: "GetObjectTags",
			Handler:    _MinIOService_GetObjectTags_Handler,
		},
		{
			MethodName: "DeleteObjectTags",
			Handler:    _MinIOService_DeleteObjectTags_Handler,
		},
		{
			MethodName: "GetPresignedURL",
			Handler:    _MinIOService_GetPresignedURL_Handler,
		},
		{
			MethodName: "GetPresignedPutURL",
			Handler:    _MinIOService_GetPresignedPutURL_Handler,
		},
		{
			MethodName: "InitiateMultipartUpload",
			Handler:    _MinIOService_InitiateMultipartUpload_Handler,
		},
		{
			MethodName: "CompleteMultipartUpload",
			Handler:    _MinIOService_CompleteMultipartUpload_Handler,
		},
		{
			MethodName: "AbortMultipartUpload",
			Handler:    _MinIOService_AbortMultipartUpload_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _MinIOService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "PutObject",
			Handler:       _MinIOService_PutObject_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "GetObject",
			Handler:       _MinIOService_GetObject_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UploadPart",
			Handler:       _MinIOService_UploadPart_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "minio_service.proto",
}
