// qdrant_service.proto - Qdrant Vector Database gRPC Service
// High-performance vector search with filtering and hybrid search capabilities

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: qdrant_service.proto

package qdrant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QdrantService_CreateCollection_FullMethodName      = "/isa.qdrant.QdrantService/CreateCollection"
	QdrantService_ListCollections_FullMethodName       = "/isa.qdrant.QdrantService/ListCollections"
	QdrantService_GetCollectionInfo_FullMethodName     = "/isa.qdrant.QdrantService/GetCollectionInfo"
	QdrantService_UpdateCollection_FullMethodName      = "/isa.qdrant.QdrantService/UpdateCollection"
	QdrantService_DeleteCollection_FullMethodName      = "/isa.qdrant.QdrantService/DeleteCollection"
	QdrantService_CreateCollectionAlias_FullMethodName = "/isa.qdrant.QdrantService/CreateCollectionAlias"
	QdrantService_UpsertPoints_FullMethodName          = "/isa.qdrant.QdrantService/UpsertPoints"
	QdrantService_GetPoints_FullMethodName             = "/isa.qdrant.QdrantService/GetPoints"
	QdrantService_DeletePoints_FullMethodName          = "/isa.qdrant.QdrantService/DeletePoints"
	QdrantService_UpdatePayload_FullMethodName         = "/isa.qdrant.QdrantService/UpdatePayload"
	QdrantService_DeletePayload_FullMethodName         = "/isa.qdrant.QdrantService/DeletePayload"
	QdrantService_ClearPayload_FullMethodName          = "/isa.qdrant.QdrantService/ClearPayload"
	QdrantService_Search_FullMethodName                = "/isa.qdrant.QdrantService/Search"
	QdrantService_SearchBatch_FullMethodName           = "/isa.qdrant.QdrantService/SearchBatch"
	QdrantService_Recommend_FullMethodName             = "/isa.qdrant.QdrantService/Recommend"
	QdrantService_Discover_FullMethodName              = "/isa.qdrant.QdrantService/Discover"
	QdrantService_Scroll_FullMethodName                = "/isa.qdrant.QdrantService/Scroll"
	QdrantService_Count_FullMethodName                 = "/isa.qdrant.QdrantService/Count"
	QdrantService_CreateFieldIndex_FullMethodName      = "/isa.qdrant.QdrantService/CreateFieldIndex"
	QdrantService_DeleteFieldIndex_FullMethodName      = "/isa.qdrant.QdrantService/DeleteFieldIndex"
	QdrantService_CreateSnapshot_FullMethodName        = "/isa.qdrant.QdrantService/CreateSnapshot"
	QdrantService_ListSnapshots_FullMethodName         = "/isa.qdrant.QdrantService/ListSnapshots"
	QdrantService_DeleteSnapshot_FullMethodName        = "/isa.qdrant.QdrantService/DeleteSnapshot"
	QdrantService_HealthCheck_FullMethodName           = "/isa.qdrant.QdrantService/HealthCheck"
	QdrantService_GetClusterInfo_FullMethodName        = "/isa.qdrant.QdrantService/GetClusterInfo"
)

// QdrantServiceClient is the client API for QdrantService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QdrantServiceClient interface {
	// CreateCollection - Create a new vector collection
	CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error)
	// ListCollections - List all collections
	ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error)
	// GetCollectionInfo - Get detailed collection information
	GetCollectionInfo(ctx context.Context, in *GetCollectionInfoRequest, opts ...grpc.CallOption) (*GetCollectionInfoResponse, error)
	// UpdateCollection - Update collection parameters
	UpdateCollection(ctx context.Context, in *UpdateCollectionRequest, opts ...grpc.CallOption) (*UpdateCollectionResponse, error)
	// DeleteCollection - Delete a collection
	DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*DeleteCollectionResponse, error)
	// CreateCollectionAlias - Create collection alias
	CreateCollectionAlias(ctx context.Context, in *CreateCollectionAliasRequest, opts ...grpc.CallOption) (*CreateCollectionAliasResponse, error)
	// UpsertPoints - Insert or update points (vectors with payload)
	UpsertPoints(ctx context.Context, in *UpsertPointsRequest, opts ...grpc.CallOption) (*UpsertPointsResponse, error)
	// GetPoints - Retrieve points by IDs
	GetPoints(ctx context.Context, in *GetPointsRequest, opts ...grpc.CallOption) (*GetPointsResponse, error)
	// DeletePoints - Delete points by IDs or filter
	DeletePoints(ctx context.Context, in *DeletePointsRequest, opts ...grpc.CallOption) (*DeletePointsResponse, error)
	// UpdatePayload - Update payload for points
	UpdatePayload(ctx context.Context, in *UpdatePayloadRequest, opts ...grpc.CallOption) (*UpdatePayloadResponse, error)
	// DeletePayload - Delete specific payload fields
	DeletePayload(ctx context.Context, in *DeletePayloadRequest, opts ...grpc.CallOption) (*DeletePayloadResponse, error)
	// ClearPayload - Clear all payload data
	ClearPayload(ctx context.Context, in *ClearPayloadRequest, opts ...grpc.CallOption) (*ClearPayloadResponse, error)
	// Search - Vector similarity search
	Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error)
	// SearchBatch - Batch vector search
	SearchBatch(ctx context.Context, in *SearchBatchRequest, opts ...grpc.CallOption) (*SearchBatchResponse, error)
	// Recommend - Recommendation based on positive/negative examples
	Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error)
	// Discover - Discovery search (find points similar to positive but different from negative)
	Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error)
	// Scroll - Iterate through all points
	Scroll(ctx context.Context, in *ScrollRequest, opts ...grpc.CallOption) (*ScrollResponse, error)
	// Count - Count points matching filter
	Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error)
	// CreateFieldIndex - Create payload field index
	CreateFieldIndex(ctx context.Context, in *CreateFieldIndexRequest, opts ...grpc.CallOption) (*CreateFieldIndexResponse, error)
	// DeleteFieldIndex - Delete payload field index
	DeleteFieldIndex(ctx context.Context, in *DeleteFieldIndexRequest, opts ...grpc.CallOption) (*DeleteFieldIndexResponse, error)
	// CreateSnapshot - Create collection snapshot
	CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error)
	// ListSnapshots - List available snapshots
	ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error)
	// DeleteSnapshot - Delete a snapshot
	DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error)
	// HealthCheck - Service health check
	HealthCheck(ctx context.Context, in *QdrantHealthCheckRequest, opts ...grpc.CallOption) (*QdrantHealthCheckResponse, error)
	// GetClusterInfo - Get cluster information
	GetClusterInfo(ctx context.Context, in *GetClusterInfoRequest, opts ...grpc.CallOption) (*GetClusterInfoResponse, error)
}

type qdrantServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQdrantServiceClient(cc grpc.ClientConnInterface) QdrantServiceClient {
	return &qdrantServiceClient{cc}
}

func (c *qdrantServiceClient) CreateCollection(ctx context.Context, in *CreateCollectionRequest, opts ...grpc.CallOption) (*CreateCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectionResponse)
	err := c.cc.Invoke(ctx, QdrantService_CreateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) ListCollections(ctx context.Context, in *ListCollectionsRequest, opts ...grpc.CallOption) (*ListCollectionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListCollectionsResponse)
	err := c.cc.Invoke(ctx, QdrantService_ListCollections_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) GetCollectionInfo(ctx context.Context, in *GetCollectionInfoRequest, opts ...grpc.CallOption) (*GetCollectionInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionInfoResponse)
	err := c.cc.Invoke(ctx, QdrantService_GetCollectionInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) UpdateCollection(ctx context.Context, in *UpdateCollectionRequest, opts ...grpc.CallOption) (*UpdateCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateCollectionResponse)
	err := c.cc.Invoke(ctx, QdrantService_UpdateCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) DeleteCollection(ctx context.Context, in *DeleteCollectionRequest, opts ...grpc.CallOption) (*DeleteCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteCollectionResponse)
	err := c.cc.Invoke(ctx, QdrantService_DeleteCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) CreateCollectionAlias(ctx context.Context, in *CreateCollectionAliasRequest, opts ...grpc.CallOption) (*CreateCollectionAliasResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateCollectionAliasResponse)
	err := c.cc.Invoke(ctx, QdrantService_CreateCollectionAlias_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) UpsertPoints(ctx context.Context, in *UpsertPointsRequest, opts ...grpc.CallOption) (*UpsertPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertPointsResponse)
	err := c.cc.Invoke(ctx, QdrantService_UpsertPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) GetPoints(ctx context.Context, in *GetPointsRequest, opts ...grpc.CallOption) (*GetPointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetPointsResponse)
	err := c.cc.Invoke(ctx, QdrantService_GetPoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) DeletePoints(ctx context.Context, in *DeletePointsRequest, opts ...grpc.CallOption) (*DeletePointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePointsResponse)
	err := c.cc.Invoke(ctx, QdrantService_DeletePoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) UpdatePayload(ctx context.Context, in *UpdatePayloadRequest, opts ...grpc.CallOption) (*UpdatePayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdatePayloadResponse)
	err := c.cc.Invoke(ctx, QdrantService_UpdatePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) DeletePayload(ctx context.Context, in *DeletePayloadRequest, opts ...grpc.CallOption) (*DeletePayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeletePayloadResponse)
	err := c.cc.Invoke(ctx, QdrantService_DeletePayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) ClearPayload(ctx context.Context, in *ClearPayloadRequest, opts ...grpc.CallOption) (*ClearPayloadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClearPayloadResponse)
	err := c.cc.Invoke(ctx, QdrantService_ClearPayload_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) Search(ctx context.Context, in *SearchRequest, opts ...grpc.CallOption) (*SearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchResponse)
	err := c.cc.Invoke(ctx, QdrantService_Search_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) SearchBatch(ctx context.Context, in *SearchBatchRequest, opts ...grpc.CallOption) (*SearchBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchBatchResponse)
	err := c.cc.Invoke(ctx, QdrantService_SearchBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) Recommend(ctx context.Context, in *RecommendRequest, opts ...grpc.CallOption) (*RecommendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RecommendResponse)
	err := c.cc.Invoke(ctx, QdrantService_Recommend_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) Discover(ctx context.Context, in *DiscoverRequest, opts ...grpc.CallOption) (*DiscoverResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DiscoverResponse)
	err := c.cc.Invoke(ctx, QdrantService_Discover_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) Scroll(ctx context.Context, in *ScrollRequest, opts ...grpc.CallOption) (*ScrollResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ScrollResponse)
	err := c.cc.Invoke(ctx, QdrantService_Scroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) Count(ctx context.Context, in *CountRequest, opts ...grpc.CallOption) (*CountResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CountResponse)
	err := c.cc.Invoke(ctx, QdrantService_Count_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) CreateFieldIndex(ctx context.Context, in *CreateFieldIndexRequest, opts ...grpc.CallOption) (*CreateFieldIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFieldIndexResponse)
	err := c.cc.Invoke(ctx, QdrantService_CreateFieldIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) DeleteFieldIndex(ctx context.Context, in *DeleteFieldIndexRequest, opts ...grpc.CallOption) (*DeleteFieldIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteFieldIndexResponse)
	err := c.cc.Invoke(ctx, QdrantService_DeleteFieldIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) CreateSnapshot(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*CreateSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSnapshotResponse)
	err := c.cc.Invoke(ctx, QdrantService_CreateSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) ListSnapshots(ctx context.Context, in *ListSnapshotsRequest, opts ...grpc.CallOption) (*ListSnapshotsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSnapshotsResponse)
	err := c.cc.Invoke(ctx, QdrantService_ListSnapshots_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) DeleteSnapshot(ctx context.Context, in *DeleteSnapshotRequest, opts ...grpc.CallOption) (*DeleteSnapshotResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSnapshotResponse)
	err := c.cc.Invoke(ctx, QdrantService_DeleteSnapshot_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) HealthCheck(ctx context.Context, in *QdrantHealthCheckRequest, opts ...grpc.CallOption) (*QdrantHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QdrantHealthCheckResponse)
	err := c.cc.Invoke(ctx, QdrantService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *qdrantServiceClient) GetClusterInfo(ctx context.Context, in *GetClusterInfoRequest, opts ...grpc.CallOption) (*GetClusterInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterInfoResponse)
	err := c.cc.Invoke(ctx, QdrantService_GetClusterInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QdrantServiceServer is the server API for QdrantService service.
// All implementations must embed UnimplementedQdrantServiceServer
// for forward compatibility.
type QdrantServiceServer interface {
	// CreateCollection - Create a new vector collection
	CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error)
	// ListCollections - List all collections
	ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error)
	// GetCollectionInfo - Get detailed collection information
	GetCollectionInfo(context.Context, *GetCollectionInfoRequest) (*GetCollectionInfoResponse, error)
	// UpdateCollection - Update collection parameters
	UpdateCollection(context.Context, *UpdateCollectionRequest) (*UpdateCollectionResponse, error)
	// DeleteCollection - Delete a collection
	DeleteCollection(context.Context, *DeleteCollectionRequest) (*DeleteCollectionResponse, error)
	// CreateCollectionAlias - Create collection alias
	CreateCollectionAlias(context.Context, *CreateCollectionAliasRequest) (*CreateCollectionAliasResponse, error)
	// UpsertPoints - Insert or update points (vectors with payload)
	UpsertPoints(context.Context, *UpsertPointsRequest) (*UpsertPointsResponse, error)
	// GetPoints - Retrieve points by IDs
	GetPoints(context.Context, *GetPointsRequest) (*GetPointsResponse, error)
	// DeletePoints - Delete points by IDs or filter
	DeletePoints(context.Context, *DeletePointsRequest) (*DeletePointsResponse, error)
	// UpdatePayload - Update payload for points
	UpdatePayload(context.Context, *UpdatePayloadRequest) (*UpdatePayloadResponse, error)
	// DeletePayload - Delete specific payload fields
	DeletePayload(context.Context, *DeletePayloadRequest) (*DeletePayloadResponse, error)
	// ClearPayload - Clear all payload data
	ClearPayload(context.Context, *ClearPayloadRequest) (*ClearPayloadResponse, error)
	// Search - Vector similarity search
	Search(context.Context, *SearchRequest) (*SearchResponse, error)
	// SearchBatch - Batch vector search
	SearchBatch(context.Context, *SearchBatchRequest) (*SearchBatchResponse, error)
	// Recommend - Recommendation based on positive/negative examples
	Recommend(context.Context, *RecommendRequest) (*RecommendResponse, error)
	// Discover - Discovery search (find points similar to positive but different from negative)
	Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error)
	// Scroll - Iterate through all points
	Scroll(context.Context, *ScrollRequest) (*ScrollResponse, error)
	// Count - Count points matching filter
	Count(context.Context, *CountRequest) (*CountResponse, error)
	// CreateFieldIndex - Create payload field index
	CreateFieldIndex(context.Context, *CreateFieldIndexRequest) (*CreateFieldIndexResponse, error)
	// DeleteFieldIndex - Delete payload field index
	DeleteFieldIndex(context.Context, *DeleteFieldIndexRequest) (*DeleteFieldIndexResponse, error)
	// CreateSnapshot - Create collection snapshot
	CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error)
	// ListSnapshots - List available snapshots
	ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error)
	// DeleteSnapshot - Delete a snapshot
	DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error)
	// HealthCheck - Service health check
	HealthCheck(context.Context, *QdrantHealthCheckRequest) (*QdrantHealthCheckResponse, error)
	// GetClusterInfo - Get cluster information
	GetClusterInfo(context.Context, *GetClusterInfoRequest) (*GetClusterInfoResponse, error)
	mustEmbedUnimplementedQdrantServiceServer()
}

// UnimplementedQdrantServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQdrantServiceServer struct{}

func (UnimplementedQdrantServiceServer) CreateCollection(context.Context, *CreateCollectionRequest) (*CreateCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollection not implemented")
}
func (UnimplementedQdrantServiceServer) ListCollections(context.Context, *ListCollectionsRequest) (*ListCollectionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListCollections not implemented")
}
func (UnimplementedQdrantServiceServer) GetCollectionInfo(context.Context, *GetCollectionInfoRequest) (*GetCollectionInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCollectionInfo not implemented")
}
func (UnimplementedQdrantServiceServer) UpdateCollection(context.Context, *UpdateCollectionRequest) (*UpdateCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateCollection not implemented")
}
func (UnimplementedQdrantServiceServer) DeleteCollection(context.Context, *DeleteCollectionRequest) (*DeleteCollectionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteCollection not implemented")
}
func (UnimplementedQdrantServiceServer) CreateCollectionAlias(context.Context, *CreateCollectionAliasRequest) (*CreateCollectionAliasResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateCollectionAlias not implemented")
}
func (UnimplementedQdrantServiceServer) UpsertPoints(context.Context, *UpsertPointsRequest) (*UpsertPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertPoints not implemented")
}
func (UnimplementedQdrantServiceServer) GetPoints(context.Context, *GetPointsRequest) (*GetPointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPoints not implemented")
}
func (UnimplementedQdrantServiceServer) DeletePoints(context.Context, *DeletePointsRequest) (*DeletePointsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePoints not implemented")
}
func (UnimplementedQdrantServiceServer) UpdatePayload(context.Context, *UpdatePayloadRequest) (*UpdatePayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdatePayload not implemented")
}
func (UnimplementedQdrantServiceServer) DeletePayload(context.Context, *DeletePayloadRequest) (*DeletePayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeletePayload not implemented")
}
func (UnimplementedQdrantServiceServer) ClearPayload(context.Context, *ClearPayloadRequest) (*ClearPayloadResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ClearPayload not implemented")
}
func (UnimplementedQdrantServiceServer) Search(context.Context, *SearchRequest) (*SearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Search not implemented")
}
func (UnimplementedQdrantServiceServer) SearchBatch(context.Context, *SearchBatchRequest) (*SearchBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SearchBatch not implemented")
}
func (UnimplementedQdrantServiceServer) Recommend(context.Context, *RecommendRequest) (*RecommendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Recommend not implemented")
}
func (UnimplementedQdrantServiceServer) Discover(context.Context, *DiscoverRequest) (*DiscoverResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Discover not implemented")
}
func (UnimplementedQdrantServiceServer) Scroll(context.Context, *ScrollRequest) (*ScrollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Scroll not implemented")
}
func (UnimplementedQdrantServiceServer) Count(context.Context, *CountRequest) (*CountResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Count not implemented")
}
func (UnimplementedQdrantServiceServer) CreateFieldIndex(context.Context, *CreateFieldIndexRequest) (*CreateFieldIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFieldIndex not implemented")
}
func (UnimplementedQdrantServiceServer) DeleteFieldIndex(context.Context, *DeleteFieldIndexRequest) (*DeleteFieldIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteFieldIndex not implemented")
}
func (UnimplementedQdrantServiceServer) CreateSnapshot(context.Context, *CreateSnapshotRequest) (*CreateSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSnapshot not implemented")
}
func (UnimplementedQdrantServiceServer) ListSnapshots(context.Context, *ListSnapshotsRequest) (*ListSnapshotsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSnapshots not implemented")
}
func (UnimplementedQdrantServiceServer) DeleteSnapshot(context.Context, *DeleteSnapshotRequest) (*DeleteSnapshotResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSnapshot not implemented")
}
func (UnimplementedQdrantServiceServer) HealthCheck(context.Context, *QdrantHealthCheckRequest) (*QdrantHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedQdrantServiceServer) GetClusterInfo(context.Context, *GetClusterInfoRequest) (*GetClusterInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetClusterInfo not implemented")
}
func (UnimplementedQdrantServiceServer) mustEmbedUnimplementedQdrantServiceServer() {}
func (UnimplementedQdrantServiceServer) testEmbeddedByValue()                       {}

// UnsafeQdrantServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QdrantServiceServer will
// result in compilation errors.
type UnsafeQdrantServiceServer interface {
	mustEmbedUnimplementedQdrantServiceServer()
}

func RegisterQdrantServiceServer(s grpc.ServiceRegistrar, srv QdrantServiceServer) {
	// If the following call pancis, it indicates UnimplementedQdrantServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QdrantService_ServiceDesc, srv)
}

func _QdrantService_CreateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).CreateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_CreateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).CreateCollection(ctx, req.(*CreateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_ListCollections_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListCollectionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).ListCollections(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_ListCollections_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).ListCollections(ctx, req.(*ListCollectionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_GetCollectionInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).GetCollectionInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_GetCollectionInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).GetCollectionInfo(ctx, req.(*GetCollectionInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_UpdateCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).UpdateCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_UpdateCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).UpdateCollection(ctx, req.(*UpdateCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_DeleteCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).DeleteCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_DeleteCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).DeleteCollection(ctx, req.(*DeleteCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_CreateCollectionAlias_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateCollectionAliasRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).CreateCollectionAlias(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_CreateCollectionAlias_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).CreateCollectionAlias(ctx, req.(*CreateCollectionAliasRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_UpsertPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).UpsertPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_UpsertPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).UpsertPoints(ctx, req.(*UpsertPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_GetPoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).GetPoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_GetPoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).GetPoints(ctx, req.(*GetPointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_DeletePoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).DeletePoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_DeletePoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).DeletePoints(ctx, req.(*DeletePointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_UpdatePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdatePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).UpdatePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_UpdatePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).UpdatePayload(ctx, req.(*UpdatePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_DeletePayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeletePayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).DeletePayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_DeletePayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).DeletePayload(ctx, req.(*DeletePayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_ClearPayload_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClearPayloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).ClearPayload(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_ClearPayload_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).ClearPayload(ctx, req.(*ClearPayloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_Search_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).Search(ctx, req.(*SearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_SearchBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).SearchBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_SearchBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).SearchBatch(ctx, req.(*SearchBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_Recommend_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RecommendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).Recommend(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_Recommend_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).Recommend(ctx, req.(*RecommendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_Discover_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DiscoverRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).Discover(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_Discover_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).Discover(ctx, req.(*DiscoverRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_Scroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ScrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).Scroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_Scroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).Scroll(ctx, req.(*ScrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_Count_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).Count(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_Count_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).Count(ctx, req.(*CountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_CreateFieldIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFieldIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).CreateFieldIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_CreateFieldIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).CreateFieldIndex(ctx, req.(*CreateFieldIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_DeleteFieldIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteFieldIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).DeleteFieldIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_DeleteFieldIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).DeleteFieldIndex(ctx, req.(*DeleteFieldIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_CreateSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).CreateSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_CreateSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).CreateSnapshot(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_ListSnapshots_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSnapshotsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).ListSnapshots(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_ListSnapshots_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).ListSnapshots(ctx, req.(*ListSnapshotsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_DeleteSnapshot_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).DeleteSnapshot(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_DeleteSnapshot_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).DeleteSnapshot(ctx, req.(*DeleteSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QdrantHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).HealthCheck(ctx, req.(*QdrantHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QdrantService_GetClusterInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QdrantServiceServer).GetClusterInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QdrantService_GetClusterInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QdrantServiceServer).GetClusterInfo(ctx, req.(*GetClusterInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// QdrantService_ServiceDesc is the grpc.ServiceDesc for QdrantService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QdrantService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "isa.qdrant.QdrantService",
	HandlerType: (*QdrantServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateCollection",
			Handler:    _QdrantService_CreateCollection_Handler,
		},
		{
			MethodName: "ListCollections",
			Handler:    _QdrantService_ListCollections_Handler,
		},
		{
			MethodName: "GetCollectionInfo",
			Handler:    _QdrantService_GetCollectionInfo_Handler,
		},
		{
			MethodName: "UpdateCollection",
			Handler:    _QdrantService_UpdateCollection_Handler,
		},
		{
			MethodName: "DeleteCollection",
			Handler:    _QdrantService_DeleteCollection_Handler,
		},
		{
			MethodName: "CreateCollectionAlias",
			Handler:    _QdrantService_CreateCollectionAlias_Handler,
		},
		{
			MethodName: "UpsertPoints",
			Handler:    _QdrantService_UpsertPoints_Handler,
		},
		{
			MethodName: "GetPoints",
			Handler:    _QdrantService_GetPoints_Handler,
		},
		{
			MethodName: "DeletePoints",
			Handler:    _QdrantService_DeletePoints_Handler,
		},
		{
			MethodName: "UpdatePayload",
			Handler:    _QdrantService_UpdatePayload_Handler,
		},
		{
			MethodName: "DeletePayload",
			Handler:    _QdrantService_DeletePayload_Handler,
		},
		{
			MethodName: "ClearPayload",
			Handler:    _QdrantService_ClearPayload_Handler,
		},
		{
			MethodName: "Search",
			Handler:    _QdrantService_Search_Handler,
		},
		{
			MethodName: "SearchBatch",
			Handler:    _QdrantService_SearchBatch_Handler,
		},
		{
			MethodName: "Recommend",
			Handler:    _QdrantService_Recommend_Handler,
		},
		{
			MethodName: "Discover",
			Handler:    _QdrantService_Discover_Handler,
		},
		{
			MethodName: "Scroll",
			Handler:    _QdrantService_Scroll_Handler,
		},
		{
			MethodName: "Count",
			Handler:    _QdrantService_Count_Handler,
		},
		{
			MethodName: "CreateFieldIndex",
			Handler:    _QdrantService_CreateFieldIndex_Handler,
		},
		{
			MethodName: "DeleteFieldIndex",
			Handler:    _QdrantService_DeleteFieldIndex_Handler,
		},
		{
			MethodName: "CreateSnapshot",
			Handler:    _QdrantService_CreateSnapshot_Handler,
		},
		{
			MethodName: "ListSnapshots",
			Handler:    _QdrantService_ListSnapshots_Handler,
		},
		{
			MethodName: "DeleteSnapshot",
			Handler:    _QdrantService_DeleteSnapshot_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _QdrantService_HealthCheck_Handler,
		},
		{
			MethodName: "GetClusterInfo",
			Handler:    _QdrantService_GetClusterInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "qdrant_service.proto",
}
