# =============================================================================
# isA Cloud - Development Environment (App of Apps)
# =============================================================================
# Development environment for local Kind cluster testing.
# Tracks the 'develop' branch for latest changes.
# =============================================================================
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isa-cloud-dev
  namespace: argocd
  labels:
    environment: dev
    project: isa-cloud
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  # App-of-apps source
  source:
    repoURL: https://github.com/your-org/isA_Cloud.git
    targetRevision: develop
    path: deployments/argocd/apps/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: argocd

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  info:
    - name: 'Environment'
      value: 'Development'
    - name: 'Pattern'
      value: 'App-of-Apps'
    - name: 'Auto-Sync'
      value: 'Enabled'
