apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: isa-cloud-dev
  namespace: argocd
  labels:
    environment: dev
    project: isa-cloud
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default

  source:
    repoURL: https://github.com/your-org/isA_Cloud.git
    targetRevision: develop  # Dev 环境跟踪 develop 分支
    path: deployments/kubernetes/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: isa-cloud-dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground

    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m

  info:
    - name: 'Environment'
      value: 'Development'
    - name: 'Auto-Sync'
      value: 'Enabled'
