// duckdb_service.proto - DuckDB 数据分析服务 gRPC 接口
// 提供高性能的 OLAP 分析能力，数据存储在 MinIO 中，支持用户隔离

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: duckdb_service.proto

package duckdb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DuckDBService_CreateDatabase_FullMethodName     = "/isa.duckdb.DuckDBService/CreateDatabase"
	DuckDBService_ListDatabases_FullMethodName      = "/isa.duckdb.DuckDBService/ListDatabases"
	DuckDBService_DeleteDatabase_FullMethodName     = "/isa.duckdb.DuckDBService/DeleteDatabase"
	DuckDBService_GetDatabaseInfo_FullMethodName    = "/isa.duckdb.DuckDBService/GetDatabaseInfo"
	DuckDBService_BackupDatabase_FullMethodName     = "/isa.duckdb.DuckDBService/BackupDatabase"
	DuckDBService_RestoreDatabase_FullMethodName    = "/isa.duckdb.DuckDBService/RestoreDatabase"
	DuckDBService_ExecuteQuery_FullMethodName       = "/isa.duckdb.DuckDBService/ExecuteQuery"
	DuckDBService_ExecuteQueryStream_FullMethodName = "/isa.duckdb.DuckDBService/ExecuteQueryStream"
	DuckDBService_ExecuteStatement_FullMethodName   = "/isa.duckdb.DuckDBService/ExecuteStatement"
	DuckDBService_ExecuteBatch_FullMethodName       = "/isa.duckdb.DuckDBService/ExecuteBatch"
	DuckDBService_PrepareStatement_FullMethodName   = "/isa.duckdb.DuckDBService/PrepareStatement"
	DuckDBService_CreateTable_FullMethodName        = "/isa.duckdb.DuckDBService/CreateTable"
	DuckDBService_ListTables_FullMethodName         = "/isa.duckdb.DuckDBService/ListTables"
	DuckDBService_DropTable_FullMethodName          = "/isa.duckdb.DuckDBService/DropTable"
	DuckDBService_GetTableSchema_FullMethodName     = "/isa.duckdb.DuckDBService/GetTableSchema"
	DuckDBService_GetTableStats_FullMethodName      = "/isa.duckdb.DuckDBService/GetTableStats"
	DuckDBService_CreateView_FullMethodName         = "/isa.duckdb.DuckDBService/CreateView"
	DuckDBService_ListViews_FullMethodName          = "/isa.duckdb.DuckDBService/ListViews"
	DuckDBService_DropView_FullMethodName           = "/isa.duckdb.DuckDBService/DropView"
	DuckDBService_ImportFromMinIO_FullMethodName    = "/isa.duckdb.DuckDBService/ImportFromMinIO"
	DuckDBService_ExportToMinIO_FullMethodName      = "/isa.duckdb.DuckDBService/ExportToMinIO"
	DuckDBService_QueryMinIOFile_FullMethodName     = "/isa.duckdb.DuckDBService/QueryMinIOFile"
	DuckDBService_ImportData_FullMethodName         = "/isa.duckdb.DuckDBService/ImportData"
	DuckDBService_InstallExtension_FullMethodName   = "/isa.duckdb.DuckDBService/InstallExtension"
	DuckDBService_ListExtensions_FullMethodName     = "/isa.duckdb.DuckDBService/ListExtensions"
	DuckDBService_CreateFunction_FullMethodName     = "/isa.duckdb.DuckDBService/CreateFunction"
	DuckDBService_HealthCheck_FullMethodName        = "/isa.duckdb.DuckDBService/HealthCheck"
	DuckDBService_GetMetrics_FullMethodName         = "/isa.duckdb.DuckDBService/GetMetrics"
)

// DuckDBServiceClient is the client API for DuckDBService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DuckDBServiceClient interface {
	// ========== 数据库管理 ==========
	CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error)
	ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error)
	DeleteDatabase(ctx context.Context, in *DeleteDatabaseRequest, opts ...grpc.CallOption) (*DeleteDatabaseResponse, error)
	GetDatabaseInfo(ctx context.Context, in *GetDatabaseInfoRequest, opts ...grpc.CallOption) (*GetDatabaseInfoResponse, error)
	BackupDatabase(ctx context.Context, in *BackupDatabaseRequest, opts ...grpc.CallOption) (*BackupDatabaseResponse, error)
	RestoreDatabase(ctx context.Context, in *RestoreDatabaseRequest, opts ...grpc.CallOption) (*RestoreDatabaseResponse, error)
	// ========== 查询操作 ==========
	// 执行 SQL 查询（返回完整结果）
	ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error)
	// 流式查询（适合大结果集）
	ExecuteQueryStream(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultChunk], error)
	// 执行写操作（INSERT、UPDATE、DELETE）
	ExecuteStatement(ctx context.Context, in *ExecuteStatementRequest, opts ...grpc.CallOption) (*ExecuteStatementResponse, error)
	// 批量执行 SQL
	ExecuteBatch(ctx context.Context, in *ExecuteBatchRequest, opts ...grpc.CallOption) (*ExecuteBatchResponse, error)
	// 准备预编译语句
	PrepareStatement(ctx context.Context, in *PrepareStatementRequest, opts ...grpc.CallOption) (*PrepareStatementResponse, error)
	// ========== 表管理 ==========
	CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error)
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error)
	GetTableSchema(ctx context.Context, in *GetTableSchemaRequest, opts ...grpc.CallOption) (*GetTableSchemaResponse, error)
	GetTableStats(ctx context.Context, in *GetTableStatsRequest, opts ...grpc.CallOption) (*GetTableStatsResponse, error)
	// ========== 视图管理 ==========
	CreateView(ctx context.Context, in *CreateViewRequest, opts ...grpc.CallOption) (*CreateViewResponse, error)
	ListViews(ctx context.Context, in *ListViewsRequest, opts ...grpc.CallOption) (*ListViewsResponse, error)
	DropView(ctx context.Context, in *DropViewRequest, opts ...grpc.CallOption) (*DropViewResponse, error)
	// ========== 数据导入/导出 ==========
	// 从 MinIO 导入数据
	ImportFromMinIO(ctx context.Context, in *ImportFromMinIORequest, opts ...grpc.CallOption) (*ImportFromMinIOResponse, error)
	// 导出数据到 MinIO
	ExportToMinIO(ctx context.Context, in *ExportToMinIORequest, opts ...grpc.CallOption) (*ExportToMinIOResponse, error)
	// 直接查询 MinIO 中的文件（无需导入）
	QueryMinIOFile(ctx context.Context, in *QueryMinIOFileRequest, opts ...grpc.CallOption) (*QueryMinIOFileResponse, error)
	// 流式导入数据
	ImportData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportDataRequest, ImportDataResponse], error)
	// ========== 扩展和函数 ==========
	InstallExtension(ctx context.Context, in *InstallExtensionRequest, opts ...grpc.CallOption) (*InstallExtensionResponse, error)
	ListExtensions(ctx context.Context, in *ListExtensionsRequest, opts ...grpc.CallOption) (*ListExtensionsResponse, error)
	CreateFunction(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*CreateFunctionResponse, error)
	// ========== 健康检查和监控 ==========
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
	GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error)
}

type duckDBServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDuckDBServiceClient(cc grpc.ClientConnInterface) DuckDBServiceClient {
	return &duckDBServiceClient{cc}
}

func (c *duckDBServiceClient) CreateDatabase(ctx context.Context, in *CreateDatabaseRequest, opts ...grpc.CallOption) (*CreateDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDatabaseResponse)
	err := c.cc.Invoke(ctx, DuckDBService_CreateDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ListDatabases(ctx context.Context, in *ListDatabasesRequest, opts ...grpc.CallOption) (*ListDatabasesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatabasesResponse)
	err := c.cc.Invoke(ctx, DuckDBService_ListDatabases_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) DeleteDatabase(ctx context.Context, in *DeleteDatabaseRequest, opts ...grpc.CallOption) (*DeleteDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDatabaseResponse)
	err := c.cc.Invoke(ctx, DuckDBService_DeleteDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) GetDatabaseInfo(ctx context.Context, in *GetDatabaseInfoRequest, opts ...grpc.CallOption) (*GetDatabaseInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDatabaseInfoResponse)
	err := c.cc.Invoke(ctx, DuckDBService_GetDatabaseInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) BackupDatabase(ctx context.Context, in *BackupDatabaseRequest, opts ...grpc.CallOption) (*BackupDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BackupDatabaseResponse)
	err := c.cc.Invoke(ctx, DuckDBService_BackupDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) RestoreDatabase(ctx context.Context, in *RestoreDatabaseRequest, opts ...grpc.CallOption) (*RestoreDatabaseResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreDatabaseResponse)
	err := c.cc.Invoke(ctx, DuckDBService_RestoreDatabase_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ExecuteQuery(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (*ExecuteQueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteQueryResponse)
	err := c.cc.Invoke(ctx, DuckDBService_ExecuteQuery_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ExecuteQueryStream(ctx context.Context, in *ExecuteQueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultChunk], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DuckDBService_ServiceDesc.Streams[0], DuckDBService_ExecuteQueryStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecuteQueryRequest, QueryResultChunk]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DuckDBService_ExecuteQueryStreamClient = grpc.ServerStreamingClient[QueryResultChunk]

func (c *duckDBServiceClient) ExecuteStatement(ctx context.Context, in *ExecuteStatementRequest, opts ...grpc.CallOption) (*ExecuteStatementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteStatementResponse)
	err := c.cc.Invoke(ctx, DuckDBService_ExecuteStatement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ExecuteBatch(ctx context.Context, in *ExecuteBatchRequest, opts ...grpc.CallOption) (*ExecuteBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExecuteBatchResponse)
	err := c.cc.Invoke(ctx, DuckDBService_ExecuteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) PrepareStatement(ctx context.Context, in *PrepareStatementRequest, opts ...grpc.CallOption) (*PrepareStatementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PrepareStatementResponse)
	err := c.cc.Invoke(ctx, DuckDBService_PrepareStatement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) CreateTable(ctx context.Context, in *CreateTableRequest, opts ...grpc.CallOption) (*CreateTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateTableResponse)
	err := c.cc.Invoke(ctx, DuckDBService_CreateTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTablesResponse)
	err := c.cc.Invoke(ctx, DuckDBService_ListTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropTableResponse)
	err := c.cc.Invoke(ctx, DuckDBService_DropTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) GetTableSchema(ctx context.Context, in *GetTableSchemaRequest, opts ...grpc.CallOption) (*GetTableSchemaResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableSchemaResponse)
	err := c.cc.Invoke(ctx, DuckDBService_GetTableSchema_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) GetTableStats(ctx context.Context, in *GetTableStatsRequest, opts ...grpc.CallOption) (*GetTableStatsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTableStatsResponse)
	err := c.cc.Invoke(ctx, DuckDBService_GetTableStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) CreateView(ctx context.Context, in *CreateViewRequest, opts ...grpc.CallOption) (*CreateViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateViewResponse)
	err := c.cc.Invoke(ctx, DuckDBService_CreateView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ListViews(ctx context.Context, in *ListViewsRequest, opts ...grpc.CallOption) (*ListViewsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListViewsResponse)
	err := c.cc.Invoke(ctx, DuckDBService_ListViews_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) DropView(ctx context.Context, in *DropViewRequest, opts ...grpc.CallOption) (*DropViewResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropViewResponse)
	err := c.cc.Invoke(ctx, DuckDBService_DropView_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ImportFromMinIO(ctx context.Context, in *ImportFromMinIORequest, opts ...grpc.CallOption) (*ImportFromMinIOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ImportFromMinIOResponse)
	err := c.cc.Invoke(ctx, DuckDBService_ImportFromMinIO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ExportToMinIO(ctx context.Context, in *ExportToMinIORequest, opts ...grpc.CallOption) (*ExportToMinIOResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExportToMinIOResponse)
	err := c.cc.Invoke(ctx, DuckDBService_ExportToMinIO_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) QueryMinIOFile(ctx context.Context, in *QueryMinIOFileRequest, opts ...grpc.CallOption) (*QueryMinIOFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryMinIOFileResponse)
	err := c.cc.Invoke(ctx, DuckDBService_QueryMinIOFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ImportData(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[ImportDataRequest, ImportDataResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &DuckDBService_ServiceDesc.Streams[1], DuckDBService_ImportData_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ImportDataRequest, ImportDataResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DuckDBService_ImportDataClient = grpc.ClientStreamingClient[ImportDataRequest, ImportDataResponse]

func (c *duckDBServiceClient) InstallExtension(ctx context.Context, in *InstallExtensionRequest, opts ...grpc.CallOption) (*InstallExtensionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstallExtensionResponse)
	err := c.cc.Invoke(ctx, DuckDBService_InstallExtension_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) ListExtensions(ctx context.Context, in *ListExtensionsRequest, opts ...grpc.CallOption) (*ListExtensionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListExtensionsResponse)
	err := c.cc.Invoke(ctx, DuckDBService_ListExtensions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) CreateFunction(ctx context.Context, in *CreateFunctionRequest, opts ...grpc.CallOption) (*CreateFunctionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateFunctionResponse)
	err := c.cc.Invoke(ctx, DuckDBService_CreateFunction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, DuckDBService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *duckDBServiceClient) GetMetrics(ctx context.Context, in *GetMetricsRequest, opts ...grpc.CallOption) (*GetMetricsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMetricsResponse)
	err := c.cc.Invoke(ctx, DuckDBService_GetMetrics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DuckDBServiceServer is the server API for DuckDBService service.
// All implementations must embed UnimplementedDuckDBServiceServer
// for forward compatibility.
type DuckDBServiceServer interface {
	// ========== 数据库管理 ==========
	CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error)
	ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error)
	DeleteDatabase(context.Context, *DeleteDatabaseRequest) (*DeleteDatabaseResponse, error)
	GetDatabaseInfo(context.Context, *GetDatabaseInfoRequest) (*GetDatabaseInfoResponse, error)
	BackupDatabase(context.Context, *BackupDatabaseRequest) (*BackupDatabaseResponse, error)
	RestoreDatabase(context.Context, *RestoreDatabaseRequest) (*RestoreDatabaseResponse, error)
	// ========== 查询操作 ==========
	// 执行 SQL 查询（返回完整结果）
	ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error)
	// 流式查询（适合大结果集）
	ExecuteQueryStream(*ExecuteQueryRequest, grpc.ServerStreamingServer[QueryResultChunk]) error
	// 执行写操作（INSERT、UPDATE、DELETE）
	ExecuteStatement(context.Context, *ExecuteStatementRequest) (*ExecuteStatementResponse, error)
	// 批量执行 SQL
	ExecuteBatch(context.Context, *ExecuteBatchRequest) (*ExecuteBatchResponse, error)
	// 准备预编译语句
	PrepareStatement(context.Context, *PrepareStatementRequest) (*PrepareStatementResponse, error)
	// ========== 表管理 ==========
	CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error)
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error)
	GetTableSchema(context.Context, *GetTableSchemaRequest) (*GetTableSchemaResponse, error)
	GetTableStats(context.Context, *GetTableStatsRequest) (*GetTableStatsResponse, error)
	// ========== 视图管理 ==========
	CreateView(context.Context, *CreateViewRequest) (*CreateViewResponse, error)
	ListViews(context.Context, *ListViewsRequest) (*ListViewsResponse, error)
	DropView(context.Context, *DropViewRequest) (*DropViewResponse, error)
	// ========== 数据导入/导出 ==========
	// 从 MinIO 导入数据
	ImportFromMinIO(context.Context, *ImportFromMinIORequest) (*ImportFromMinIOResponse, error)
	// 导出数据到 MinIO
	ExportToMinIO(context.Context, *ExportToMinIORequest) (*ExportToMinIOResponse, error)
	// 直接查询 MinIO 中的文件（无需导入）
	QueryMinIOFile(context.Context, *QueryMinIOFileRequest) (*QueryMinIOFileResponse, error)
	// 流式导入数据
	ImportData(grpc.ClientStreamingServer[ImportDataRequest, ImportDataResponse]) error
	// ========== 扩展和函数 ==========
	InstallExtension(context.Context, *InstallExtensionRequest) (*InstallExtensionResponse, error)
	ListExtensions(context.Context, *ListExtensionsRequest) (*ListExtensionsResponse, error)
	CreateFunction(context.Context, *CreateFunctionRequest) (*CreateFunctionResponse, error)
	// ========== 健康检查和监控 ==========
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error)
	mustEmbedUnimplementedDuckDBServiceServer()
}

// UnimplementedDuckDBServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDuckDBServiceServer struct{}

func (UnimplementedDuckDBServiceServer) CreateDatabase(context.Context, *CreateDatabaseRequest) (*CreateDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDatabase not implemented")
}
func (UnimplementedDuckDBServiceServer) ListDatabases(context.Context, *ListDatabasesRequest) (*ListDatabasesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDatabases not implemented")
}
func (UnimplementedDuckDBServiceServer) DeleteDatabase(context.Context, *DeleteDatabaseRequest) (*DeleteDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDatabase not implemented")
}
func (UnimplementedDuckDBServiceServer) GetDatabaseInfo(context.Context, *GetDatabaseInfoRequest) (*GetDatabaseInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetDatabaseInfo not implemented")
}
func (UnimplementedDuckDBServiceServer) BackupDatabase(context.Context, *BackupDatabaseRequest) (*BackupDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BackupDatabase not implemented")
}
func (UnimplementedDuckDBServiceServer) RestoreDatabase(context.Context, *RestoreDatabaseRequest) (*RestoreDatabaseResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RestoreDatabase not implemented")
}
func (UnimplementedDuckDBServiceServer) ExecuteQuery(context.Context, *ExecuteQueryRequest) (*ExecuteQueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedDuckDBServiceServer) ExecuteQueryStream(*ExecuteQueryRequest, grpc.ServerStreamingServer[QueryResultChunk]) error {
	return status.Errorf(codes.Unimplemented, "method ExecuteQueryStream not implemented")
}
func (UnimplementedDuckDBServiceServer) ExecuteStatement(context.Context, *ExecuteStatementRequest) (*ExecuteStatementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteStatement not implemented")
}
func (UnimplementedDuckDBServiceServer) ExecuteBatch(context.Context, *ExecuteBatchRequest) (*ExecuteBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteBatch not implemented")
}
func (UnimplementedDuckDBServiceServer) PrepareStatement(context.Context, *PrepareStatementRequest) (*PrepareStatementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PrepareStatement not implemented")
}
func (UnimplementedDuckDBServiceServer) CreateTable(context.Context, *CreateTableRequest) (*CreateTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateTable not implemented")
}
func (UnimplementedDuckDBServiceServer) ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListTables not implemented")
}
func (UnimplementedDuckDBServiceServer) DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropTable not implemented")
}
func (UnimplementedDuckDBServiceServer) GetTableSchema(context.Context, *GetTableSchemaRequest) (*GetTableSchemaResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableSchema not implemented")
}
func (UnimplementedDuckDBServiceServer) GetTableStats(context.Context, *GetTableStatsRequest) (*GetTableStatsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTableStats not implemented")
}
func (UnimplementedDuckDBServiceServer) CreateView(context.Context, *CreateViewRequest) (*CreateViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateView not implemented")
}
func (UnimplementedDuckDBServiceServer) ListViews(context.Context, *ListViewsRequest) (*ListViewsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListViews not implemented")
}
func (UnimplementedDuckDBServiceServer) DropView(context.Context, *DropViewRequest) (*DropViewResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DropView not implemented")
}
func (UnimplementedDuckDBServiceServer) ImportFromMinIO(context.Context, *ImportFromMinIORequest) (*ImportFromMinIOResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ImportFromMinIO not implemented")
}
func (UnimplementedDuckDBServiceServer) ExportToMinIO(context.Context, *ExportToMinIORequest) (*ExportToMinIOResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExportToMinIO not implemented")
}
func (UnimplementedDuckDBServiceServer) QueryMinIOFile(context.Context, *QueryMinIOFileRequest) (*QueryMinIOFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMinIOFile not implemented")
}
func (UnimplementedDuckDBServiceServer) ImportData(grpc.ClientStreamingServer[ImportDataRequest, ImportDataResponse]) error {
	return status.Errorf(codes.Unimplemented, "method ImportData not implemented")
}
func (UnimplementedDuckDBServiceServer) InstallExtension(context.Context, *InstallExtensionRequest) (*InstallExtensionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method InstallExtension not implemented")
}
func (UnimplementedDuckDBServiceServer) ListExtensions(context.Context, *ListExtensionsRequest) (*ListExtensionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListExtensions not implemented")
}
func (UnimplementedDuckDBServiceServer) CreateFunction(context.Context, *CreateFunctionRequest) (*CreateFunctionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateFunction not implemented")
}
func (UnimplementedDuckDBServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedDuckDBServiceServer) GetMetrics(context.Context, *GetMetricsRequest) (*GetMetricsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMetrics not implemented")
}
func (UnimplementedDuckDBServiceServer) mustEmbedUnimplementedDuckDBServiceServer() {}
func (UnimplementedDuckDBServiceServer) testEmbeddedByValue()                       {}

// UnsafeDuckDBServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DuckDBServiceServer will
// result in compilation errors.
type UnsafeDuckDBServiceServer interface {
	mustEmbedUnimplementedDuckDBServiceServer()
}

func RegisterDuckDBServiceServer(s grpc.ServiceRegistrar, srv DuckDBServiceServer) {
	// If the following call pancis, it indicates UnimplementedDuckDBServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DuckDBService_ServiceDesc, srv)
}

func _DuckDBService_CreateDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).CreateDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_CreateDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).CreateDatabase(ctx, req.(*CreateDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ListDatabases_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatabasesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).ListDatabases(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_ListDatabases_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).ListDatabases(ctx, req.(*ListDatabasesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_DeleteDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).DeleteDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_DeleteDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).DeleteDatabase(ctx, req.(*DeleteDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_GetDatabaseInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDatabaseInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).GetDatabaseInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_GetDatabaseInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).GetDatabaseInfo(ctx, req.(*GetDatabaseInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_BackupDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BackupDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).BackupDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_BackupDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).BackupDatabase(ctx, req.(*BackupDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_RestoreDatabase_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreDatabaseRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).RestoreDatabase(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_RestoreDatabase_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).RestoreDatabase(ctx, req.(*RestoreDatabaseRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ExecuteQuery_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteQueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).ExecuteQuery(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_ExecuteQuery_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).ExecuteQuery(ctx, req.(*ExecuteQueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ExecuteQueryStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecuteQueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(DuckDBServiceServer).ExecuteQueryStream(m, &grpc.GenericServerStream[ExecuteQueryRequest, QueryResultChunk]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DuckDBService_ExecuteQueryStreamServer = grpc.ServerStreamingServer[QueryResultChunk]

func _DuckDBService_ExecuteStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).ExecuteStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_ExecuteStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).ExecuteStatement(ctx, req.(*ExecuteStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ExecuteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExecuteBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).ExecuteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_ExecuteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).ExecuteBatch(ctx, req.(*ExecuteBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_PrepareStatement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PrepareStatementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).PrepareStatement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_PrepareStatement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).PrepareStatement(ctx, req.(*PrepareStatementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_CreateTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).CreateTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_CreateTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).CreateTable(ctx, req.(*CreateTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_ListTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_DropTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).DropTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_DropTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).DropTable(ctx, req.(*DropTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_GetTableSchema_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableSchemaRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).GetTableSchema(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_GetTableSchema_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).GetTableSchema(ctx, req.(*GetTableSchemaRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_GetTableStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTableStatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).GetTableStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_GetTableStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).GetTableStats(ctx, req.(*GetTableStatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_CreateView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).CreateView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_CreateView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).CreateView(ctx, req.(*CreateViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ListViews_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListViewsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).ListViews(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_ListViews_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).ListViews(ctx, req.(*ListViewsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_DropView_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropViewRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).DropView(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_DropView_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).DropView(ctx, req.(*DropViewRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ImportFromMinIO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ImportFromMinIORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).ImportFromMinIO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_ImportFromMinIO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).ImportFromMinIO(ctx, req.(*ImportFromMinIORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ExportToMinIO_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExportToMinIORequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).ExportToMinIO(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_ExportToMinIO_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).ExportToMinIO(ctx, req.(*ExportToMinIORequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_QueryMinIOFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMinIOFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).QueryMinIOFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_QueryMinIOFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).QueryMinIOFile(ctx, req.(*QueryMinIOFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ImportData_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(DuckDBServiceServer).ImportData(&grpc.GenericServerStream[ImportDataRequest, ImportDataResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type DuckDBService_ImportDataServer = grpc.ClientStreamingServer[ImportDataRequest, ImportDataResponse]

func _DuckDBService_InstallExtension_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstallExtensionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).InstallExtension(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_InstallExtension_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).InstallExtension(ctx, req.(*InstallExtensionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_ListExtensions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListExtensionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).ListExtensions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_ListExtensions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).ListExtensions(ctx, req.(*ListExtensionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_CreateFunction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateFunctionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).CreateFunction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_CreateFunction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).CreateFunction(ctx, req.(*CreateFunctionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _DuckDBService_GetMetrics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMetricsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DuckDBServiceServer).GetMetrics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DuckDBService_GetMetrics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DuckDBServiceServer).GetMetrics(ctx, req.(*GetMetricsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// DuckDBService_ServiceDesc is the grpc.ServiceDesc for DuckDBService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DuckDBService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "isa.duckdb.DuckDBService",
	HandlerType: (*DuckDBServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateDatabase",
			Handler:    _DuckDBService_CreateDatabase_Handler,
		},
		{
			MethodName: "ListDatabases",
			Handler:    _DuckDBService_ListDatabases_Handler,
		},
		{
			MethodName: "DeleteDatabase",
			Handler:    _DuckDBService_DeleteDatabase_Handler,
		},
		{
			MethodName: "GetDatabaseInfo",
			Handler:    _DuckDBService_GetDatabaseInfo_Handler,
		},
		{
			MethodName: "BackupDatabase",
			Handler:    _DuckDBService_BackupDatabase_Handler,
		},
		{
			MethodName: "RestoreDatabase",
			Handler:    _DuckDBService_RestoreDatabase_Handler,
		},
		{
			MethodName: "ExecuteQuery",
			Handler:    _DuckDBService_ExecuteQuery_Handler,
		},
		{
			MethodName: "ExecuteStatement",
			Handler:    _DuckDBService_ExecuteStatement_Handler,
		},
		{
			MethodName: "ExecuteBatch",
			Handler:    _DuckDBService_ExecuteBatch_Handler,
		},
		{
			MethodName: "PrepareStatement",
			Handler:    _DuckDBService_PrepareStatement_Handler,
		},
		{
			MethodName: "CreateTable",
			Handler:    _DuckDBService_CreateTable_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _DuckDBService_ListTables_Handler,
		},
		{
			MethodName: "DropTable",
			Handler:    _DuckDBService_DropTable_Handler,
		},
		{
			MethodName: "GetTableSchema",
			Handler:    _DuckDBService_GetTableSchema_Handler,
		},
		{
			MethodName: "GetTableStats",
			Handler:    _DuckDBService_GetTableStats_Handler,
		},
		{
			MethodName: "CreateView",
			Handler:    _DuckDBService_CreateView_Handler,
		},
		{
			MethodName: "ListViews",
			Handler:    _DuckDBService_ListViews_Handler,
		},
		{
			MethodName: "DropView",
			Handler:    _DuckDBService_DropView_Handler,
		},
		{
			MethodName: "ImportFromMinIO",
			Handler:    _DuckDBService_ImportFromMinIO_Handler,
		},
		{
			MethodName: "ExportToMinIO",
			Handler:    _DuckDBService_ExportToMinIO_Handler,
		},
		{
			MethodName: "QueryMinIOFile",
			Handler:    _DuckDBService_QueryMinIOFile_Handler,
		},
		{
			MethodName: "InstallExtension",
			Handler:    _DuckDBService_InstallExtension_Handler,
		},
		{
			MethodName: "ListExtensions",
			Handler:    _DuckDBService_ListExtensions_Handler,
		},
		{
			MethodName: "CreateFunction",
			Handler:    _DuckDBService_CreateFunction_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _DuckDBService_HealthCheck_Handler,
		},
		{
			MethodName: "GetMetrics",
			Handler:    _DuckDBService_GetMetrics_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteQueryStream",
			Handler:       _DuckDBService_ExecuteQueryStream_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ImportData",
			Handler:       _DuckDBService_ImportData_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "duckdb_service.proto",
}
