// redis_service.proto - Redis 缓存服务 gRPC 接口
// 提供统一的缓存和会话存储接口，支持多租户和命名空间隔离

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: redis_service.proto

package redis

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RedisService_Set_FullMethodName               = "/isa.redis.RedisService/Set"
	RedisService_Get_FullMethodName               = "/isa.redis.RedisService/Get"
	RedisService_GetMultiple_FullMethodName       = "/isa.redis.RedisService/GetMultiple"
	RedisService_SetWithExpiration_FullMethodName = "/isa.redis.RedisService/SetWithExpiration"
	RedisService_Increment_FullMethodName         = "/isa.redis.RedisService/Increment"
	RedisService_Decrement_FullMethodName         = "/isa.redis.RedisService/Decrement"
	RedisService_Append_FullMethodName            = "/isa.redis.RedisService/Append"
	RedisService_Delete_FullMethodName            = "/isa.redis.RedisService/Delete"
	RedisService_DeleteMultiple_FullMethodName    = "/isa.redis.RedisService/DeleteMultiple"
	RedisService_Exists_FullMethodName            = "/isa.redis.RedisService/Exists"
	RedisService_Expire_FullMethodName            = "/isa.redis.RedisService/Expire"
	RedisService_GetTTL_FullMethodName            = "/isa.redis.RedisService/GetTTL"
	RedisService_Rename_FullMethodName            = "/isa.redis.RedisService/Rename"
	RedisService_ListKeys_FullMethodName          = "/isa.redis.RedisService/ListKeys"
	RedisService_HSet_FullMethodName              = "/isa.redis.RedisService/HSet"
	RedisService_HGet_FullMethodName              = "/isa.redis.RedisService/HGet"
	RedisService_HGetAll_FullMethodName           = "/isa.redis.RedisService/HGetAll"
	RedisService_HDelete_FullMethodName           = "/isa.redis.RedisService/HDelete"
	RedisService_HExists_FullMethodName           = "/isa.redis.RedisService/HExists"
	RedisService_HKeys_FullMethodName             = "/isa.redis.RedisService/HKeys"
	RedisService_HValues_FullMethodName           = "/isa.redis.RedisService/HValues"
	RedisService_HIncrement_FullMethodName        = "/isa.redis.RedisService/HIncrement"
	RedisService_LPush_FullMethodName             = "/isa.redis.RedisService/LPush"
	RedisService_RPush_FullMethodName             = "/isa.redis.RedisService/RPush"
	RedisService_LPop_FullMethodName              = "/isa.redis.RedisService/LPop"
	RedisService_RPop_FullMethodName              = "/isa.redis.RedisService/RPop"
	RedisService_LRange_FullMethodName            = "/isa.redis.RedisService/LRange"
	RedisService_LLen_FullMethodName              = "/isa.redis.RedisService/LLen"
	RedisService_LIndex_FullMethodName            = "/isa.redis.RedisService/LIndex"
	RedisService_LTrim_FullMethodName             = "/isa.redis.RedisService/LTrim"
	RedisService_SAdd_FullMethodName              = "/isa.redis.RedisService/SAdd"
	RedisService_SRemove_FullMethodName           = "/isa.redis.RedisService/SRemove"
	RedisService_SMembers_FullMethodName          = "/isa.redis.RedisService/SMembers"
	RedisService_SIsMember_FullMethodName         = "/isa.redis.RedisService/SIsMember"
	RedisService_SCard_FullMethodName             = "/isa.redis.RedisService/SCard"
	RedisService_SUnion_FullMethodName            = "/isa.redis.RedisService/SUnion"
	RedisService_SInter_FullMethodName            = "/isa.redis.RedisService/SInter"
	RedisService_SDiff_FullMethodName             = "/isa.redis.RedisService/SDiff"
	RedisService_ZAdd_FullMethodName              = "/isa.redis.RedisService/ZAdd"
	RedisService_ZRemove_FullMethodName           = "/isa.redis.RedisService/ZRemove"
	RedisService_ZRange_FullMethodName            = "/isa.redis.RedisService/ZRange"
	RedisService_ZRangeByScore_FullMethodName     = "/isa.redis.RedisService/ZRangeByScore"
	RedisService_ZRank_FullMethodName             = "/isa.redis.RedisService/ZRank"
	RedisService_ZScore_FullMethodName            = "/isa.redis.RedisService/ZScore"
	RedisService_ZCard_FullMethodName             = "/isa.redis.RedisService/ZCard"
	RedisService_ZIncrement_FullMethodName        = "/isa.redis.RedisService/ZIncrement"
	RedisService_AcquireLock_FullMethodName       = "/isa.redis.RedisService/AcquireLock"
	RedisService_ReleaseLock_FullMethodName       = "/isa.redis.RedisService/ReleaseLock"
	RedisService_RenewLock_FullMethodName         = "/isa.redis.RedisService/RenewLock"
	RedisService_Publish_FullMethodName           = "/isa.redis.RedisService/Publish"
	RedisService_Subscribe_FullMethodName         = "/isa.redis.RedisService/Subscribe"
	RedisService_Unsubscribe_FullMethodName       = "/isa.redis.RedisService/Unsubscribe"
	RedisService_ExecuteBatch_FullMethodName      = "/isa.redis.RedisService/ExecuteBatch"
	RedisService_CreateSession_FullMethodName     = "/isa.redis.RedisService/CreateSession"
	RedisService_GetSession_FullMethodName        = "/isa.redis.RedisService/GetSession"
	RedisService_UpdateSession_FullMethodName     = "/isa.redis.RedisService/UpdateSession"
	RedisService_DeleteSession_FullMethodName     = "/isa.redis.RedisService/DeleteSession"
	RedisService_ListSessions_FullMethodName      = "/isa.redis.RedisService/ListSessions"
	RedisService_GetStatistics_FullMethodName     = "/isa.redis.RedisService/GetStatistics"
	RedisService_GetKeyInfo_FullMethodName        = "/isa.redis.RedisService/GetKeyInfo"
	RedisService_HealthCheck_FullMethodName       = "/isa.redis.RedisService/HealthCheck"
)

// RedisServiceClient is the client API for RedisService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RedisServiceClient interface {
	// ========== 字符串操作 (String Operations) ==========
	Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error)
	GetMultiple(ctx context.Context, in *GetMultipleRequest, opts ...grpc.CallOption) (*GetMultipleResponse, error)
	SetWithExpiration(ctx context.Context, in *SetWithExpirationRequest, opts ...grpc.CallOption) (*SetResponse, error)
	Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*IncrementResponse, error)
	Decrement(ctx context.Context, in *DecrementRequest, opts ...grpc.CallOption) (*DecrementResponse, error)
	Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error)
	// ========== 键操作 (Key Operations) ==========
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	DeleteMultiple(ctx context.Context, in *DeleteMultipleRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error)
	Expire(ctx context.Context, in *ExpireRequest, opts ...grpc.CallOption) (*ExpireResponse, error)
	GetTTL(ctx context.Context, in *GetTTLRequest, opts ...grpc.CallOption) (*GetTTLResponse, error)
	Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error)
	ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error)
	// ========== 哈希操作 (Hash Operations) ==========
	HSet(ctx context.Context, in *HSetRequest, opts ...grpc.CallOption) (*HSetResponse, error)
	HGet(ctx context.Context, in *HGetRequest, opts ...grpc.CallOption) (*HGetResponse, error)
	HGetAll(ctx context.Context, in *HGetAllRequest, opts ...grpc.CallOption) (*HGetAllResponse, error)
	HDelete(ctx context.Context, in *HDeleteRequest, opts ...grpc.CallOption) (*HDeleteResponse, error)
	HExists(ctx context.Context, in *HExistsRequest, opts ...grpc.CallOption) (*HExistsResponse, error)
	HKeys(ctx context.Context, in *HKeysRequest, opts ...grpc.CallOption) (*HKeysResponse, error)
	HValues(ctx context.Context, in *HValuesRequest, opts ...grpc.CallOption) (*HValuesResponse, error)
	HIncrement(ctx context.Context, in *HIncrementRequest, opts ...grpc.CallOption) (*HIncrementResponse, error)
	// ========== 列表操作 (List Operations) ==========
	LPush(ctx context.Context, in *LPushRequest, opts ...grpc.CallOption) (*LPushResponse, error)
	RPush(ctx context.Context, in *RPushRequest, opts ...grpc.CallOption) (*RPushResponse, error)
	LPop(ctx context.Context, in *LPopRequest, opts ...grpc.CallOption) (*LPopResponse, error)
	RPop(ctx context.Context, in *RPopRequest, opts ...grpc.CallOption) (*RPopResponse, error)
	LRange(ctx context.Context, in *LRangeRequest, opts ...grpc.CallOption) (*LRangeResponse, error)
	LLen(ctx context.Context, in *LLenRequest, opts ...grpc.CallOption) (*LLenResponse, error)
	LIndex(ctx context.Context, in *LIndexRequest, opts ...grpc.CallOption) (*LIndexResponse, error)
	LTrim(ctx context.Context, in *LTrimRequest, opts ...grpc.CallOption) (*LTrimResponse, error)
	// ========== 集合操作 (Set Operations) ==========
	SAdd(ctx context.Context, in *SAddRequest, opts ...grpc.CallOption) (*SAddResponse, error)
	SRemove(ctx context.Context, in *SRemoveRequest, opts ...grpc.CallOption) (*SRemoveResponse, error)
	SMembers(ctx context.Context, in *SMembersRequest, opts ...grpc.CallOption) (*SMembersResponse, error)
	SIsMember(ctx context.Context, in *SIsMemberRequest, opts ...grpc.CallOption) (*SIsMemberResponse, error)
	SCard(ctx context.Context, in *SCardRequest, opts ...grpc.CallOption) (*SCardResponse, error)
	SUnion(ctx context.Context, in *SUnionRequest, opts ...grpc.CallOption) (*SUnionResponse, error)
	SInter(ctx context.Context, in *SInterRequest, opts ...grpc.CallOption) (*SInterResponse, error)
	SDiff(ctx context.Context, in *SDiffRequest, opts ...grpc.CallOption) (*SDiffResponse, error)
	// ========== 有序集合操作 (Sorted Set Operations) ==========
	ZAdd(ctx context.Context, in *ZAddRequest, opts ...grpc.CallOption) (*ZAddResponse, error)
	ZRemove(ctx context.Context, in *ZRemoveRequest, opts ...grpc.CallOption) (*ZRemoveResponse, error)
	ZRange(ctx context.Context, in *ZRangeRequest, opts ...grpc.CallOption) (*ZRangeResponse, error)
	ZRangeByScore(ctx context.Context, in *ZRangeByScoreRequest, opts ...grpc.CallOption) (*ZRangeByScoreResponse, error)
	ZRank(ctx context.Context, in *ZRankRequest, opts ...grpc.CallOption) (*ZRankResponse, error)
	ZScore(ctx context.Context, in *ZScoreRequest, opts ...grpc.CallOption) (*ZScoreResponse, error)
	ZCard(ctx context.Context, in *ZCardRequest, opts ...grpc.CallOption) (*ZCardResponse, error)
	ZIncrement(ctx context.Context, in *ZIncrementRequest, opts ...grpc.CallOption) (*ZIncrementResponse, error)
	// ========== 分布式锁 (Distributed Lock) ==========
	AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error)
	ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error)
	RenewLock(ctx context.Context, in *RenewLockRequest, opts ...grpc.CallOption) (*RenewLockResponse, error)
	// ========== Pub/Sub ==========
	Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error)
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageResponse], error)
	Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error)
	// ========== 批量操作 (Batch Operations) ==========
	ExecuteBatch(ctx context.Context, in *RedisBatchRequest, opts ...grpc.CallOption) (*RedisBatchResponse, error)
	// ========== 会话管理 (Session Management) ==========
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error)
	GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error)
	DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error)
	ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error)
	// ========== 统计和监控 ==========
	GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error)
	GetKeyInfo(ctx context.Context, in *GetKeyInfoRequest, opts ...grpc.CallOption) (*GetKeyInfoResponse, error)
	// ========== 健康检查 ==========
	HealthCheck(ctx context.Context, in *RedisHealthCheckRequest, opts ...grpc.CallOption) (*RedisHealthCheckResponse, error)
}

type redisServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewRedisServiceClient(cc grpc.ClientConnInterface) RedisServiceClient {
	return &redisServiceClient{cc}
}

func (c *redisServiceClient) Set(ctx context.Context, in *SetRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, RedisService_Set_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Get(ctx context.Context, in *GetRequest, opts ...grpc.CallOption) (*GetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetResponse)
	err := c.cc.Invoke(ctx, RedisService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) GetMultiple(ctx context.Context, in *GetMultipleRequest, opts ...grpc.CallOption) (*GetMultipleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetMultipleResponse)
	err := c.cc.Invoke(ctx, RedisService_GetMultiple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) SetWithExpiration(ctx context.Context, in *SetWithExpirationRequest, opts ...grpc.CallOption) (*SetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetResponse)
	err := c.cc.Invoke(ctx, RedisService_SetWithExpiration_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Increment(ctx context.Context, in *IncrementRequest, opts ...grpc.CallOption) (*IncrementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IncrementResponse)
	err := c.cc.Invoke(ctx, RedisService_Increment_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Decrement(ctx context.Context, in *DecrementRequest, opts ...grpc.CallOption) (*DecrementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecrementResponse)
	err := c.cc.Invoke(ctx, RedisService_Decrement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Append(ctx context.Context, in *AppendRequest, opts ...grpc.CallOption) (*AppendResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendResponse)
	err := c.cc.Invoke(ctx, RedisService_Append_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, RedisService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) DeleteMultiple(ctx context.Context, in *DeleteMultipleRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, RedisService_DeleteMultiple_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Exists(ctx context.Context, in *ExistsRequest, opts ...grpc.CallOption) (*ExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExistsResponse)
	err := c.cc.Invoke(ctx, RedisService_Exists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Expire(ctx context.Context, in *ExpireRequest, opts ...grpc.CallOption) (*ExpireResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ExpireResponse)
	err := c.cc.Invoke(ctx, RedisService_Expire_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) GetTTL(ctx context.Context, in *GetTTLRequest, opts ...grpc.CallOption) (*GetTTLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetTTLResponse)
	err := c.cc.Invoke(ctx, RedisService_GetTTL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Rename(ctx context.Context, in *RenameRequest, opts ...grpc.CallOption) (*RenameResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenameResponse)
	err := c.cc.Invoke(ctx, RedisService_Rename_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ListKeys(ctx context.Context, in *ListKeysRequest, opts ...grpc.CallOption) (*ListKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListKeysResponse)
	err := c.cc.Invoke(ctx, RedisService_ListKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HSet(ctx context.Context, in *HSetRequest, opts ...grpc.CallOption) (*HSetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HSetResponse)
	err := c.cc.Invoke(ctx, RedisService_HSet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HGet(ctx context.Context, in *HGetRequest, opts ...grpc.CallOption) (*HGetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HGetResponse)
	err := c.cc.Invoke(ctx, RedisService_HGet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HGetAll(ctx context.Context, in *HGetAllRequest, opts ...grpc.CallOption) (*HGetAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HGetAllResponse)
	err := c.cc.Invoke(ctx, RedisService_HGetAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HDelete(ctx context.Context, in *HDeleteRequest, opts ...grpc.CallOption) (*HDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HDeleteResponse)
	err := c.cc.Invoke(ctx, RedisService_HDelete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HExists(ctx context.Context, in *HExistsRequest, opts ...grpc.CallOption) (*HExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HExistsResponse)
	err := c.cc.Invoke(ctx, RedisService_HExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HKeys(ctx context.Context, in *HKeysRequest, opts ...grpc.CallOption) (*HKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HKeysResponse)
	err := c.cc.Invoke(ctx, RedisService_HKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HValues(ctx context.Context, in *HValuesRequest, opts ...grpc.CallOption) (*HValuesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HValuesResponse)
	err := c.cc.Invoke(ctx, RedisService_HValues_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HIncrement(ctx context.Context, in *HIncrementRequest, opts ...grpc.CallOption) (*HIncrementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HIncrementResponse)
	err := c.cc.Invoke(ctx, RedisService_HIncrement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) LPush(ctx context.Context, in *LPushRequest, opts ...grpc.CallOption) (*LPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LPushResponse)
	err := c.cc.Invoke(ctx, RedisService_LPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) RPush(ctx context.Context, in *RPushRequest, opts ...grpc.CallOption) (*RPushResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RPushResponse)
	err := c.cc.Invoke(ctx, RedisService_RPush_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) LPop(ctx context.Context, in *LPopRequest, opts ...grpc.CallOption) (*LPopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LPopResponse)
	err := c.cc.Invoke(ctx, RedisService_LPop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) RPop(ctx context.Context, in *RPopRequest, opts ...grpc.CallOption) (*RPopResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RPopResponse)
	err := c.cc.Invoke(ctx, RedisService_RPop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) LRange(ctx context.Context, in *LRangeRequest, opts ...grpc.CallOption) (*LRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LRangeResponse)
	err := c.cc.Invoke(ctx, RedisService_LRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) LLen(ctx context.Context, in *LLenRequest, opts ...grpc.CallOption) (*LLenResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LLenResponse)
	err := c.cc.Invoke(ctx, RedisService_LLen_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) LIndex(ctx context.Context, in *LIndexRequest, opts ...grpc.CallOption) (*LIndexResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LIndexResponse)
	err := c.cc.Invoke(ctx, RedisService_LIndex_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) LTrim(ctx context.Context, in *LTrimRequest, opts ...grpc.CallOption) (*LTrimResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LTrimResponse)
	err := c.cc.Invoke(ctx, RedisService_LTrim_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) SAdd(ctx context.Context, in *SAddRequest, opts ...grpc.CallOption) (*SAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SAddResponse)
	err := c.cc.Invoke(ctx, RedisService_SAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) SRemove(ctx context.Context, in *SRemoveRequest, opts ...grpc.CallOption) (*SRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SRemoveResponse)
	err := c.cc.Invoke(ctx, RedisService_SRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) SMembers(ctx context.Context, in *SMembersRequest, opts ...grpc.CallOption) (*SMembersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SMembersResponse)
	err := c.cc.Invoke(ctx, RedisService_SMembers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) SIsMember(ctx context.Context, in *SIsMemberRequest, opts ...grpc.CallOption) (*SIsMemberResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SIsMemberResponse)
	err := c.cc.Invoke(ctx, RedisService_SIsMember_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) SCard(ctx context.Context, in *SCardRequest, opts ...grpc.CallOption) (*SCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SCardResponse)
	err := c.cc.Invoke(ctx, RedisService_SCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) SUnion(ctx context.Context, in *SUnionRequest, opts ...grpc.CallOption) (*SUnionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SUnionResponse)
	err := c.cc.Invoke(ctx, RedisService_SUnion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) SInter(ctx context.Context, in *SInterRequest, opts ...grpc.CallOption) (*SInterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SInterResponse)
	err := c.cc.Invoke(ctx, RedisService_SInter_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) SDiff(ctx context.Context, in *SDiffRequest, opts ...grpc.CallOption) (*SDiffResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SDiffResponse)
	err := c.cc.Invoke(ctx, RedisService_SDiff_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ZAdd(ctx context.Context, in *ZAddRequest, opts ...grpc.CallOption) (*ZAddResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZAddResponse)
	err := c.cc.Invoke(ctx, RedisService_ZAdd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ZRemove(ctx context.Context, in *ZRemoveRequest, opts ...grpc.CallOption) (*ZRemoveResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZRemoveResponse)
	err := c.cc.Invoke(ctx, RedisService_ZRemove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ZRange(ctx context.Context, in *ZRangeRequest, opts ...grpc.CallOption) (*ZRangeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZRangeResponse)
	err := c.cc.Invoke(ctx, RedisService_ZRange_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ZRangeByScore(ctx context.Context, in *ZRangeByScoreRequest, opts ...grpc.CallOption) (*ZRangeByScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZRangeByScoreResponse)
	err := c.cc.Invoke(ctx, RedisService_ZRangeByScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ZRank(ctx context.Context, in *ZRankRequest, opts ...grpc.CallOption) (*ZRankResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZRankResponse)
	err := c.cc.Invoke(ctx, RedisService_ZRank_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ZScore(ctx context.Context, in *ZScoreRequest, opts ...grpc.CallOption) (*ZScoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZScoreResponse)
	err := c.cc.Invoke(ctx, RedisService_ZScore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ZCard(ctx context.Context, in *ZCardRequest, opts ...grpc.CallOption) (*ZCardResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZCardResponse)
	err := c.cc.Invoke(ctx, RedisService_ZCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ZIncrement(ctx context.Context, in *ZIncrementRequest, opts ...grpc.CallOption) (*ZIncrementResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ZIncrementResponse)
	err := c.cc.Invoke(ctx, RedisService_ZIncrement_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) AcquireLock(ctx context.Context, in *AcquireLockRequest, opts ...grpc.CallOption) (*AcquireLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AcquireLockResponse)
	err := c.cc.Invoke(ctx, RedisService_AcquireLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ReleaseLock(ctx context.Context, in *ReleaseLockRequest, opts ...grpc.CallOption) (*ReleaseLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseLockResponse)
	err := c.cc.Invoke(ctx, RedisService_ReleaseLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) RenewLock(ctx context.Context, in *RenewLockRequest, opts ...grpc.CallOption) (*RenewLockResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RenewLockResponse)
	err := c.cc.Invoke(ctx, RedisService_RenewLock_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Publish(ctx context.Context, in *PublishRequest, opts ...grpc.CallOption) (*PublishResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PublishResponse)
	err := c.cc.Invoke(ctx, RedisService_Publish_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MessageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &RedisService_ServiceDesc.Streams[0], RedisService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, MessageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RedisService_SubscribeClient = grpc.ServerStreamingClient[MessageResponse]

func (c *redisServiceClient) Unsubscribe(ctx context.Context, in *UnsubscribeRequest, opts ...grpc.CallOption) (*UnsubscribeResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UnsubscribeResponse)
	err := c.cc.Invoke(ctx, RedisService_Unsubscribe_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ExecuteBatch(ctx context.Context, in *RedisBatchRequest, opts ...grpc.CallOption) (*RedisBatchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedisBatchResponse)
	err := c.cc.Invoke(ctx, RedisService_ExecuteBatch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateSessionResponse)
	err := c.cc.Invoke(ctx, RedisService_CreateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) GetSession(ctx context.Context, in *GetSessionRequest, opts ...grpc.CallOption) (*GetSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSessionResponse)
	err := c.cc.Invoke(ctx, RedisService_GetSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateSessionResponse)
	err := c.cc.Invoke(ctx, RedisService_UpdateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) DeleteSession(ctx context.Context, in *DeleteSessionRequest, opts ...grpc.CallOption) (*DeleteSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteSessionResponse)
	err := c.cc.Invoke(ctx, RedisService_DeleteSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) ListSessions(ctx context.Context, in *ListSessionsRequest, opts ...grpc.CallOption) (*ListSessionsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListSessionsResponse)
	err := c.cc.Invoke(ctx, RedisService_ListSessions_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) GetStatistics(ctx context.Context, in *GetStatisticsRequest, opts ...grpc.CallOption) (*GetStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetStatisticsResponse)
	err := c.cc.Invoke(ctx, RedisService_GetStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) GetKeyInfo(ctx context.Context, in *GetKeyInfoRequest, opts ...grpc.CallOption) (*GetKeyInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyInfoResponse)
	err := c.cc.Invoke(ctx, RedisService_GetKeyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *redisServiceClient) HealthCheck(ctx context.Context, in *RedisHealthCheckRequest, opts ...grpc.CallOption) (*RedisHealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RedisHealthCheckResponse)
	err := c.cc.Invoke(ctx, RedisService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RedisServiceServer is the server API for RedisService service.
// All implementations must embed UnimplementedRedisServiceServer
// for forward compatibility.
type RedisServiceServer interface {
	// ========== 字符串操作 (String Operations) ==========
	Set(context.Context, *SetRequest) (*SetResponse, error)
	Get(context.Context, *GetRequest) (*GetResponse, error)
	GetMultiple(context.Context, *GetMultipleRequest) (*GetMultipleResponse, error)
	SetWithExpiration(context.Context, *SetWithExpirationRequest) (*SetResponse, error)
	Increment(context.Context, *IncrementRequest) (*IncrementResponse, error)
	Decrement(context.Context, *DecrementRequest) (*DecrementResponse, error)
	Append(context.Context, *AppendRequest) (*AppendResponse, error)
	// ========== 键操作 (Key Operations) ==========
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	DeleteMultiple(context.Context, *DeleteMultipleRequest) (*DeleteResponse, error)
	Exists(context.Context, *ExistsRequest) (*ExistsResponse, error)
	Expire(context.Context, *ExpireRequest) (*ExpireResponse, error)
	GetTTL(context.Context, *GetTTLRequest) (*GetTTLResponse, error)
	Rename(context.Context, *RenameRequest) (*RenameResponse, error)
	ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error)
	// ========== 哈希操作 (Hash Operations) ==========
	HSet(context.Context, *HSetRequest) (*HSetResponse, error)
	HGet(context.Context, *HGetRequest) (*HGetResponse, error)
	HGetAll(context.Context, *HGetAllRequest) (*HGetAllResponse, error)
	HDelete(context.Context, *HDeleteRequest) (*HDeleteResponse, error)
	HExists(context.Context, *HExistsRequest) (*HExistsResponse, error)
	HKeys(context.Context, *HKeysRequest) (*HKeysResponse, error)
	HValues(context.Context, *HValuesRequest) (*HValuesResponse, error)
	HIncrement(context.Context, *HIncrementRequest) (*HIncrementResponse, error)
	// ========== 列表操作 (List Operations) ==========
	LPush(context.Context, *LPushRequest) (*LPushResponse, error)
	RPush(context.Context, *RPushRequest) (*RPushResponse, error)
	LPop(context.Context, *LPopRequest) (*LPopResponse, error)
	RPop(context.Context, *RPopRequest) (*RPopResponse, error)
	LRange(context.Context, *LRangeRequest) (*LRangeResponse, error)
	LLen(context.Context, *LLenRequest) (*LLenResponse, error)
	LIndex(context.Context, *LIndexRequest) (*LIndexResponse, error)
	LTrim(context.Context, *LTrimRequest) (*LTrimResponse, error)
	// ========== 集合操作 (Set Operations) ==========
	SAdd(context.Context, *SAddRequest) (*SAddResponse, error)
	SRemove(context.Context, *SRemoveRequest) (*SRemoveResponse, error)
	SMembers(context.Context, *SMembersRequest) (*SMembersResponse, error)
	SIsMember(context.Context, *SIsMemberRequest) (*SIsMemberResponse, error)
	SCard(context.Context, *SCardRequest) (*SCardResponse, error)
	SUnion(context.Context, *SUnionRequest) (*SUnionResponse, error)
	SInter(context.Context, *SInterRequest) (*SInterResponse, error)
	SDiff(context.Context, *SDiffRequest) (*SDiffResponse, error)
	// ========== 有序集合操作 (Sorted Set Operations) ==========
	ZAdd(context.Context, *ZAddRequest) (*ZAddResponse, error)
	ZRemove(context.Context, *ZRemoveRequest) (*ZRemoveResponse, error)
	ZRange(context.Context, *ZRangeRequest) (*ZRangeResponse, error)
	ZRangeByScore(context.Context, *ZRangeByScoreRequest) (*ZRangeByScoreResponse, error)
	ZRank(context.Context, *ZRankRequest) (*ZRankResponse, error)
	ZScore(context.Context, *ZScoreRequest) (*ZScoreResponse, error)
	ZCard(context.Context, *ZCardRequest) (*ZCardResponse, error)
	ZIncrement(context.Context, *ZIncrementRequest) (*ZIncrementResponse, error)
	// ========== 分布式锁 (Distributed Lock) ==========
	AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error)
	ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error)
	RenewLock(context.Context, *RenewLockRequest) (*RenewLockResponse, error)
	// ========== Pub/Sub ==========
	Publish(context.Context, *PublishRequest) (*PublishResponse, error)
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[MessageResponse]) error
	Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error)
	// ========== 批量操作 (Batch Operations) ==========
	ExecuteBatch(context.Context, *RedisBatchRequest) (*RedisBatchResponse, error)
	// ========== 会话管理 (Session Management) ==========
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error)
	GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error)
	DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error)
	ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error)
	// ========== 统计和监控 ==========
	GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error)
	GetKeyInfo(context.Context, *GetKeyInfoRequest) (*GetKeyInfoResponse, error)
	// ========== 健康检查 ==========
	HealthCheck(context.Context, *RedisHealthCheckRequest) (*RedisHealthCheckResponse, error)
	mustEmbedUnimplementedRedisServiceServer()
}

// UnimplementedRedisServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRedisServiceServer struct{}

func (UnimplementedRedisServiceServer) Set(context.Context, *SetRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Set not implemented")
}
func (UnimplementedRedisServiceServer) Get(context.Context, *GetRequest) (*GetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRedisServiceServer) GetMultiple(context.Context, *GetMultipleRequest) (*GetMultipleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMultiple not implemented")
}
func (UnimplementedRedisServiceServer) SetWithExpiration(context.Context, *SetWithExpirationRequest) (*SetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetWithExpiration not implemented")
}
func (UnimplementedRedisServiceServer) Increment(context.Context, *IncrementRequest) (*IncrementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Increment not implemented")
}
func (UnimplementedRedisServiceServer) Decrement(context.Context, *DecrementRequest) (*DecrementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Decrement not implemented")
}
func (UnimplementedRedisServiceServer) Append(context.Context, *AppendRequest) (*AppendResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Append not implemented")
}
func (UnimplementedRedisServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedRedisServiceServer) DeleteMultiple(context.Context, *DeleteMultipleRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteMultiple not implemented")
}
func (UnimplementedRedisServiceServer) Exists(context.Context, *ExistsRequest) (*ExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Exists not implemented")
}
func (UnimplementedRedisServiceServer) Expire(context.Context, *ExpireRequest) (*ExpireResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Expire not implemented")
}
func (UnimplementedRedisServiceServer) GetTTL(context.Context, *GetTTLRequest) (*GetTTLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTTL not implemented")
}
func (UnimplementedRedisServiceServer) Rename(context.Context, *RenameRequest) (*RenameResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Rename not implemented")
}
func (UnimplementedRedisServiceServer) ListKeys(context.Context, *ListKeysRequest) (*ListKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListKeys not implemented")
}
func (UnimplementedRedisServiceServer) HSet(context.Context, *HSetRequest) (*HSetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HSet not implemented")
}
func (UnimplementedRedisServiceServer) HGet(context.Context, *HGetRequest) (*HGetResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HGet not implemented")
}
func (UnimplementedRedisServiceServer) HGetAll(context.Context, *HGetAllRequest) (*HGetAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HGetAll not implemented")
}
func (UnimplementedRedisServiceServer) HDelete(context.Context, *HDeleteRequest) (*HDeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HDelete not implemented")
}
func (UnimplementedRedisServiceServer) HExists(context.Context, *HExistsRequest) (*HExistsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HExists not implemented")
}
func (UnimplementedRedisServiceServer) HKeys(context.Context, *HKeysRequest) (*HKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HKeys not implemented")
}
func (UnimplementedRedisServiceServer) HValues(context.Context, *HValuesRequest) (*HValuesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HValues not implemented")
}
func (UnimplementedRedisServiceServer) HIncrement(context.Context, *HIncrementRequest) (*HIncrementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HIncrement not implemented")
}
func (UnimplementedRedisServiceServer) LPush(context.Context, *LPushRequest) (*LPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LPush not implemented")
}
func (UnimplementedRedisServiceServer) RPush(context.Context, *RPushRequest) (*RPushResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPush not implemented")
}
func (UnimplementedRedisServiceServer) LPop(context.Context, *LPopRequest) (*LPopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LPop not implemented")
}
func (UnimplementedRedisServiceServer) RPop(context.Context, *RPopRequest) (*RPopResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RPop not implemented")
}
func (UnimplementedRedisServiceServer) LRange(context.Context, *LRangeRequest) (*LRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LRange not implemented")
}
func (UnimplementedRedisServiceServer) LLen(context.Context, *LLenRequest) (*LLenResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LLen not implemented")
}
func (UnimplementedRedisServiceServer) LIndex(context.Context, *LIndexRequest) (*LIndexResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LIndex not implemented")
}
func (UnimplementedRedisServiceServer) LTrim(context.Context, *LTrimRequest) (*LTrimResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method LTrim not implemented")
}
func (UnimplementedRedisServiceServer) SAdd(context.Context, *SAddRequest) (*SAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SAdd not implemented")
}
func (UnimplementedRedisServiceServer) SRemove(context.Context, *SRemoveRequest) (*SRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SRemove not implemented")
}
func (UnimplementedRedisServiceServer) SMembers(context.Context, *SMembersRequest) (*SMembersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SMembers not implemented")
}
func (UnimplementedRedisServiceServer) SIsMember(context.Context, *SIsMemberRequest) (*SIsMemberResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SIsMember not implemented")
}
func (UnimplementedRedisServiceServer) SCard(context.Context, *SCardRequest) (*SCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SCard not implemented")
}
func (UnimplementedRedisServiceServer) SUnion(context.Context, *SUnionRequest) (*SUnionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SUnion not implemented")
}
func (UnimplementedRedisServiceServer) SInter(context.Context, *SInterRequest) (*SInterResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SInter not implemented")
}
func (UnimplementedRedisServiceServer) SDiff(context.Context, *SDiffRequest) (*SDiffResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SDiff not implemented")
}
func (UnimplementedRedisServiceServer) ZAdd(context.Context, *ZAddRequest) (*ZAddResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZAdd not implemented")
}
func (UnimplementedRedisServiceServer) ZRemove(context.Context, *ZRemoveRequest) (*ZRemoveResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZRemove not implemented")
}
func (UnimplementedRedisServiceServer) ZRange(context.Context, *ZRangeRequest) (*ZRangeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZRange not implemented")
}
func (UnimplementedRedisServiceServer) ZRangeByScore(context.Context, *ZRangeByScoreRequest) (*ZRangeByScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZRangeByScore not implemented")
}
func (UnimplementedRedisServiceServer) ZRank(context.Context, *ZRankRequest) (*ZRankResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZRank not implemented")
}
func (UnimplementedRedisServiceServer) ZScore(context.Context, *ZScoreRequest) (*ZScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZScore not implemented")
}
func (UnimplementedRedisServiceServer) ZCard(context.Context, *ZCardRequest) (*ZCardResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZCard not implemented")
}
func (UnimplementedRedisServiceServer) ZIncrement(context.Context, *ZIncrementRequest) (*ZIncrementResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ZIncrement not implemented")
}
func (UnimplementedRedisServiceServer) AcquireLock(context.Context, *AcquireLockRequest) (*AcquireLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcquireLock not implemented")
}
func (UnimplementedRedisServiceServer) ReleaseLock(context.Context, *ReleaseLockRequest) (*ReleaseLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReleaseLock not implemented")
}
func (UnimplementedRedisServiceServer) RenewLock(context.Context, *RenewLockRequest) (*RenewLockResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewLock not implemented")
}
func (UnimplementedRedisServiceServer) Publish(context.Context, *PublishRequest) (*PublishResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Publish not implemented")
}
func (UnimplementedRedisServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[MessageResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedRedisServiceServer) Unsubscribe(context.Context, *UnsubscribeRequest) (*UnsubscribeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Unsubscribe not implemented")
}
func (UnimplementedRedisServiceServer) ExecuteBatch(context.Context, *RedisBatchRequest) (*RedisBatchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteBatch not implemented")
}
func (UnimplementedRedisServiceServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedRedisServiceServer) GetSession(context.Context, *GetSessionRequest) (*GetSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSession not implemented")
}
func (UnimplementedRedisServiceServer) UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedRedisServiceServer) DeleteSession(context.Context, *DeleteSessionRequest) (*DeleteSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteSession not implemented")
}
func (UnimplementedRedisServiceServer) ListSessions(context.Context, *ListSessionsRequest) (*ListSessionsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListSessions not implemented")
}
func (UnimplementedRedisServiceServer) GetStatistics(context.Context, *GetStatisticsRequest) (*GetStatisticsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetStatistics not implemented")
}
func (UnimplementedRedisServiceServer) GetKeyInfo(context.Context, *GetKeyInfoRequest) (*GetKeyInfoResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyInfo not implemented")
}
func (UnimplementedRedisServiceServer) HealthCheck(context.Context, *RedisHealthCheckRequest) (*RedisHealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedRedisServiceServer) mustEmbedUnimplementedRedisServiceServer() {}
func (UnimplementedRedisServiceServer) testEmbeddedByValue()                      {}

// UnsafeRedisServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RedisServiceServer will
// result in compilation errors.
type UnsafeRedisServiceServer interface {
	mustEmbedUnimplementedRedisServiceServer()
}

func RegisterRedisServiceServer(s grpc.ServiceRegistrar, srv RedisServiceServer) {
	// If the following call pancis, it indicates UnimplementedRedisServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RedisService_ServiceDesc, srv)
}

func _RedisService_Set_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Set(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Set_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Set(ctx, req.(*SetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Get(ctx, req.(*GetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_GetMultiple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMultipleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).GetMultiple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_GetMultiple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).GetMultiple(ctx, req.(*GetMultipleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_SetWithExpiration_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetWithExpirationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SetWithExpiration(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SetWithExpiration_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SetWithExpiration(ctx, req.(*SetWithExpirationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Increment_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IncrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Increment(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Increment_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Increment(ctx, req.(*IncrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Decrement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Decrement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Decrement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Decrement(ctx, req.(*DecrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Append_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Append(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Append_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Append(ctx, req.(*AppendRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_DeleteMultiple_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteMultipleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).DeleteMultiple(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_DeleteMultiple_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).DeleteMultiple(ctx, req.(*DeleteMultipleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Exists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Exists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Exists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Exists(ctx, req.(*ExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Expire_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ExpireRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Expire(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Expire_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Expire(ctx, req.(*ExpireRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_GetTTL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTTLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).GetTTL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_GetTTL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).GetTTL(ctx, req.(*GetTTLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Rename_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Rename(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Rename_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Rename(ctx, req.(*RenameRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ListKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ListKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ListKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ListKeys(ctx, req.(*ListKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HSet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HSetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HSet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_HSet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HSet(ctx, req.(*HSetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HGet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HGetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HGet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_HGet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HGet(ctx, req.(*HGetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HGetAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HGetAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HGetAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_HGetAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HGetAll(ctx, req.(*HGetAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HDelete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HDelete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_HDelete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HDelete(ctx, req.(*HDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_HExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HExists(ctx, req.(*HExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_HKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HKeys(ctx, req.(*HKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HValues_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HValuesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HValues(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_HValues_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HValues(ctx, req.(*HValuesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HIncrement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HIncrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HIncrement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_HIncrement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HIncrement(ctx, req.(*HIncrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_LPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).LPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_LPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).LPush(ctx, req.(*LPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_RPush_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPushRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).RPush(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_RPush_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).RPush(ctx, req.(*RPushRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_LPop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LPopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).LPop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_LPop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).LPop(ctx, req.(*LPopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_RPop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPopRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).RPop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_RPop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).RPop(ctx, req.(*RPopRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_LRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).LRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_LRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).LRange(ctx, req.(*LRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_LLen_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LLenRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).LLen(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_LLen_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).LLen(ctx, req.(*LLenRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_LIndex_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LIndexRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).LIndex(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_LIndex_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).LIndex(ctx, req.(*LIndexRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_LTrim_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LTrimRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).LTrim(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_LTrim_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).LTrim(ctx, req.(*LTrimRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_SAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SAdd(ctx, req.(*SAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_SRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SRemove(ctx, req.(*SRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_SMembers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SMembersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SMembers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SMembers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SMembers(ctx, req.(*SMembersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_SIsMember_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SIsMemberRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SIsMember(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SIsMember_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SIsMember(ctx, req.(*SIsMemberRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_SCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SCard(ctx, req.(*SCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_SUnion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SUnionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SUnion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SUnion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SUnion(ctx, req.(*SUnionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_SInter_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SInterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SInter(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SInter_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SInter(ctx, req.(*SInterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_SDiff_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SDiffRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).SDiff(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_SDiff_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).SDiff(ctx, req.(*SDiffRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ZAdd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZAddRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ZAdd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ZAdd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ZAdd(ctx, req.(*ZAddRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ZRemove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZRemoveRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ZRemove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ZRemove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ZRemove(ctx, req.(*ZRemoveRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ZRange_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZRangeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ZRange(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ZRange_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ZRange(ctx, req.(*ZRangeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ZRangeByScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZRangeByScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ZRangeByScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ZRangeByScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ZRangeByScore(ctx, req.(*ZRangeByScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ZRank_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZRankRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ZRank(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ZRank_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ZRank(ctx, req.(*ZRankRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ZScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ZScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ZScore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ZScore(ctx, req.(*ZScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ZCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZCardRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ZCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ZCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ZCard(ctx, req.(*ZCardRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ZIncrement_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ZIncrementRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ZIncrement(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ZIncrement_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ZIncrement(ctx, req.(*ZIncrementRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_AcquireLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AcquireLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).AcquireLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_AcquireLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).AcquireLock(ctx, req.(*AcquireLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ReleaseLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ReleaseLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ReleaseLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ReleaseLock(ctx, req.(*ReleaseLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_RenewLock_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewLockRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).RenewLock(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_RenewLock_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).RenewLock(ctx, req.(*RenewLockRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Publish_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PublishRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Publish(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Publish_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Publish(ctx, req.(*PublishRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(RedisServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, MessageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type RedisService_SubscribeServer = grpc.ServerStreamingServer[MessageResponse]

func _RedisService_Unsubscribe_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UnsubscribeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).Unsubscribe(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_Unsubscribe_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).Unsubscribe(ctx, req.(*UnsubscribeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ExecuteBatch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisBatchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ExecuteBatch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ExecuteBatch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ExecuteBatch(ctx, req.(*RedisBatchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_CreateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_GetSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).GetSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_GetSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).GetSession(ctx, req.(*GetSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_UpdateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_DeleteSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).DeleteSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_DeleteSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).DeleteSession(ctx, req.(*DeleteSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_ListSessions_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListSessionsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).ListSessions(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_ListSessions_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).ListSessions(ctx, req.(*ListSessionsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_GetStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).GetStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_GetStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).GetStatistics(ctx, req.(*GetStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_GetKeyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).GetKeyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_GetKeyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).GetKeyInfo(ctx, req.(*GetKeyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _RedisService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RedisHealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RedisServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RedisService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RedisServiceServer).HealthCheck(ctx, req.(*RedisHealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// RedisService_ServiceDesc is the grpc.ServiceDesc for RedisService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RedisService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "isa.redis.RedisService",
	HandlerType: (*RedisServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Set",
			Handler:    _RedisService_Set_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RedisService_Get_Handler,
		},
		{
			MethodName: "GetMultiple",
			Handler:    _RedisService_GetMultiple_Handler,
		},
		{
			MethodName: "SetWithExpiration",
			Handler:    _RedisService_SetWithExpiration_Handler,
		},
		{
			MethodName: "Increment",
			Handler:    _RedisService_Increment_Handler,
		},
		{
			MethodName: "Decrement",
			Handler:    _RedisService_Decrement_Handler,
		},
		{
			MethodName: "Append",
			Handler:    _RedisService_Append_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _RedisService_Delete_Handler,
		},
		{
			MethodName: "DeleteMultiple",
			Handler:    _RedisService_DeleteMultiple_Handler,
		},
		{
			MethodName: "Exists",
			Handler:    _RedisService_Exists_Handler,
		},
		{
			MethodName: "Expire",
			Handler:    _RedisService_Expire_Handler,
		},
		{
			MethodName: "GetTTL",
			Handler:    _RedisService_GetTTL_Handler,
		},
		{
			MethodName: "Rename",
			Handler:    _RedisService_Rename_Handler,
		},
		{
			MethodName: "ListKeys",
			Handler:    _RedisService_ListKeys_Handler,
		},
		{
			MethodName: "HSet",
			Handler:    _RedisService_HSet_Handler,
		},
		{
			MethodName: "HGet",
			Handler:    _RedisService_HGet_Handler,
		},
		{
			MethodName: "HGetAll",
			Handler:    _RedisService_HGetAll_Handler,
		},
		{
			MethodName: "HDelete",
			Handler:    _RedisService_HDelete_Handler,
		},
		{
			MethodName: "HExists",
			Handler:    _RedisService_HExists_Handler,
		},
		{
			MethodName: "HKeys",
			Handler:    _RedisService_HKeys_Handler,
		},
		{
			MethodName: "HValues",
			Handler:    _RedisService_HValues_Handler,
		},
		{
			MethodName: "HIncrement",
			Handler:    _RedisService_HIncrement_Handler,
		},
		{
			MethodName: "LPush",
			Handler:    _RedisService_LPush_Handler,
		},
		{
			MethodName: "RPush",
			Handler:    _RedisService_RPush_Handler,
		},
		{
			MethodName: "LPop",
			Handler:    _RedisService_LPop_Handler,
		},
		{
			MethodName: "RPop",
			Handler:    _RedisService_RPop_Handler,
		},
		{
			MethodName: "LRange",
			Handler:    _RedisService_LRange_Handler,
		},
		{
			MethodName: "LLen",
			Handler:    _RedisService_LLen_Handler,
		},
		{
			MethodName: "LIndex",
			Handler:    _RedisService_LIndex_Handler,
		},
		{
			MethodName: "LTrim",
			Handler:    _RedisService_LTrim_Handler,
		},
		{
			MethodName: "SAdd",
			Handler:    _RedisService_SAdd_Handler,
		},
		{
			MethodName: "SRemove",
			Handler:    _RedisService_SRemove_Handler,
		},
		{
			MethodName: "SMembers",
			Handler:    _RedisService_SMembers_Handler,
		},
		{
			MethodName: "SIsMember",
			Handler:    _RedisService_SIsMember_Handler,
		},
		{
			MethodName: "SCard",
			Handler:    _RedisService_SCard_Handler,
		},
		{
			MethodName: "SUnion",
			Handler:    _RedisService_SUnion_Handler,
		},
		{
			MethodName: "SInter",
			Handler:    _RedisService_SInter_Handler,
		},
		{
			MethodName: "SDiff",
			Handler:    _RedisService_SDiff_Handler,
		},
		{
			MethodName: "ZAdd",
			Handler:    _RedisService_ZAdd_Handler,
		},
		{
			MethodName: "ZRemove",
			Handler:    _RedisService_ZRemove_Handler,
		},
		{
			MethodName: "ZRange",
			Handler:    _RedisService_ZRange_Handler,
		},
		{
			MethodName: "ZRangeByScore",
			Handler:    _RedisService_ZRangeByScore_Handler,
		},
		{
			MethodName: "ZRank",
			Handler:    _RedisService_ZRank_Handler,
		},
		{
			MethodName: "ZScore",
			Handler:    _RedisService_ZScore_Handler,
		},
		{
			MethodName: "ZCard",
			Handler:    _RedisService_ZCard_Handler,
		},
		{
			MethodName: "ZIncrement",
			Handler:    _RedisService_ZIncrement_Handler,
		},
		{
			MethodName: "AcquireLock",
			Handler:    _RedisService_AcquireLock_Handler,
		},
		{
			MethodName: "ReleaseLock",
			Handler:    _RedisService_ReleaseLock_Handler,
		},
		{
			MethodName: "RenewLock",
			Handler:    _RedisService_RenewLock_Handler,
		},
		{
			MethodName: "Publish",
			Handler:    _RedisService_Publish_Handler,
		},
		{
			MethodName: "Unsubscribe",
			Handler:    _RedisService_Unsubscribe_Handler,
		},
		{
			MethodName: "ExecuteBatch",
			Handler:    _RedisService_ExecuteBatch_Handler,
		},
		{
			MethodName: "CreateSession",
			Handler:    _RedisService_CreateSession_Handler,
		},
		{
			MethodName: "GetSession",
			Handler:    _RedisService_GetSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _RedisService_UpdateSession_Handler,
		},
		{
			MethodName: "DeleteSession",
			Handler:    _RedisService_DeleteSession_Handler,
		},
		{
			MethodName: "ListSessions",
			Handler:    _RedisService_ListSessions_Handler,
		},
		{
			MethodName: "GetStatistics",
			Handler:    _RedisService_GetStatistics_Handler,
		},
		{
			MethodName: "GetKeyInfo",
			Handler:    _RedisService_GetKeyInfo_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _RedisService_HealthCheck_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _RedisService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "redis_service.proto",
}
