// supabase_service.proto - Supabase 数据库与向量服务 gRPC 接口
// 提供统一的 Supabase 访问能力，包括数据库操作和 pgvector 向量搜索

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: supabase_service.proto

package supabase

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SupabaseService_Query_FullMethodName                 = "/isa.supabase.SupabaseService/Query"
	SupabaseService_Insert_FullMethodName                = "/isa.supabase.SupabaseService/Insert"
	SupabaseService_Update_FullMethodName                = "/isa.supabase.SupabaseService/Update"
	SupabaseService_Delete_FullMethodName                = "/isa.supabase.SupabaseService/Delete"
	SupabaseService_Upsert_FullMethodName                = "/isa.supabase.SupabaseService/Upsert"
	SupabaseService_ExecuteRPC_FullMethodName            = "/isa.supabase.SupabaseService/ExecuteRPC"
	SupabaseService_UpsertEmbedding_FullMethodName       = "/isa.supabase.SupabaseService/UpsertEmbedding"
	SupabaseService_SimilaritySearch_FullMethodName      = "/isa.supabase.SupabaseService/SimilaritySearch"
	SupabaseService_HybridSearch_FullMethodName          = "/isa.supabase.SupabaseService/HybridSearch"
	SupabaseService_DeleteEmbedding_FullMethodName       = "/isa.supabase.SupabaseService/DeleteEmbedding"
	SupabaseService_BatchInsert_FullMethodName           = "/isa.supabase.SupabaseService/BatchInsert"
	SupabaseService_BatchUpsertEmbeddings_FullMethodName = "/isa.supabase.SupabaseService/BatchUpsertEmbeddings"
	SupabaseService_HealthCheck_FullMethodName           = "/isa.supabase.SupabaseService/HealthCheck"
)

// SupabaseServiceClient is the client API for SupabaseService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SupabaseServiceClient interface {
	// Query - 查询数据 (SELECT)
	Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error)
	// Insert - 插入数据
	Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error)
	// Update - 更新数据
	Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error)
	// Delete - 删除数据
	Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error)
	// Upsert - 插入或更新 (INSERT ON CONFLICT UPDATE)
	Upsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error)
	// RPC - 调用 PostgreSQL 函数/存储过程
	ExecuteRPC(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error)
	// UpsertEmbedding - 插入或更新向量嵌入
	UpsertEmbedding(ctx context.Context, in *UpsertEmbeddingRequest, opts ...grpc.CallOption) (*UpsertEmbeddingResponse, error)
	// SimilaritySearch - 向量相似度搜索
	SimilaritySearch(ctx context.Context, in *SimilaritySearchRequest, opts ...grpc.CallOption) (*SimilaritySearchResponse, error)
	// HybridSearch - 混合搜索 (全文 + 向量)
	HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error)
	// DeleteEmbedding - 删除向量
	DeleteEmbedding(ctx context.Context, in *DeleteEmbeddingRequest, opts ...grpc.CallOption) (*DeleteEmbeddingResponse, error)
	// BatchInsert - 批量插入
	BatchInsert(ctx context.Context, in *BatchInsertRequest, opts ...grpc.CallOption) (*BatchInsertResponse, error)
	// BatchUpsertEmbeddings - 批量插入向量
	BatchUpsertEmbeddings(ctx context.Context, in *BatchUpsertEmbeddingsRequest, opts ...grpc.CallOption) (*BatchUpsertEmbeddingsResponse, error)
	// HealthCheck - 服务健康检查
	HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error)
}

type supabaseServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSupabaseServiceClient(cc grpc.ClientConnInterface) SupabaseServiceClient {
	return &supabaseServiceClient{cc}
}

func (c *supabaseServiceClient) Query(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*QueryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResponse)
	err := c.cc.Invoke(ctx, SupabaseService_Query_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) Insert(ctx context.Context, in *InsertRequest, opts ...grpc.CallOption) (*InsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertResponse)
	err := c.cc.Invoke(ctx, SupabaseService_Insert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) Update(ctx context.Context, in *UpdateRequest, opts ...grpc.CallOption) (*UpdateResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateResponse)
	err := c.cc.Invoke(ctx, SupabaseService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) Delete(ctx context.Context, in *DeleteRequest, opts ...grpc.CallOption) (*DeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteResponse)
	err := c.cc.Invoke(ctx, SupabaseService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) Upsert(ctx context.Context, in *UpsertRequest, opts ...grpc.CallOption) (*UpsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertResponse)
	err := c.cc.Invoke(ctx, SupabaseService_Upsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) ExecuteRPC(ctx context.Context, in *RPCRequest, opts ...grpc.CallOption) (*RPCResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RPCResponse)
	err := c.cc.Invoke(ctx, SupabaseService_ExecuteRPC_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) UpsertEmbedding(ctx context.Context, in *UpsertEmbeddingRequest, opts ...grpc.CallOption) (*UpsertEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertEmbeddingResponse)
	err := c.cc.Invoke(ctx, SupabaseService_UpsertEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) SimilaritySearch(ctx context.Context, in *SimilaritySearchRequest, opts ...grpc.CallOption) (*SimilaritySearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SimilaritySearchResponse)
	err := c.cc.Invoke(ctx, SupabaseService_SimilaritySearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) HybridSearch(ctx context.Context, in *HybridSearchRequest, opts ...grpc.CallOption) (*HybridSearchResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HybridSearchResponse)
	err := c.cc.Invoke(ctx, SupabaseService_HybridSearch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) DeleteEmbedding(ctx context.Context, in *DeleteEmbeddingRequest, opts ...grpc.CallOption) (*DeleteEmbeddingResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteEmbeddingResponse)
	err := c.cc.Invoke(ctx, SupabaseService_DeleteEmbedding_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) BatchInsert(ctx context.Context, in *BatchInsertRequest, opts ...grpc.CallOption) (*BatchInsertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchInsertResponse)
	err := c.cc.Invoke(ctx, SupabaseService_BatchInsert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) BatchUpsertEmbeddings(ctx context.Context, in *BatchUpsertEmbeddingsRequest, opts ...grpc.CallOption) (*BatchUpsertEmbeddingsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchUpsertEmbeddingsResponse)
	err := c.cc.Invoke(ctx, SupabaseService_BatchUpsertEmbeddings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *supabaseServiceClient) HealthCheck(ctx context.Context, in *HealthCheckRequest, opts ...grpc.CallOption) (*HealthCheckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthCheckResponse)
	err := c.cc.Invoke(ctx, SupabaseService_HealthCheck_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SupabaseServiceServer is the server API for SupabaseService service.
// All implementations must embed UnimplementedSupabaseServiceServer
// for forward compatibility.
type SupabaseServiceServer interface {
	// Query - 查询数据 (SELECT)
	Query(context.Context, *QueryRequest) (*QueryResponse, error)
	// Insert - 插入数据
	Insert(context.Context, *InsertRequest) (*InsertResponse, error)
	// Update - 更新数据
	Update(context.Context, *UpdateRequest) (*UpdateResponse, error)
	// Delete - 删除数据
	Delete(context.Context, *DeleteRequest) (*DeleteResponse, error)
	// Upsert - 插入或更新 (INSERT ON CONFLICT UPDATE)
	Upsert(context.Context, *UpsertRequest) (*UpsertResponse, error)
	// RPC - 调用 PostgreSQL 函数/存储过程
	ExecuteRPC(context.Context, *RPCRequest) (*RPCResponse, error)
	// UpsertEmbedding - 插入或更新向量嵌入
	UpsertEmbedding(context.Context, *UpsertEmbeddingRequest) (*UpsertEmbeddingResponse, error)
	// SimilaritySearch - 向量相似度搜索
	SimilaritySearch(context.Context, *SimilaritySearchRequest) (*SimilaritySearchResponse, error)
	// HybridSearch - 混合搜索 (全文 + 向量)
	HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error)
	// DeleteEmbedding - 删除向量
	DeleteEmbedding(context.Context, *DeleteEmbeddingRequest) (*DeleteEmbeddingResponse, error)
	// BatchInsert - 批量插入
	BatchInsert(context.Context, *BatchInsertRequest) (*BatchInsertResponse, error)
	// BatchUpsertEmbeddings - 批量插入向量
	BatchUpsertEmbeddings(context.Context, *BatchUpsertEmbeddingsRequest) (*BatchUpsertEmbeddingsResponse, error)
	// HealthCheck - 服务健康检查
	HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error)
	mustEmbedUnimplementedSupabaseServiceServer()
}

// UnimplementedSupabaseServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSupabaseServiceServer struct{}

func (UnimplementedSupabaseServiceServer) Query(context.Context, *QueryRequest) (*QueryResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Query not implemented")
}
func (UnimplementedSupabaseServiceServer) Insert(context.Context, *InsertRequest) (*InsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Insert not implemented")
}
func (UnimplementedSupabaseServiceServer) Update(context.Context, *UpdateRequest) (*UpdateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedSupabaseServiceServer) Delete(context.Context, *DeleteRequest) (*DeleteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedSupabaseServiceServer) Upsert(context.Context, *UpsertRequest) (*UpsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Upsert not implemented")
}
func (UnimplementedSupabaseServiceServer) ExecuteRPC(context.Context, *RPCRequest) (*RPCResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ExecuteRPC not implemented")
}
func (UnimplementedSupabaseServiceServer) UpsertEmbedding(context.Context, *UpsertEmbeddingRequest) (*UpsertEmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpsertEmbedding not implemented")
}
func (UnimplementedSupabaseServiceServer) SimilaritySearch(context.Context, *SimilaritySearchRequest) (*SimilaritySearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SimilaritySearch not implemented")
}
func (UnimplementedSupabaseServiceServer) HybridSearch(context.Context, *HybridSearchRequest) (*HybridSearchResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HybridSearch not implemented")
}
func (UnimplementedSupabaseServiceServer) DeleteEmbedding(context.Context, *DeleteEmbeddingRequest) (*DeleteEmbeddingResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteEmbedding not implemented")
}
func (UnimplementedSupabaseServiceServer) BatchInsert(context.Context, *BatchInsertRequest) (*BatchInsertResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchInsert not implemented")
}
func (UnimplementedSupabaseServiceServer) BatchUpsertEmbeddings(context.Context, *BatchUpsertEmbeddingsRequest) (*BatchUpsertEmbeddingsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method BatchUpsertEmbeddings not implemented")
}
func (UnimplementedSupabaseServiceServer) HealthCheck(context.Context, *HealthCheckRequest) (*HealthCheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method HealthCheck not implemented")
}
func (UnimplementedSupabaseServiceServer) mustEmbedUnimplementedSupabaseServiceServer() {}
func (UnimplementedSupabaseServiceServer) testEmbeddedByValue()                         {}

// UnsafeSupabaseServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SupabaseServiceServer will
// result in compilation errors.
type UnsafeSupabaseServiceServer interface {
	mustEmbedUnimplementedSupabaseServiceServer()
}

func RegisterSupabaseServiceServer(s grpc.ServiceRegistrar, srv SupabaseServiceServer) {
	// If the following call pancis, it indicates UnimplementedSupabaseServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SupabaseService_ServiceDesc, srv)
}

func _SupabaseService_Query_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).Query(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_Query_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).Query(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_Insert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).Insert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_Insert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).Insert(ctx, req.(*InsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).Update(ctx, req.(*UpdateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).Delete(ctx, req.(*DeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_Upsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).Upsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_Upsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).Upsert(ctx, req.(*UpsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_ExecuteRPC_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RPCRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).ExecuteRPC(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_ExecuteRPC_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).ExecuteRPC(ctx, req.(*RPCRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_UpsertEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).UpsertEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_UpsertEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).UpsertEmbedding(ctx, req.(*UpsertEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_SimilaritySearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SimilaritySearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).SimilaritySearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_SimilaritySearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).SimilaritySearch(ctx, req.(*SimilaritySearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_HybridSearch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HybridSearchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).HybridSearch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_HybridSearch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).HybridSearch(ctx, req.(*HybridSearchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_DeleteEmbedding_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteEmbeddingRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).DeleteEmbedding(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_DeleteEmbedding_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).DeleteEmbedding(ctx, req.(*DeleteEmbeddingRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_BatchInsert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchInsertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).BatchInsert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_BatchInsert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).BatchInsert(ctx, req.(*BatchInsertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_BatchUpsertEmbeddings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchUpsertEmbeddingsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).BatchUpsertEmbeddings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_BatchUpsertEmbeddings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).BatchUpsertEmbeddings(ctx, req.(*BatchUpsertEmbeddingsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SupabaseService_HealthCheck_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HealthCheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SupabaseServiceServer).HealthCheck(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SupabaseService_HealthCheck_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SupabaseServiceServer).HealthCheck(ctx, req.(*HealthCheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SupabaseService_ServiceDesc is the grpc.ServiceDesc for SupabaseService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SupabaseService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "isa.supabase.SupabaseService",
	HandlerType: (*SupabaseServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Query",
			Handler:    _SupabaseService_Query_Handler,
		},
		{
			MethodName: "Insert",
			Handler:    _SupabaseService_Insert_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _SupabaseService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _SupabaseService_Delete_Handler,
		},
		{
			MethodName: "Upsert",
			Handler:    _SupabaseService_Upsert_Handler,
		},
		{
			MethodName: "ExecuteRPC",
			Handler:    _SupabaseService_ExecuteRPC_Handler,
		},
		{
			MethodName: "UpsertEmbedding",
			Handler:    _SupabaseService_UpsertEmbedding_Handler,
		},
		{
			MethodName: "SimilaritySearch",
			Handler:    _SupabaseService_SimilaritySearch_Handler,
		},
		{
			MethodName: "HybridSearch",
			Handler:    _SupabaseService_HybridSearch_Handler,
		},
		{
			MethodName: "DeleteEmbedding",
			Handler:    _SupabaseService_DeleteEmbedding_Handler,
		},
		{
			MethodName: "BatchInsert",
			Handler:    _SupabaseService_BatchInsert_Handler,
		},
		{
			MethodName: "BatchUpsertEmbeddings",
			Handler:    _SupabaseService_BatchUpsertEmbeddings_Handler,
		},
		{
			MethodName: "HealthCheck",
			Handler:    _SupabaseService_HealthCheck_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "supabase_service.proto",
}
