# ============================================
# isA Platform - Data Stores
# ============================================
# Databases, cache, object storage, time-series, graph DB, MQTT

services:
  # ============== Relational Database (Supabase PostgreSQL + Extensions) ==============

  postgres:
    image: ${POSTGRES_IMAGE:-public.ecr.aws/supabase/postgres:17.4.1.043}
    container_name: isa-postgres
    command:
      - postgres
      - -c
      - config_file=/etc/postgresql/postgresql.conf
      - -c
      - log_min_messages=fatal
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGPORT: 5432
      POSTGRES_PORT: 5432
      PGPASSWORD: ${POSTGRES_PASSWORD:-postgres}
      JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      JWT_EXP: ${JWT_EXPIRY:-3600}
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - isa-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h localhost"]
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped

  # ============== Cache ==============

  redis:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.redis
    image: isa-redis:latest
    container_name: isa-redis
    ports:
      - "${REDIS_PORT:-6379}:6379"
    volumes:
      - redis-data:/data
    networks:
      - isa-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ============== Object Storage ==============

  minio:
    image: ${MINIO_IMAGE:-minio/minio:latest}
    container_name: isa-minio
    command: server /data --console-address ":9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER:-minioadmin}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD:-minioadmin}
    ports:
      - "${MINIO_API_PORT:-9000}:9000"
      - "${MINIO_CONSOLE_PORT:-9001}:9001"
    volumes:
      - minio-data:/data
    networks:
      - isa-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
    restart: unless-stopped

  # ============== Graph Database ==============

  neo4j:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.neo4j
    image: isa-neo4j:latest
    container_name: isa-neo4j
    environment:
      - NEO4J_AUTH=${NEO4J_AUTH:-neo4j/isa_neo4j_2024}
      - NEO4J_PLUGINS=["apoc"]
      - NEO4J_dbms_memory_heap_max__size=2G
      - NEO4J_dbms_memory_pagecache_size=1G
    ports:
      - "${NEO4J_HTTP_PORT:-7474}:7474"
      - "${NEO4J_BOLT_PORT:-7687}:7687"
    volumes:
      - neo4j-data:/data
    networks:
      - isa-network
    healthcheck:
      test: ["CMD", "cypher-shell", "-u", "neo4j", "-p", "isa_neo4j_2024", "RETURN 1"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # ============== Time-Series Database ==============

  influxdb:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.influxdb
    image: isa-influxdb:latest
    container_name: isa-influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=${INFLUXDB_ADMIN_USER:-admin}
      - DOCKER_INFLUXDB_INIT_PASSWORD=${INFLUXDB_ADMIN_PASSWORD:-isa_influx_2024}
      - DOCKER_INFLUXDB_INIT_ORG=${INFLUXDB_ORG:-isa-platform}
      - DOCKER_INFLUXDB_INIT_BUCKET=${INFLUXDB_BUCKET:-metrics}
      - DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=${INFLUXDB_ADMIN_TOKEN:-isa_influx_admin_token_2024}
    ports:
      - "${INFLUXDB_PORT:-8086}:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    networks:
      - isa-network
    healthcheck:
      test: ["CMD", "influx", "ping"]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped

  # ============== MQTT Broker ==============

  mosquitto:
    build:
      context: ..
      dockerfile: dockerfiles/Dockerfile.mosquitto
    image: isa-mosquitto:latest
    container_name: isa-mosquitto
    ports:
      - "${MQTT_PORT:-1883}:1883"
      - "${MQTT_WS_PORT:-9001}:9001"
    volumes:
      - mosquitto-data:/mosquitto/data
      - mosquitto-log:/mosquitto/log
    networks:
      - isa-network
    healthcheck:
      test: ["CMD", "mosquitto_sub", "-t", "$$SYS/#", "-C", "1", "-i", "healthcheck"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # ============== Supabase Services ==============
  # Complete Supabase stack: Auth, REST API, Realtime, Storage, Studio

  supabase-kong:
    image: ${KONG_IMAGE:-kong:2.8.1}
    container_name: isa-supabase-kong
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /var/lib/kong/kong.yml
      KONG_DNS_ORDER: LAST,A,CNAME
      KONG_PLUGINS: request-transformer,cors,key-auth,acl,basic-auth
      KONG_NGINX_PROXY_PROXY_BUFFER_SIZE: 160k
      KONG_NGINX_PROXY_PROXY_BUFFERS: 64 160k
      # Supabase API keys for Kong auth
      ANON_KEY: ${ANON_KEY}
      SERVICE_ROLE_KEY: ${SERVICE_ROLE_KEY}
    ports:
      - "${SUPABASE_KONG_HTTP_PORT:-54321}:8000/tcp"
      - "${SUPABASE_KONG_HTTPS_PORT:-54322}:8443/tcp"
    volumes:
      - ../configs/test/kong-supabase.yml:/var/lib/kong/kong.yml:ro
    networks:
      - isa-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  supabase-auth:
    image: ${GOTRUE_IMAGE:-public.ecr.aws/supabase/gotrue:v2.176.1}
    container_name: isa-supabase-auth
    environment:
      GOTRUE_API_HOST: 0.0.0.0
      GOTRUE_API_PORT: 9999
      API_EXTERNAL_URL: ${SUPABASE_API_EXTERNAL_URL:-http://localhost:54321}

      GOTRUE_DB_DRIVER: postgres
      # Fixed: Removed search_path=test to match supabase local configuration
      # GoTrue expects auth schema in default search path, not test schema
      GOTRUE_DB_DATABASE_URL: postgres://supabase_auth_admin:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres

      GOTRUE_SITE_URL: ${SUPABASE_SITE_URL:-http://localhost:3000}
      GOTRUE_URI_ALLOW_LIST: ${SUPABASE_ADDITIONAL_REDIRECT_URLS:-}
      GOTRUE_DISABLE_SIGNUP: ${SUPABASE_DISABLE_SIGNUP:-false}

      GOTRUE_JWT_ADMIN_ROLES: service_role
      GOTRUE_JWT_AUD: authenticated
      GOTRUE_JWT_DEFAULT_GROUP_NAME: authenticated
      GOTRUE_JWT_EXP: ${JWT_EXPIRY:-3600}
      GOTRUE_JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}

      GOTRUE_EXTERNAL_EMAIL_ENABLED: ${ENABLE_EMAIL_SIGNUP:-true}
      GOTRUE_MAILER_AUTOCONFIRM: ${ENABLE_EMAIL_AUTOCONFIRM:-true}
      GOTRUE_SMTP_HOST: ${SMTP_HOST:-}
      GOTRUE_SMTP_PORT: ${SMTP_PORT:-587}
      GOTRUE_SMTP_USER: ${SMTP_USER:-}
      GOTRUE_SMTP_PASS: ${SMTP_PASS:-}
      GOTRUE_SMTP_ADMIN_EMAIL: ${SMTP_ADMIN_EMAIL:-admin@example.com}
      GOTRUE_MAILER_URLPATHS_INVITE: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_CONFIRMATION: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_RECOVERY: /auth/v1/verify
      GOTRUE_MAILER_URLPATHS_EMAIL_CHANGE: /auth/v1/verify
    networks:
      - isa-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  supabase-rest:
    image: ${POSTGREST_IMAGE:-public.ecr.aws/supabase/postgrest:v12.2.12}
    container_name: isa-supabase-rest
    environment:
      # Fixed: Removed search_path from URI to match supabase local configuration
      PGRST_DB_URI: postgres://authenticator:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      # Expose multiple schemas: public, graphql_public, dev, test (like supabase local)
      PGRST_DB_SCHEMAS: ${PGRST_DB_SCHEMAS:-public,graphql_public,dev,test}
      # Extra search path for schema resolution
      PGRST_DB_EXTRA_SEARCH_PATH: ${PGRST_DB_EXTRA_SEARCH_PATH:-public,extensions,dev,test}
      PGRST_DB_ANON_ROLE: anon
      PGRST_JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      PGRST_DB_USE_LEGACY_GUCS: "false"
      PGRST_APP_SETTINGS_JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      PGRST_APP_SETTINGS_JWT_EXP: ${JWT_EXPIRY:-3600}
    networks:
      - isa-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  supabase-realtime:
    image: ${REALTIME_IMAGE:-public.ecr.aws/supabase/realtime:v2.36.18}
    container_name: isa-supabase-realtime
    environment:
      PORT: 4000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: supabase_admin
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      DB_NAME: postgres
      # Fixed: Prioritize _realtime schema, include public,dev,test for multi-schema support
      DB_AFTER_CONNECT_QUERY: 'SET search_path TO _realtime,public,dev,test'
      DB_ENC_KEY: supabaserealtime
      API_JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      FLY_ALLOC_ID: fly123
      FLY_APP_NAME: realtime
      SECRET_KEY_BASE: UpNVntn3cDxHJpq99YMc1T1AQgQpc8kfYTuRgBiYa15BLrx8etQoXz3gZv1/u2oq
      ERL_AFLAGS: -proto_dist inet_tcp
      ENABLE_TAILSCALE: "false"
      DNS_NODES: "''"
      RLIMIT_NOFILE: "1048576"
      APP_NAME: realtime
    command: >
      sh -c "/app/bin/migrate && /app/bin/realtime eval 'Realtime.Release.seeds(Realtime.Repo)' && /app/bin/server"
    networks:
      - isa-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  supabase-storage:
    image: ${STORAGE_IMAGE:-public.ecr.aws/supabase/storage-api:v1.24.6}
    container_name: isa-supabase-storage
    environment:
      ANON_KEY: ${ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0}
      SERVICE_KEY: ${SERVICE_ROLE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU}
      POSTGREST_URL: http://supabase-rest:3000
      PGRST_JWT_SECRET: ${JWT_SECRET:-super-secret-jwt-token-with-at-least-32-characters-long}
      DATABASE_URL: postgres://supabase_storage_admin:${POSTGRES_PASSWORD:-postgres}@postgres:5432/postgres
      FILE_SIZE_LIMIT: 52428800
      STORAGE_BACKEND: file
      FILE_STORAGE_BACKEND_PATH: /var/lib/storage
      TENANT_ID: stub
      REGION: stub
      GLOBAL_S3_BUCKET: stub
      ENABLE_IMAGE_TRANSFORMATION: "true"
      IMGPROXY_URL: http://supabase-imgproxy:5001
    volumes:
      - supabase-storage-data:/var/lib/storage:z
    networks:
      - isa-network
    depends_on:
      postgres:
        condition: service_healthy
      supabase-rest:
        condition: service_started
    restart: unless-stopped

  supabase-imgproxy:
    image: ${IMGPROXY_IMAGE:-darthsim/imgproxy:latest}
    container_name: isa-supabase-imgproxy
    environment:
      IMGPROXY_BIND: ":5001"
      IMGPROXY_LOCAL_FILESYSTEM_ROOT: /
      IMGPROXY_USE_ETAG: "true"
      IMGPROXY_ENABLE_WEBP_DETECTION: ${IMGPROXY_ENABLE_WEBP_DETECTION:-true}
    volumes:
      - supabase-storage-data:/var/lib/storage:z
    networks:
      - isa-network
    restart: unless-stopped

  supabase-meta:
    image: ${POSTGRES_META_IMAGE:-public.ecr.aws/supabase/postgres-meta:v0.89.3}
    container_name: isa-supabase-meta
    environment:
      PG_META_PORT: 8080
      PG_META_DB_HOST: postgres
      PG_META_DB_PORT: 5432
      PG_META_DB_NAME: postgres
      PG_META_DB_USER: supabase_admin
      PG_META_DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
    networks:
      - isa-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped

  supabase-studio:
    image: ${STUDIO_IMAGE:-supabase/studio:latest}
    container_name: isa-supabase-studio
    environment:
      STUDIO_PG_META_URL: http://supabase-meta:8080
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}

      DEFAULT_ORGANIZATION_NAME: ${STUDIO_DEFAULT_ORGANIZATION:-isA Platform}
      DEFAULT_PROJECT_NAME: ${STUDIO_DEFAULT_PROJECT:-isA Project}

      SUPABASE_URL: ${SUPABASE_API_EXTERNAL_URL:-http://localhost:54321}
      SUPABASE_PUBLIC_URL: ${SUPABASE_API_EXTERNAL_URL:-http://localhost:54321}
      SUPABASE_ANON_KEY: ${ANON_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6ImFub24iLCJleHAiOjE5ODM4MTI5OTZ9.CRXP1A7WOeoJeXxjNni43kdQwgnWNReilDMblYTn_I0}
      SUPABASE_SERVICE_KEY: ${SERVICE_ROLE_KEY:-eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZS1kZW1vIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImV4cCI6MTk4MzgxMjk5Nn0.EGIM96RAZx35lJzdJsyH-qQwv8Hdp7fsn3W0YpN81IU}

      NEXT_PUBLIC_ENABLE_LOGS: true
      NEXT_ANALYTICS_BACKEND_PROVIDER: postgres
    networks:
      - isa-network
    depends_on:
      supabase-meta:
        condition: service_started
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:3000/api/profile', (r) => {process.exit(r.statusCode === 200 ? 0 : 1)})"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

# Networks and volumes are defined in compose/base.yml
