# ============================================
# isA Platform - Observability Stack
# ============================================
# Centralized logging: Loki + Promtail + Grafana
# Services send logs directly to Loki via HTTP (python-logging-loki)

services:
  # ============== Log Aggregation ==============

  loki:
    image: ${LOKI_IMAGE:-grafana/loki:2.9.3}
    container_name: isa-loki
    ports:
      - "${LOKI_PORT:-3100}:3100"
    volumes:
      - ../configs/test/loki-config.yml:/etc/loki/local-config.yaml
      - loki-data:/loki
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - isa-network
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3100/ready"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # ============== Log Collector (File-based - Optional) ==============
  # NOTE: Most services use direct HTTP to Loki via python-logging-loki
  # Promtail is for legacy file-based logs or system logs

  promtail:
    image: ${PROMTAIL_IMAGE:-grafana/promtail:2.9.3}
    container_name: isa-promtail
    volumes:
      - ../configs/test/promtail-config.yml:/etc/promtail/config.yml
      - /var/log:/var/log:ro
      - ${ISA_USER_LOGS:-../../isA_user/logs}:/var/logs/user:ro
      - ${ISA_AGENT_LOGS:-../../isA_Agent/logs}:/var/logs/agent:ro
      - ${ISA_MODEL_LOGS:-../../isA_Model/logs}:/var/logs/model:ro
      - ${ISA_MCP_LOGS:-../../isA_MCP/logs}:/var/logs/mcp:ro
    command: -config.file=/etc/promtail/config.yml
    networks:
      - isa-network
    depends_on:
      - loki
    restart: unless-stopped

  # ============== Visualization & Dashboards ==============

  grafana:
    image: ${GRAFANA_IMAGE:-grafana/grafana:10.2.3}
    container_name: isa-grafana
    ports:
      - "${GRAFANA_PORT:-3003}:3000"
    environment:
      # Authentication
      - GF_AUTH_ANONYMOUS_ENABLED=${GF_AUTH_ANONYMOUS_ENABLED:-true}
      - GF_AUTH_ANONYMOUS_ORG_ROLE=${GF_AUTH_ANONYMOUS_ORG_ROLE:-Viewer}
      - GF_AUTH_DISABLE_LOGIN_FORM=${GF_AUTH_DISABLE_LOGIN_FORM:-false}
      - GF_SECURITY_ADMIN_USER=${GF_ADMIN_USER:-admin}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_ADMIN_PASSWORD:-admin}

      # Plugins
      - GF_INSTALL_PLUGINS=${GF_INSTALL_PLUGINS:-}

      # Server
      - GF_SERVER_ROOT_URL=${GRAFANA_ROOT_URL:-http://localhost:3003}
      - GF_SERVER_DOMAIN=${GRAFANA_DOMAIN:-localhost}
    volumes:
      - grafana-data:/var/lib/grafana
      - ../configs/test/grafana/provisioning:/etc/grafana/provisioning
      - ../configs/test/grafana/dashboards:/var/lib/grafana/dashboards
    networks:
      - isa-network
    depends_on:
      - loki
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:3000/api/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

# Networks and volumes are defined in compose/base.yml
