apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "hms.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "hms.selectorLabels" . | nindent 4 }}
  ports:
    - name: thrift
      port: {{ .Values.port }}
      targetPort: thrift
      protocol: TCP
